### ISSUE TITLE
Optimizations failure - Cannot resolve module/file/directory

### ISSUE THREAD

**Issue by cadab** [sivasamyk/logtrail#1]
Kibana version: 4.5.3

I've tried installing the plugin using the following command:

`./bin/kibana plugin -i konsole -u https://github.com/sivasamyk/konsole/archive/master.zip
`

And i get the following error 

```
Optimizing and caching browser bundles...
Plugin installation was unsuccessful due to error "Optimizations failure.

    ERROR in ./installedPlugins/konsole/public/app.js
    Module not found: Error: Cannot resolve module 'sugar-date' in /opt/kibana/installedPlugins/konsole/public
     @ ./installedPlugins/konsole/public/app.js 25:17-38

    ERROR in ./installedPlugins/konsole/public/app.js
    Module not found: Error: Cannot resolve 'file' or 'directory' /opt/kibana/src/ui/public/autoload/styles in /opt/kibana/installedPlugins/konsole/public
     @ ./installedPlugins/konsole/public/app.js 29:0-29
"
root@9539e9ec5bba:/opt/kibana# Plugin installation was unsuccessful due to error "Optimizations failure.

```

Have you got any pointers to fix the issue?

Thanks.

**Comment by sivasamyk** [comment]
James,
Thanks for trying out the plugin.  You need to specify the URL of plugin package zip while installing. You are trying to install the plugin from the source code. This will not work since the dependencies are not packaged.
The current plugin code support only Kibana 5.0 and Elasticsearch 5.0. 
Currently I am making changes to support Kibana 4.5.  Once I am done, I will upload the package and publish the URL.

If you are still interested in trying out the plugin, you can download the source code and run the plugin from source using `npm start`

**Comment by cadab** [comment]
Hi,

Thanks for getting back to me. I managed to fix the first error by installing the missing lib.

The other error i'm guessing is because i'm not running Kibana 5.

Ive managed to get the plugin installed by removing the autoload/style line from app.js, however nothing new has shown up in Kibana, I'm guessing there more issues with it being developed for Kibana 5.

Just as a bit of interest, do you have a screenshot of the plugin in use? Also what url would the plugin be available from within Kibana?

Thanks.

**Comment by sivasamyk** [comment]
The idea is to replicate the functionality of [PaperTrailApp](https://papertrailapp.com/). Following are the features currently implemented, once all syslog events are indexed in Elasticsearch using logstash
1)  Event viewer to view all syslog event
2) search the event logs ( see search bar in the below screenshot )
3) seek to any time in the logs - as shown in second screenshot.
4) filter by host (Clicking All System button will show all the hostname from which logs are collected), program
5) Live tail

URL of plugin :` https://localhost:5601/zke/app/konsole#/?_g=() `[notice this is from development setup. zke might change based on random proxy URL generated by kibana]

Following are some screenshots
![konsole](https://cloud.githubusercontent.com/assets/1464186/18093531/ccbdc624-6eed-11e6-812a-9c36635e6034.png)
![konsole-time-seek](https://cloud.githubusercontent.com/assets/1464186/18093530/ccbcdffc-6eed-11e6-8015-1a0f050b6bc5.png)

**Comment by sivasamyk** [comment]
You can install the plugin for 4.x kibana by executing `./bin/kibana plugin -i logtrail -u https://github.com/sivasamyk/logtrail/releases/download/v4.x-0.1.0/logtrail-4.x-0.1.0.tar.gz`

Please check readme for other configuration options.

**Comment by cadab** [comment]
@sivasamyk Ive tried installing it this morning, using the above command. The install looked to be successful, however theres no new application link showing up within kibana.  Any ideas?

**Comment by sivasamyk** [comment]
@cadab Let me know the Kibana version you are using. The mentioned command work for 4.x versions.   Can you attach the Kibana startup logs? You should see something like

`  log   [14:01:30.934] [info][status][plugin:logtrail@0.1.0] Status changed from uninitialized to green - Ready
`
I have tested with Kibana 4.5 and 4.6 versions.

**Comment by cadab** [comment]
@sivasamyk using Kibana 4.5.3.

I restarted kibana in order to get the start up logs, and the app has shown up. So just a restart was needed.

The next issue... :)

The app is reporting an error "error! Cannot connect to elasticsearch : undefined", ive looked in the .json config and cant see anywhere to set the connection to elastic search. Kibana is running as normal.

**Comment by sivasamyk** [comment]
@cadab Thanks for your feedback. This is because your Elasticsearch index used for syslog events ( logstash-* by default) does not contain any data. I would recommend you to start logstash with mentioned config in the README. Once you have some syslog events indexed in ES, you should be able to see that events.  I will fix this error to show proper message in this case.

**Comment by cadab** [comment]
@sivasamyk I've updated the json config to use a different index, one which has data. Ive also changed the type to be 'log'.

I wanted to use this plugin to tail our log messages already being shipped, we dont use syslog messages, i was hoping some tweaks in the config (or maybe code) would allow this.

After changing the config will i need to restart?

**Comment by cadab** [comment]
@sivasamyk 

After restarting the error went away, but no events were shown.

I edited the server.js file and removed the default field from the query request.

I'm not seeing new lines in the viewer, but everyline is a colon ":", clicking on one returns program: 'undefined'.

Guessing theres more stuff to change as your view code is expecting certain syslog fields?

**Comment by sivasamyk** [comment]
Yes. The code expects following fields in the ES : `syslog_timestamp syslog_hostname syslog_program:syslog_message received_at`. I assume you do not have these fields in your indexes and you are not using the logstash config mentioned in README.

**Comment by cadab** [comment]
Yeah, i appreciate the help even though i'm not using it as expected.

Should it just be a case of changing the template/index.html file to use the returned fields i have specified?

**Comment by sivasamyk** [comment]
Changing in index.html should show the events. Also change respective fields in server.js and validate.js.  Make sure you have a field `received_at ` for timestamp.

**Comment by sivasamyk** [comment]
Make sure you also make required changes in logtrail.json fields.

**Comment by cadab** [comment]
Thanks for your help.

Its now displaying my log messages as expected :+1: 

Only issue is the timestamp, the timestamp we use in logstash is the standard "@timestamp", using this breaks the templating. Other quick question, ive added console logging of the event object in app.js, but thats not displayed.

**Comment by sivasamyk** [comment]
Awesome. 
The plugin assumes standard timestamp format . Do you have field `received_from` in you ES index. Due to absence of this field, there might be some exceptions.

Have you checked-in your changes in you fork. If so I can look at your changes and comment on them.

I am planning to add a mapper option in logtrail.json where you can map your syslog fields to standard logtrail fields.  Once done, you do not have to make these changes. Will keep you updated.

**Comment by cadab** [comment]
Yeah my changes are checked into the fork.

And no I dont have the received_from field. I'm looking into how easy this would be too add.

**Comment by sivasamyk** [comment]
If you using logstash add following codec (Correction the field name is `received_at):`

`grok {
 add_field => [ "received_at", "%{@timestamp}" ]
}`

**Comment by sivasamyk** [comment]
@cadab I see the console.log(event) changes in server.js but not in app.js. Any change in server.js will be logged in Kibana server logs.

**Comment by cadab** [comment]
![](http://i.imgur.com/032PKoG.png)

Added received_at to logstash, added back into template and .json config.

Thanks for all your help.

**Comment by sivasamyk** [comment]
Great. Let me know your feedback and do report if you find any issues.

**Comment by sivasamyk** [comment]
@cadab I have updated the logtrail.json and code by providing options to map custom fields. You can install latest software using `./bin/kibana plugin -i logtrail -u https://github.com/sivasamyk/logtrail/releases/download/v4.x-0.1.0/logtrail-4.x-0.1.0.tar.gz`. I have also updated readme with instructions to map existing logs from ES. Please check let me know if you face any issues.

**Comment by cadab** [comment]
@sivasamyk Awesome, i'll give it a go tomorrow when I get chance, and let you know.

**Comment by cadab** [comment]
@sivasamyk I just got it installed now, works just as expected.

Only issue i can see, when clicking on the 'program' field it adds a search looking for a 'program' field, but I have that mapped to a different field, so the search will always be empty.

i.e. `"program": "Level",` (I want level in the display)

But clicking on the level in the logs adds a search for `program: "DEBUG"` rather than `level: "DEBUG"`

**Comment by sivasamyk** [comment]
oops. Fixed this issue and uploaded the latest tar.gz. You try reinstalling the plugin. Thanks again for your feedback.

**Comment by cadab** [comment]
Thanks, working perfectly now.

![](http://i.imgur.com/TYl9KXM.png)

**Comment by sivasamyk** [comment]
👌
