### ISSUE TITLE
Failed to parse query [/users/28474/notes?_=238427835]

### ISSUE THREAD

**Issue by tioteath** [sivasamyk/logtrail#107]
Looks like it is impossible to search the line containing slashes and other non-alphanumeric symbols:
```
Error! Exception while executing search query :[query_shard_exception]  Failed to parse query [/users/28474/notes?_=238427835]
```

**Comment by sivasamyk** [comment]
Can you try enclosing your query string in double quotes : "/users/28474/notes?_=238427835"

For more info on query string syntax refer : https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html#query-string-syntax

**Comment by sivasamyk** [comment]
Solution is to enclose the query string in double quotes. Closing the issue.
