### ISSUE TITLE
use logtrail with multiple indexes

### ISSUE THREAD

**Issue by dpgaspar** [sivasamyk/logtrail#11]
Hi,

Great plugin, is it possible to use this plugin for multiple ES indices?

**Comment by sivasamyk** [comment]
Thanks.  Do you mean you need ability to view logs from multiple indices each with different document schema in a single view?  ( similar to Kibana multiple index patterns). or support for multiple indexes with different document schema in different view?

**Comment by dpgaspar** [comment]
Well ideally use multiple indexes with different document schemas, being able to on logstrail.json to define multiple indexes and field mappings.

PS:
I'm going to test the alias "solution" to see if it's possible with my schemas

**Comment by sivasamyk** [comment]
Got it. I will add option to declare multiple index patterns in logtrail.json each with its own mapping. In the logtrail console view, you can select the index pattern and view the logs from the selected pattern ( you won't be able to see logs from multiple index pattern in single view). Will this solve your issue? 

I am not aware about alias solution. Can you please explain or check-in the changes in your fork?

**Comment by dpgaspar** [comment]
@sivasamyk thats simply great!

How are you planning to change the logtrail.json?

{[
  "es": {
    "default_index": "logstash-*",
    "allow_url_parameter": false,
    "timezone": "UTC"
  },
  "tail_interval_in_seconds": 10,
  "max_buckets": 500,
  "nested_objects" : false,
  "default_time_range_in_days" : 0,
  "fields" : {
    "mapping" : {
        "timestamp" : "@timestamp",
        "display_timestamp" : "syslog_timestamp",
        "hostname" : "hostname",
        "program": "program",
        "message": "syslog_message"
    }
  },
  "es": {
    "default_index": "nginx-*",
    "allow_url_parameter": false,
    "timezone": "UTC"
  },
  "tail_interval_in_seconds": 10,
  "max_buckets": 500,
  "nested_objects" : false,
  "default_time_range_in_days" : 0,
  "fields" : {
    "mapping" : {
        "timestamp" : "@timestamp",
        "display_timestamp" : "@timestamp",
        "hostname" : "hostname",
        "program": "code",
        "message": "path"
    }
  }
]}

Could be an option, but you had to be careful not to introduce any breaking feature. Test is it's a list or not (or something like it).

Regarding the alias: https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-aliases.html

Haven't checked if it's 5.0 specific.

**Comment by dpgaspar** [comment]
Any news on this? do you need help?

**Comment by dpgaspar** [comment]
Thanks!

**Comment by sivasamyk** [comment]
I have added the option to specify multiple indexes in logtrail.json. By default the first index will be shown. Need to provide an option in UI to select the index. Will push the changes to a branch soon.

**Comment by laywin** [comment]
great plugin,why not query kibana index pattern to get index metadata data(default index,multiple indexes)?feel config logtrail.json is not a good way!

**Comment by sivasamyk** [comment]
@laywin thanks. logtrail.json has other configuration parameters like logtrail specific field mappings, default fetch count,  etc. In future, the plan is to move logtrail config to UI similar to Kibana.

**Comment by laywin** [comment]
@sivasamyk  happy to see your update!

**Comment by dpgaspar** [comment]
Hi @sivasamyk,

Looking forward for the update, thanks!

**Comment by shmish111** [comment]
Will there be a release for this soon? Asking to use master branch versions of things doesn't go down well where I work :smiley: 

Pretty cool idea by the way.

**Comment by sivasamyk** [comment]
@shmish111 Will try to get a preview early next week!

**Comment by dpgaspar** [comment]
Thank you for your time on this!

**Comment by sivasamyk** [comment]
@dpgaspar @shmish111 Find attached a logtrail plugin with support for multiple indexes. The changes in logtrail.json are not backward compatible. You can select the required index from 'Settings' button. Please note this plugin is compatible with Kibana 5.1.1

Test and let me know if any issues

[logtrail-5.x-0.1.7.zip](https://github.com/sivasamyk/logtrail/files/666730/logtrail-5.x-0.1.7.zip)

**Comment by dpgaspar** [comment]
Kibana 5.X chuifff... i'm using 4.X, is it very hard do port it to 4.X?

**Comment by dpgaspar** [comment]
Many thanks. I'll find a window to drop this on testing.

**Comment by sivasamyk** [comment]
0.1.7 release supports this feature 
https://github.com/sivasamyk/logtrail/releases/tag/0.1.7
