### ISSUE TITLE
Validating Elasticsearch index issue

### ISSUE THREAD

**Issue by lantern77** [sivasamyk/logtrail#112]
Hello, while looking into the source code for logTrail and making changes for my own use,

I noticed a small bug when calling for validation in LogTrail 5.
In "app.js" you make a post request to '/logtrail/validate/es' with params = {index} on line 105
However on line 7 of "validate_es.js" an attempt is made to get the index with 'request.params.index'. Shouldn't this be 'request.payload.index'? As we pass it through the post data and not the url.

I noticed this when trying to validate for an invalid index parameter. This may have been missed when kibana 5 was made from kibana 4?

Regards Peter
Thanks for taking your time to read this :)

**Comment by sivasamyk** [comment]
Thats a bug. Thanks for the issue. Will fix it in next release
