### ISSUE TITLE
Search Functionality is not working fine

### ISSUE THREAD

**Issue by cabhi** [sivasamyk/logtrail#117]
Hi

I am using logtrail with kibana and es - 5.4.1. Both kibana and es are running is containers and i insatlled logtrail plugin as per the document.

I can see the logs correctly in live mode but when i search something it doesn't show the full logs + adds some UI tags.

For example

Sample Logs- 
![full log](https://cloud.githubusercontent.com/assets/7628259/26816516/97842360-4aaf-11e7-9442-1f73122f9946.PNG)

After Search
![search result](https://cloud.githubusercontent.com/assets/7628259/26816532/a500e7b2-4aaf-11e7-9e36-2791064e180f.PNG)

Its not showing full line of log + also added <span class='highlight'>

**Comment by sivasamyk** [comment]
@cabhi These tags are added as part of highlight feature. If you have upgraded from 0.1.13 please change message_fromat field in logtrail.json from {{syslog_message}} to **{{{syslog_message}}}** ( notice 3 curly braces)

**Comment by cabhi** [comment]
@sivasamyk  Thanks that worked. it would be nice to update the same in documentations.
Also i have one more query. Can i give custom time range in seek instead of Range -><<in time>>to now

**Comment by sivasamyk** [comment]
Can i give custom time range in seek instead of Range -><>to now - I assume you need to filter events between 2 timestamps T1 and T2.  Currently it is not possible. You can go to a particular time using seek and scroll down till you reach the latest event. ( logtrail won't fetch all events on one query).

**Comment by cabhi** [comment]
Thanks for the quick reply :)
Is there any debug option where I can see the query being fired on es in logs ??

**Comment by sivasamyk** [comment]
Currently there are no debug options . You can uncomment `//console.log(JSON.stringify(searchRequest));` line in plugins/logtrail/server/routes/server.js file and restart Kibana.

**Comment by cabhi** [comment]
Thanks for the replies :)
I got another cosmetic UI error.

Once we click on any of the buttons ( System, Time Range, Settings) it is not closing already opened input box which makes it totally cluttered. 


![ui error](https://cloud.githubusercontent.com/assets/7628259/26822306/317d0e84-4ac7-11e7-9f1e-56d8e8512505.PNG)

**Comment by sivasamyk** [comment]
Thanks for reporting this issue. Its a known issue. You can click outside ( in the console) to close the popups. Will fix this in next release.

**Comment by sivasamyk** [comment]
The UI issue is fixed in latest release @ https://github.com/sivasamyk/logtrail/releases/download/v0.1.15/logtrail-5.4.1-0.1.15.zip
