### ISSUE TITLE
logtrail-4.x webpack errors when installed with Kibana 4.3 

### ISSUE THREAD

**Issue by hardproblems** [sivasamyk/logtrail#119]
I tried installing 4.x.0.1.14 with kibana 4.3 and got an error about webpack (see screenshot). I then tried installing the earliest 4.x release (4.x.0.1.0) but got the same errors. Is there an easy work around for this webpack error (we can't upgrade to kibana 4.4 because it requires upgrading ES from 2.1 to 2.2 and 2.2 had lots of mapping changes and would be a much more risky and time consuming activity).

Thank you so much for creating this plugin!

![screen shot 2017-06-09 at 1 05 51 pm](https://user-images.githubusercontent.com/142453/26992671-8e64e082-4d14-11e7-9163-cd2c8568a160.png)

**Comment by sivasamyk** [comment]
@hardproblems There are Kibana API changes between 4.3 and later releases. Some of APIs used by logtrail is not compatible with 4.3.  The basic plugin structure is also not compatible.

**Comment by sivasamyk** [comment]
Latest logtrail is not compatible with Kibana 4.3. Recommend upgrading to latest Kibana.
