### ISSUE TITLE
show message log level

### ISSUE THREAD

**Issue by TimMeissner** [sivasamyk/logtrail#12]
We have a 'level' field in our json document that indicates whether a log message is Debug, Info, Warning, Error, ... would be nice to have this aswell with some color coding in the logtrail view.

**Comment by sivasamyk** [comment]
@TimMeissner currently the fields shown in event view are fixed. Adding support for new fields require changes in code. Regarding color coding based on level, I see if this can be added as config in logtrail.json.

**Comment by danielmotaleite** [comment]
the flexibility to add a few more fields would be very helpful 
no need to call then special names, just name then field1, field2, field3, etc and then in the config
we map the ES field. 
Only field1 is the one mapped to the "all systems" and can be renamed to ALL, so it is generic enough
If possible, show in the "all systems" button the select field if any selected

**Comment by OferE** [comment]
+1

**Comment by airom** [comment]
+1

**Comment by reineruhry** [comment]
Hi,

I've working on a customization to allow coloring messages based on new field called severity.

Right now it was made to attend our business needs, and need some work to make it more dynamic.

Bellow was what I've done.

1. New field called **severity**, that can be used on field mapping, like bellow:

> "fields" : {
>         "mapping" : {
>             "timestamp" : "@timestamp",
>             "display_timestamp" : "@timestamp",
>             "hostname" : "beat.hostname",
>             "program": "fields.node",
>             "message": "message",
>             "severity": "severity"
>         },
> 

2. Changed the css class and added four different classes for message and severity like bellow.

> .message {
>         color: #258CCD;
>         word-break: break-all;
>     word-wrap: break-word;
>     white-space: pre-wrap;
> }
> 
> .message-error a {
>         color: #ff3333;
> }
> 
> .message-warning a {
>         color: #ffff33;
> }
> 
> .message-info a {
>         color: #33cc33;
> }
> 
> .message-debug a {
>         color: #B0B0B0;
> }
> 
> .severity {
>         color: #258CCD;
>         word-break: break-all;
>     word-wrap: break-word;
>     white-space: pre-wrap;
> }
> 
> .severity-error a{
>         color: #ff3333;
> }
> 
> .severity-warning a {
>         color: #ffff33;
> }
> 
> .severity-info a {
>         color: #33cc33;
> }
> 
> .severity-debug a {
>         color: #B0B0B0;
> }

3. A small change on server.js to support the new field.

Now, my questions are, if that's interesting for community, how to share it and what is the way to add this to the project.


Best Regards,
Reiner

**Comment by sivasamyk** [comment]
Thanks for the update. Please send a pull request.

**Comment by sivasamyk** [comment]
@reineruhry Let me know if you need any help in sending the pull request.

**Comment by reineruhry** [comment]
Done!

https://github.com/sivasamyk/logtrail/pull/106

**Comment by sivasamyk** [comment]
Added support for color coding of messages based on field values and support for adding custom fields.

Checkout : https://github.com/sivasamyk/logtrail/blob/master/docs/color_mapping.md
