### ISSUE TITLE
            "display_timestamp" : "@timestamp",

### ISSUE THREAD

**Issue by gavenkoa** [sivasamyk/logtrail#127]
I got:

    Invalid date

in date field until I removed :

     "display_timestamp" : "@timestamp",

After removing current time is displayed...

My `@timestamp` is milliseconds since epoch. ES mapping come from template and is:

          "@timestamp": {
            "type": "date",
            "format": "epoch_millis"
          },

**Comment by sivasamyk** [comment]
Looks like there is some date parsing issue with moment.js. Can you post a sample document from your ES?

**Comment by gavenkoa** [comment]
Of course, it fictional:

    {"@timestamp":"1497909361079","level":"TRACE","logger":"org.defun.logbackes.ESAppenderTest","thread":"main","message":"yy","marker":"login"}

**Comment by sivasamyk** [comment]
From your JSON doc, I see that `@timestamp` is coming as string. Can you configure it as long (number) datatype in ES, so that the query on document return number instead of string?

**Comment by sivasamyk** [comment]
@gavenkoa Are you able to fix this issue? Let me know if you need any help.

**Comment by sivasamyk** [comment]
Reopen if you see any issue after converting timestamp to number.
