### ISSUE TITLE
Program filtering do not work for me

### ISSUE THREAD

**Issue by vcariven** [sivasamyk/logtrail#13]
Clicking on the program should filter the log lines. It (onProgramClick ) updates the userSearchText with the following (in public/app.js):
`$scope.userSearchText = config.fields.mapping['program'] + ': \'' + program + '\'';`
The program value is single-quoted, with in my case does not lead to expected results (generated the following query param: `q=program:%20'my-program'`)
Doucle-quoting the value does the trick:
`$scope.userSearchText = config.fields.mapping['program'] + ': "' + program + '"';`
(generating the following url query param : `q=program:%20%22my-program%22`)

It does not seem te be browser dependent (fyi, I test with Chrome)

Regards

**Comment by sivasamyk** [comment]
Thanks fixed. Please use 1.5.0

 - Kibana 4.x : `./bin/kibana plugin -i logtrail -u https://github.com/sivasamyk/logtrail/releases/download/0.1.5/logtrail-4.x-0.1.5.tar.gz`
 - Kibana 5.x : `./bin/kibana-plugin install https://github.com/sivasamyk/logtrail/releases/download/0.1.5/logtrail-5.x-0.1.5.zip`
