### ISSUE TITLE
Installation works after updating logtrail package.json to 5.2.1 but UI i see no events

### ISSUE THREAD

**Issue by monitoringit** [sivasamyk/logtrail#130]
I have kibana 5.2.1, so i took latest logtrail zip (5.4.2) and update package.json in it to change kibana version to 5.2.1. I then zipped it up again to install. Installation worked smoothly. Now i see logtrail icon on kibana 5.2.1.
 But when i try to search i dont see anything. I also see that it only shows index of logstash when i have several other indices.

[root@ip-xxxxx kibana]# ./bin/kibana-plugin install file:///usr/share/kibana/logtrail-5.2.1-0.1.15.zip
Attempting to transfer from file:///usr/share/kibana/logtrail-5.2.1-0.1.15.zip
Transferring 1353489 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Extracting plugin archive
Extraction complete
Optimizing and caching browser bundles...
Plugin installation complete
[root@ip-xxxx kibana]# service kibana restart
kibana stopped.
kibana started

Any help will be apprciated

**Comment by sivasamyk** [comment]
@monitoringit You can directly use the 5.4.1 release from https://github.com/sivasamyk/logtrail/releases/download/v0.1.15/logtrail-5.4.1-0.1.15.zip

By default logtrail use logstash-* indices. For more indices, you can configure the same in logtrail.json file present in plugins/logtrail dir. This requires a restart of Kibana.

Check if the fields configured in logtrail.json matches with ES. Let me know if you are seeing some errors in Kibana console or UI.

**Comment by monitoringit** [comment]
So with 5.4.1 logtrail i dont have to update kibana version in package.json to 5.2.1? I can just use 5.4.1 logtrail zip with kibana 5.2.1?

Then why is this not the case with 5.4.2 logtrail as when i tried to install 5.4.2 before it complained abt version mismatch between kibana and logtrail forcing me to update package.json

**Comment by sivasamyk** [comment]
Sorry. My bad. I misread 5.2.1 as 5.4.1. Kibana does need exact match between plugin and Kibana version. Do you see any exceptions in Kibana logs/UI? Can you share your logtrail.json and logstash config (if avaibale)?

**Comment by monitoringit** [comment]
I will upload it by tomorrow. Meanwhile do you have 5.2.1 version of logtrail in archives?

**Comment by sivasamyk** [comment]
Sure. I do not seem have a release to support 5.2.1. Can you download 5.2.2 https://github.com/sivasamyk/logtrail/releases/download/0.1.9/logtrail-5.2.2-0.1.9.zip release and downgrade to 5.2.1?

**Comment by monitoringit** [comment]
Will do thx!

**Comment by monitoringit** [comment]
I was able to mske it work...my field settings wrre not correct before. It works now but systems selection link doesnt work but i see that issue was raised by someone else and you fixed it. I will try newer version. 

I want to know how is this plugin different from kibana std UI with autorefresh enabled? You can achieve very similar view of events in kibana ui with autorefresh except that latest msg shows on top vs logtrail shows like a tail of a file?

I see frequency of refresh is more or less for both logtrail view and std kibana UI view

**Comment by monitoringit** [comment]
It would be nice to know the differences between kibana auto refresh and this plugin. More i use this new plugin more i answer my own questions. I am closing this for now. Thx for your help!

**Comment by sivasamyk** [comment]
Logtrail does a periodic query for events created after the last event time present in event console. I assume Kibana also does auto refresh based on periodic refresh. As developer, I find it hard to debug logs from Kibana UI ( it is very good for charts and dashboard). I wanted a console like UI ( influenced by PapertrailApp). Hope this helps!
