### ISSUE TITLE
About monitoring the configuration of multiple events

### ISSUE THREAD

**Issue by firehalt** [sivasamyk/logtrail#131]
Hello，I want to know how to monitor the configuration of multiple events，for example There are three strengths in my configuration file. How do I configure it so that three strengths are displayed? I can only show one now

**Comment by sivasamyk** [comment]
I assume you have your events going into 3 different indices and you want
to see the events from these indices.

Logtrail has support for multiple indices. You can define multiple indices
in logtrail.json and they will be listed accordingly in Settings .

**Comment by firehalt** [comment]
How do I edit in logtrail.json？and my multiple indices name system-log-nginx，system-log，system-network?
      
{
  "index_patterns" : [
    {
      "es": {
       "default_index": "system-log*",
       "allow_url_parameter": false
      },
       "es": {
      {
       "default_index": "system-log-nginx-*",
       "allow_url_parameter": false
      },
      "tail_interval_in_seconds": 10,
      "es_index_time_offset_in_seconds": 0,
      "display_timezone": "local",
      "display_timestamp_format": "MMM DD HH:mm:ss",
      "max_buckets": 500,
      "nested_objects" : false,
      "default_time_range_in_days" : 0,
      "max_hosts": 100,
      "max_events_to_keep_in_viewer": 5000,
      "fields" : {
        "mapping" : {
            "timestamp" : "@timestamp",
            "display_timestamp" : "@timestamp",
            "hostname" : "hostname",
            "program": "program",
            "message": "syslog_message"
        },
        "message_format": "{{{syslog_message}}}"
      }
    }

**Comment by sivasamyk** [comment]
The following is the config for 3 indices. Please edit the `fields.mapping` and `message_format` for each index based on your needs:

```
{
   "index_patterns":[
      {
         "es":{
            "default_index":"system-log-nginx*",
            "allow_url_parameter":false
         },
         "tail_interval_in_seconds":10,
         "es_index_time_offset_in_seconds":0,
         "display_timezone":"local",
         "display_timestamp_format":"MMM DD HH:mm:ss",
         "max_buckets":500,
         "nested_objects":false,
         "default_time_range_in_days":0,
         "max_hosts":100,
         "max_events_to_keep_in_viewer":5000,
         "fields":{
            "mapping":{
               "timestamp":"@timestamp",
               "display_timestamp":"@timestamp",
               "hostname":"hostname",
               "program":"program",
               "message":"syslog_message"
            },
            "message_format":"{{{syslog_message}}}"
         }
      },
      {
         "es":{
            "default_index":"system-log*",
            "allow_url_parameter":false
         },
         "tail_interval_in_seconds":10,
         "es_index_time_offset_in_seconds":0,
         "display_timezone":"local",
         "display_timestamp_format":"MMM DD HH:mm:ss",
         "max_buckets":500,
         "nested_objects":false,
         "default_time_range_in_days":0,
         "max_hosts":100,
         "max_events_to_keep_in_viewer":5000,
         "fields":{
            "mapping":{
               "timestamp":"@timestamp",
               "display_timestamp":"@timestamp",
               "hostname":"hostname",
               "program":"program",
               "message":"syslog_message"
            },
            "message_format":"{{{syslog_message}}}"
         }
      },
      {
         "es":{
            "default_index":"system-network*",
            "allow_url_parameter":false
         },
         "tail_interval_in_seconds":10,
         "es_index_time_offset_in_seconds":0,
         "display_timezone":"local",
         "display_timestamp_format":"MMM DD HH:mm:ss",
         "max_buckets":500,
         "nested_objects":false,
         "default_time_range_in_days":0,
         "max_hosts":100,
         "max_events_to_keep_in_viewer":5000,
         "fields":{
            "mapping":{
               "timestamp":"@timestamp",
               "display_timestamp":"@timestamp",
               "hostname":"hostname",
               "program":"program",
               "message":"syslog_message"
            },
            "message_format":"{{{syslog_message}}}"
         }
      }
   ]
}
```

**Comment by firehalt** [comment]
Thank you

**Comment by firehalt** [comment]
I have new problems，my kibana api display  logtrail  as follows，This is not what I need. I want to show the effect of your project. What should I do?

  Jun 20 16:00:19 elk init:  logstash main process ended, respawning
Jun 20 16:00:19 elk init:  logstash main process (13117) terminated with status 1
Jun 20 16:00:42 elk init:  logstash main process (13158) terminated with status 1
Jun 20 16:00:42 elk init:  logstash main process ended, respawning
Jun 20 16:01:02 elk init:  logstash main process ended, respawning
Jun 20 16:01:02 elk init:  logstash main process (13198) terminated with status 1
Jun 20 16:01:26 elk init:  logstash main process (13250) terminated with status 1
Jun 20 16:01:26 elk init:  logstash main process ended, respawning
Jun 20 16:02:05 elk init:  logstash main process ended, respawning
Jun 20 16:02:05 elk init:  logstash main process (13290) terminated with status 1
Jun 20 16:02:33 elk init:  logstash main process ended, respawning
Jun 20 16:02:33 elk init:  logstash main process (13331) terminated with status 1

**Comment by sivasamyk** [comment]
Please share you logstash conf and logtrail.json. Make sure you modify secure info in the files.

**Comment by firehalt** [comment]
my logstash conf :
[root@elk logtrail]# cat /etc/logstash/conf.d/system.conf 
input
    file {
        path => "/var/log/messages"
        type => "system-log-messages"
        start_position => "beginning"
         }
    file {
        path =>  "/var/log/secure"
        type => "system-log-secure"
        start_position => "beginning"
         }
     file {
        path =>  "/var/log/nginx/access.log"
        type => "system-log-nginx"
        start_position => "beginning"
         }
 		}  
filter {
 }
output {
    if [type] == "system-log-messages" {
    elasticsearch {
        hosts => ["192.168.2.39:9200"]
        index => "system-log-messages-%{+YYYY-MM}"
                 }
                             }
    if [type] == "system-log-securet" {
    elasticsearch {
        hosts => ["192.168.2.39:9200"]
        index => "system-log-secure-%{+YYYY-MM}"
                          } }
	
	if [type] == "system-log-nginx" {
    elasticsearch {
        hosts => ["192.168.2.39:9200"]
        index => "system-log-nginx-%{+YYYY-MM}"
                          } }
    }


my  logtrail.json
    {
   "index_patterns":[
      {
         "es":{
            "default_index":"system-log-nginx*",
            "allow_url_parameter":false
         },
         "tail_interval_in_seconds":10,
         "es_index_time_offset_in_seconds":0,
         "display_timezone":"local",
         "display_timestamp_format":"MMM DD HH:mm:ss",
         "max_buckets":500,
         "nested_objects":false,
         "default_time_range_in_days":0,
         "max_hosts":100,
         "max_events_to_keep_in_viewer":5000,
         "fields":{
            "mapping":{
               "timestamp":"@timestamp",
               "display_timestamp":"@timestamp",
               "hostname":"hostname",
               "program":"program",
               "message":"syslog_message"
            },
            "message_format":"{{{syslog_message}}}"
         }
      },
	  	
      {
         "es":{
            "default_index":"system-log-messages*",
            "allow_url_parameter":false
         },
         "tail_interval_in_seconds":10,
         "es_index_time_offset_in_seconds":0,
         "display_timezone":"local",
         "display_timestamp_format":"MMM DD HH:mm:ss",
         "max_buckets":500,
         "nested_objects":false,
         "default_time_range_in_days":0,
         "max_hosts":100,
         "max_events_to_keep_in_viewer":5000,
         "fields":{
            "mapping":{
               "timestamp":"@timestamp",
               "display_timestamp":"@timestamp",
               "hostname":"hostname",
               "program":"program",
               "message":"syslog_message"
            },
            "message_format":"{{{syslog_message}}}"
         }
      },
      {
         "es":{
            "default_index":"system-log-secure*",
            "allow_url_parameter":false
         },
         "tail_interval_in_seconds":10,
         "es_index_time_offset_in_seconds":0,
         "display_timezone":"local",
         "display_timestamp_format":"MMM DD HH:mm:ss",
         "max_buckets":500,
         "nested_objects":false,
         "default_time_range_in_days":0,
         "max_hosts":100,
         "max_events_to_keep_in_viewer":5000,
         "fields":{
            "mapping":{
               "timestamp":"@timestamp",
               "display_timestamp":"@timestamp",
               "hostname":"hostname",
               "program":"program",
               "message":"syslog_message"
            },
            "message_format":"{{{syslog_message}}}"
         }
      }
   ]
}

**Comment by sivasamyk** [comment]
@firehalt you need to update the filter section in logstash configuration, to parse the log lines accordingly. And then specify the fields in logtrail.conf. Checkout https://www.elastic.co/guide/en/logstash/current/config-examples.html#_processing_syslog_messages for more info on processing syslog files.
