### ISSUE TITLE
Switching between systems does not work in 5.4.1

### ISSUE THREAD

**Issue by joiningnat** [sivasamyk/logtrail#132]
Hi sivasamyk, 
I am using https://github.com/sivasamyk/logtrail/releases/download/v0.1.15/logtrail-5.4.1-0.1.15.zip with elasticsearch "5.4.1.
I have systems list but when I select any system, it is not selected.
So I only can view All Systems mode.
No errors in kibana logs.
JBoss logs are provided to logstash.

This is a typical logtrail entry:
Jun 23 15:54:38 server_instance1 env1:  14:54:37,557 INFO  [org.jboss.as.connector.subsystems.datasources] (FRD service thread 1-13) JBAS010409: Unbound data source 

My logtrail.json:
{
  "index_patterns" : [
    {      
      "es": {
        "default_index": "jboss-*",
        "allow_url_parameter": false       
      },
      "tail_interval_in_seconds": 10,
      "es_index_time_offset_in_seconds": 0,
      "display_timezone": "local",
      "display_timestamp_format": "MMM DD HH:mm:ss",
      "max_buckets": 500,
      "nested_objects" : false,
      "default_time_range_in_days" : 0,
      "max_hosts": 100,
      "max_events_to_keep_in_viewer": 5000,
      "fields" : {
        "mapping" : {
            "timestamp" : "@timestamp",
            "display_timestamp" : "@timestamp",
            "hostname" : "server_instance",
            "program": "env",
            "message": "message"
        },
        "message_format": "{{{loglevel}}} {{{message}}}"
      }
    }  
  ]
}

Thanks in advance.

**Comment by sivasamyk** [comment]
Thanks for the issue. I have fixed the issue in latest release. For 5.4.1 dowlnoad : https://github.com/sivasamyk/logtrail/releases/download/v0.1.16/logtrail-5.4.1-0.1.16.zip

For 5.4.2. : https://github.com/sivasamyk/logtrail/releases/download/v0.1.16/logtrail-5.4.2-0.1.16.zip

**Comment by joiningnat** [comment]
Thanks a lot for the fix! 
Everything works fine.
