### ISSUE TITLE
Logtrail Elasticsearch and Kibana and fluentd for docker logs dificult to select container logs to display

### ISSUE THREAD

**Issue by titansmc** [sivasamyk/logtrail#135]
Hi,
I've configured ES along with kibana and logtrail gathering metrics with fluentd from a docker swarm cluster. Everything is working but when containers are restarting constantly I go to the Logtrail tab and click under "All Systems" button and seems that I can select from a list of all containers that have been running on the cluster, which makes it quite difficult to select older containers, I mean, from the graphical interface I can only select those that have been restarted, there is no way I can see them all.
[screenshot](http://imgur.com/a/W3aDb)

**Comment by dbsanfte** [comment]
I'll second this. We're using Gelf for our logging from docker but same difference -- lots of containers, and that selection bar fills up fast. Sort of breaks the app to be honest.

At the bare minimum a scroll bar would be nice.

**Comment by sivasamyk** [comment]
Thanks. To start with I will add a scrollbar. Currently the sort criteria is alphabetical.

**Comment by titansmc** [comment]
Hi,
Thanks a lot. I am pretty new to this, would you mind to explain me how can I pull those changes to test them in my environment?

Cheers.

**Comment by sivasamyk** [comment]
@titansmc I released a new Logtrail version https://github.com/sivasamyk/logtrail/releases/download/v0.1.17/logtrail-5.4.3-0.1.17.zip with the fix. This release is compatible with 5.4.3 Kibana release. You can either upgrade your Kibana installation and reinstall  latest logtrail release else follow these steps to install 0.1.17 release with older Kibana version
1. Uninstall logtrail from Kibana
2. Download 0.1.17 release
3. Unzip the file and open package.json
4. Update kibana.version to your Kibana version (5.4.1?)
5. Zip it back
6. Install latest zip file
7. Update logtrail.json if required
8. Restart Kibana.

Hope this helps!
