### ISSUE TITLE
logtrail returns search error on switching to filebeat index

### ISSUE THREAD

**Issue by monitoringit** [sivasamyk/logtrail#139]
I used 5.4.2-0.1.16 logtrail version and updated package.json to work with kibana 5.2.1. I also updated logtrail.json to add additional index filebeat-* other than logstash-* but i cant seem to make it work.

When kibana is restarted logstash view works fine in logtrail but as soon as i switch to filebeat-* from logstash i get "Error! Exception while executing search query :undefined".

I am using following mapping in logtrail.json:

[root@ip-xxxxxxxxxxx logtrail]# cat logtrail.json
{
  "index_patterns" : [
    {
      "es": {
        "default_index": "logstash-*",
        "allow_url_parameter": false
      },
      "tail_interval_in_seconds": 10,
      "es_index_time_offset_in_seconds": 0,
      "display_timezone": "local",
      "display_timestamp_format": "MMM DD HH:mm:ss",
      "max_buckets": 500,
      "nested_objects" : false,
      "default_time_range_in_days" : 0,
      "max_hosts": 100,
      "max_events_to_keep_in_viewer": 5000,
      "fields" : {
        "mapping" : {
            "timestamp" : "@timestamp",
            "display_timestamp" : "@timestamp",
            "hostname" : "host",
            "program": "program",
            "message": "message"
        },
        "message_format": "{{{logsource}}} | {{{facility}}} | {{{priority}}} | {{{facility_label}}} | {{{pid}}} | {{{message}}}"
      }
    },
    {
      "es": {
        "default_index": "filebeat-*",
        "allow_url_parameter": false
      },
      "tail_interval_in_seconds": 10,
      "es_index_time_offset_in_seconds": 0,
      "display_timezone": "local",
      "display_timestamp_format": "MMM DD HH:mm:ss",
      "max_buckets": 500,
      "nested_objects" : false,
      "default_time_range_in_days" : 0,
      "max_hosts": 100,
      "max_events_to_keep_in_viewer": 5000,
      "fields" : {
        "mapping" : {
            "timestamp": "@timestamp",
            "display_timestamp": "@timestamp",
            "hostname": "host",
            "program": "source",
            "message": "message"
        },
        "message_format": "{{{host}}} | {{{source}} | {{{message}}}"
      }
    }
  ]
}

A typical message in filebeat index looks like this:
{
  "_index": "filebeat-2017.06.29",
  "_type": "nginx_access_log",
  "_id": "AVzyaTvgJwDKYpqnl0pl",
  "_score": null,
  "_source": {
    "request": "GET / HTTP/1.1",
    "remote_addr": "10.11.12.13",
    "offset": 174605591,
    "upstream_header_time": "-",
    "body_bytes_sent": 162,
    "input_type": "log",
    "source": "/appdata/nginx/logs/access.log",
    "request_method": "GET",
    "type": "nginx_access_log",
    "http_user_agent": "ELB-HealthChecker/2.0",
    "tags": [
      "xyz",
      "ARTF",
      "Artifactory-cluster1",
      "beats_input_raw_event"
    ],
    "remote_user": "-",
    "request_time": 0,
    "@timestamp": "2017-06-29T05:53:20.459Z",
    "upstream_connect_time": "-",
    "beat": {
      "hostname": "ip-11-11-11-11",
      "name": "xyz",
      "version": "5.1.1"
    },
    "http_x_forwarded_for": "-",
    "@version": "1",
    "host": "ip-11-11-11-11",
    "http_referrer": "-",
    "upstream_response_time": "-",
    "time": "2017-06-29T05:53:19+00:00",
    "fields": {
      "stack": "Artifactory-cluster1",
      "instance": "i-xxxxxxxxxxxxxxx",
      "appid": "ARTF",
      "vpc": "xxx",
      "az": "us-east-1b",
      "instance_type": "m4.xlarge"
    },
    "status": "302"
  },
  "fields": {
    "@timestamp": [
      1498715600459
    ],
    "time": [
      1498715599000
    ]
  },
  "sort": [
    1498715600459
  ]
}

**Comment by sivasamyk** [comment]
In the` filebeat-* `mapping, you have mapped `message `to message field in ES document. I do not see the message field in the sample doc for filebeat.

**Comment by monitoringit** [comment]
In filebeat i have docs of different types. You are right about your observation about previous doc i posted.
Here is another doc  that should have been picked up....

{
  "_index": "filebeat-2017.06.29",
  "_type": "awslogs",
  "_id": "AVz0t845AckQEOzylZwC",
  "_score": null,
  "_source": {
    "@timestamp": "2017-06-29T16:38:23.693Z",
    "offset": 2735967,
    "@version": "1",
    "input_type": "log",
    "beat": {
      "hostname": "ip-xx-xx-xx-xx",
      "name": "xyz",
      "version": "5.1.1"
    },
    "host": "ip-xx-xx-xx-xx",
    "source": "/var/log/cfn-wire.log",
    "message": "2017-06-29 16:38:16,189 [DEBUG] Response: 200 https://cloudformation.us-east-1.amazonaws.com/?Action=DescribeStackResource&StackName=hv-sec-VaultNode1-1LD2QRAQY4WYD&Version=2010-05-15&ContentType=JSON&LogicalResourceId=Ec2AppLC [headers: {'x-amzn-requestid': '983ru9ejref98ee8jnf9ejf89df89', 'date': 'Thu, 29 Jun 2017 16:38:15 GMT', 'content-length': '5643', 'content-type': 'application/json'}]",
    "fields": {
      "stack": "hv-sec",
      "instance": "i-866876",
      "appid": "VAULT",
      "dns": "vault1",
      "vpc": "xxxxx",
      "az": "us-east-1a",
      "instance_type": "m4.large"
    },
    "type": "awslogs",
    "tags": [
      "xxxxx",
      "VAULT",
      "hv-sec",
      "beats_input_codec_plain_applied"
    ]
  },
  "fields": {
    "@timestamp": [
      1498754303693
    ]
  },
  "highlight": {
    "input_type": [
      "@kibana-highlighted-field@log@/kibana-highlighted-field@"
    ],
    "fields.vpc": [
      "@kibana-highlighted-field@sec2tst@/kibana-highlighted-field@"
    ],
    "fields.stack": [
      "@kibana-highlighted-field@hv-sec@/kibana-highlighted-field@"
    ],
    "source": [
      "@kibana-highlighted-field@/var/log/cfn-wire.log@/kibana-highlighted-field@"
    ],
    "type": [
      "@kibana-highlighted-field@awslogs@/kibana-highlighted-field@"
    ],
    "message": [
      "@kibana-highlighted-field@2017@/kibana-highlighted-field@-@kibana-highlighted-field@06@/kibana-highlighted-field@-@kibana-highlighted-field@29@/kibana-highlighted-field@ @kibana-highlighted-field@16@/kibana-highlighted-field@:@kibana-highlighted-field@38@/kibana-highlighted-field@:@kibana-highlighted-field@16,189@/kibana-highlighted-field@ [@kibana-highlighted-field@DEBUG@/kibana-highlighted-field@] @kibana-highlighted-field@Response@/kibana-highlighted-field@: @kibana-highlighted-field@200@/kibana-highlighted-field@ @kibana-highlighted-field@https@/kibana-highlighted-field@://@kibana-highlighted-field@cloudformation.us@/kibana-highlighted-field@-@kibana-highlighted-field@east@/kibana-highlighted-field@-@kibana-highlighted-field@1@/kibana-highlighted-field@.@kibana-highlighted-field@amazonaws.com@/kibana-highlighted-field@/?@kibana-highlighted-field@Action@/kibana-highlighted-field@=@kibana-highlighted-field@DescribeStackResource@/kibana-highlighted-field@&@kibana-highlighted-field@StackName@/kibana-highlighted-field@=@kibana-highlighted-field@hv@/kibana-highlighted-field@-@kibana-highlighted-field@sec@/kibana-highlighted-field@-@kibana-highlighted-field@VaultNode1@/kibana-highlighted-field@-@kibana-highlighted-field@1LD2QRAQY4WYD@/kibana-highlighted-field@&@kibana-highlighted-field@Version@/kibana-highlighted-field@=@kibana-highlighted-field@2010@/kibana-highlighted-field@-@kibana-highlighted-field@05@/kibana-highlighted-field@-@kibana-highlighted-field@15@/kibana-highlighted-field@&@kibana-highlighted-field@ContentType@/kibana-highlighted-field@=@kibana-highlighted-field@JSON@/kibana-highlighted-field@&@kibana-highlighted-field@LogicalResourceId@/kibana-highlighted-field@=@kibana-highlighted-field@Ec2AppLC@/kibana-highlighted-field@ [@kibana-highlighted-field@headers@/kibana-highlighted-field@: {'@kibana-highlighted-field@x@/kibana-highlighted-field@-@kibana-highlighted-field@amzn@/kibana-highlighted-field@-@kibana-highlighted-field@requestid@/kibana-highlighted-field@': '@kibana-highlighted-field@59c9288b@/kibana-highlighted-field@-@kibana-highlighted-field@5ce9@/kibana-highlighted-field@-@kibana-highlighted-field@11e7@/kibana-highlighted-field@-@kibana-highlighted-field@afbf@/kibana-highlighted-field@-@kibana-highlighted-field@dd06e3e2fa95@/kibana-highlighted-field@', '@kibana-highlighted-field@date@/kibana-highlighted-field@': '@kibana-highlighted-field@Thu@/kibana-highlighted-field@, @kibana-highlighted-field@29@/kibana-highlighted-field@ @kibana-highlighted-field@Jun@/kibana-highlighted-field@ @kibana-highlighted-field@2017@/kibana-highlighted-field@ @kibana-highlighted-field@16@/kibana-highlighted-field@:@kibana-highlighted-field@38@/kibana-highlighted-field@:@kibana-highlighted-field@15@/kibana-highlighted-field@ @kibana-highlighted-field@GMT@/kibana-highlighted-field@', '@kibana-highlighted-field@content@/kibana-highlighted-field@-@kibana-highlighted-field@length@/kibana-highlighted-field@': '@kibana-highlighted-field@5643@/kibana-highlighted-field@', '@kibana-highlighted-field@content@/kibana-highlighted-field@-@kibana-highlighted-field@type@/kibana-highlighted-field@': '@kibana-highlighted-field@application@/kibana-highlighted-field@/@kibana-highlighted-field@json@/kibana-highlighted-field@'}]"
    ],
    "tags": [
      "@kibana-highlighted-field@sec2tst@/kibana-highlighted-field@",
      "@kibana-highlighted-field@VAULT@/kibana-highlighted-field@",
      "@kibana-highlighted-field@hv-sec@/kibana-highlighted-field@",
      "@kibana-highlighted-field@beats_input_codec_plain_applied@/kibana-highlighted-field@"
    ],
    "fields.dns": [
      "@kibana-highlighted-field@vault1@/kibana-highlighted-field@"
    ],
    "beat.name": [
      "@kibana-highlighted-field@vault1_i-030e3d69aab06089a@/kibana-highlighted-field@"
    ],
    "beat.hostname": [
      "@kibana-highlighted-field@ip-10-94-132-77@/kibana-highlighted-field@"
    ],
    "fields.instance": [
      "@kibana-highlighted-field@i-030e3d69aab06089a@/kibana-highlighted-field@"
    ],
    "@version": [
      "@kibana-highlighted-field@1@/kibana-highlighted-field@"
    ],
    "host": [
      "@kibana-highlighted-field@ip-10-94-132-77@/kibana-highlighted-field@"
    ],
    "fields.az": [
      "@kibana-highlighted-field@us-east-1a@/kibana-highlighted-field@"
    ],
    "fields.instance_type": [
      "@kibana-highlighted-field@m4.large@/kibana-highlighted-field@"
    ],
    "beat.version": [
      "@kibana-highlighted-field@5.1.1@/kibana-highlighted-field@"
    ],
    "fields.appid": [
      "@kibana-highlighted-field@VAULT@/kibana-highlighted-field@"
    ]
  },
  "sort": [
    1498754303693
  ]
}

**Comment by sivasamyk** [comment]
Can you check if there are any errors in Kibana server logs? I will also try to reproduce this locally.

**Comment by sivasamyk** [comment]
@monitoringit I tried indexing filebeat logs in ES and viewing the same in logtrail. It works fine. Can you check if there are any errors in Kibana server log or logtrail Javascript console?

**Comment by monitoringit** [comment]
Can you share your filebeat index logtrail mapping? I will check the errors in server logs. 
As I mentioned before I see the errors on logtrail Kibana  view
 "Error! Exception while executing search query :undefined"

**Comment by sivasamyk** [comment]
I used latest filebeat with default configuration. Can you check the javascript console in your browser for any logs? In case of error Kibana logs details in debug console of browser. You can open the same in Chrome from More Tools -> Developer Tools menu. Also check for any error logs in Kibana server logs.

**Comment by monitoringit** [comment]
It is working. I was using wrong message format and was missing one closing braces.

**Comment by sivasamyk** [comment]
Happy logging!
