### ISSUE TITLE
Improve message display

### ISSUE THREAD

**Issue by vcariven** [sivasamyk/logtrail#14]
Multiline message (e.g. stacktrace) are not well displayed. Pick-up the css from kibana itself on the css .message class:
Turn (in public/css/main.css):
```
.message {
    color: #B0B0B0;
}
```
into:
```
.message {
    color: #B0B0B0;
    word-break: break-all;
    word-wrap: break-word;
    white-space: pre-wrap;
}
```

Regards

**Comment by sivasamyk** [comment]
Thanks fixed. Please install 1.5.0 

 - Kibana 4.x : `./bin/kibana plugin -i logtrail -u https://github.com/sivasamyk/logtrail/releases/download/0.1.5/logtrail-4.x-0.1.5.tar.gz`
 - Kibana 5.x : `./bin/kibana-plugin install https://github.com/sivasamyk/logtrail/releases/download/0.1.5/logtrail-5.x-0.1.5.zip`
