### ISSUE TITLE
Render leading whitespace in log messages

### ISSUE THREAD

**Issue by dbsanfte** [sivasamyk/logtrail#140]
We have a lot of log messages that are indented as part of "prettifying" JSONs. These show up fine in Kibana, so the leading whitespace is there, but Logtrail strips it out when it renders it in the browser. This makes our logs a lot less pretty (the JSONs are flat and ugly).

Can we have some sort of option for Logtrail to render the leading whitespace in our log messages?

Cheers :)

**Comment by sivasamyk** [comment]
Can you please share a screenshot of the logtrail and a sample ES document ? Make sure you hide confidential info.

**Comment by dbsanfte** [comment]
Original logs as viewed in Kibana (out of order):
http://imgur.com/a/OiWOS

Renders like (in order but all indentation scrubbed):
http://imgur.com/a/UTfUe

**Comment by sivasamyk** [comment]
@dbsanfte I see that each line in the json object is interpreted as an event. I would recommend you to use logstash to format the event and map the whole json doc to a field in event or extract multiple fields from json.

https://www.elastic.co/guide/en/logstash/current/plugins-filters-json.html

**Comment by dbsanfte** [comment]
I had a dig into your suggested solution, but no dice. The main problem is that multiline-gelf isn't supported in Logstash. The multiline codec doesn't work, and the multiline filter was deprecated in logtash versions 5.x.

https://github.com/logstash-plugins/logstash-input-gelf/issues/37

In the meantime is there any way to get Logtrail to honour the leading whitespace?

**Comment by dbsanfte** [comment]
Actually nevermind. I was able to edit the css to 'white-space: pre', but some messages are out of order and the JSONs aren't rendered right.

I guess I'll need to wait for multiline gelf support in Logstash. Thanks for the response. :)

**Comment by sivasamyk** [comment]
Great. I was about test similar changes before proposing!

**Comment by sivasamyk** [comment]
Added white-space: pre-word in CSS for message
