### ISSUE TITLE
Search for hostname, is that possible?

### ISSUE THREAD

**Issue by titansmc** [sivasamyk/logtrail#141]
Hi,
We are using this tool in order to monitor all of our docker logs, and since the most important thing is to be able to grep for a particular container(hostname), I would like to set this field as searchable instead of the log message, 

Is there any way of doing this?

Thanks.

**Comment by sivasamyk** [comment]
Yes. You can search by using `<hostname-field>:<query-string>` in the search field. e.g. `hostname:docker-1`. You can also search based on any field in your document. The query string will also accept wildcard characters.  For more info refer : https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html#query-string-syntax
