### ISSUE TITLE
Incorrect Kibana version in plugin [logtrail]. Expected [5.4.0]; found [5.4.3]

### ISSUE THREAD

**Issue by patrickwolf** [sivasamyk/logtrail#142]
Got this error message when installing into Kibana 5.4.3
`Plugin installation was unsuccessful due to error "Incorrect Kibana version in plugin [logtrail]. Expected [5.4.0]; found [5.4.3]"`

> kibana-plugin.bat install https://github.com/sivasamyk/logtrail/releases/download/v0.1.17/logtrail-5.4.3-0.1.17.zip
> Attempting to transfer from https://github.com/sivasamyk/logtrail/releases/download/v0.1.17/logtrail-.4.3-0.1.17.zip
> Transferring 1353506 bytes....................
> Transfer complete
> Retrieving metadata from plugin archive
> Extracting plugin archive
> Extraction complete
> `Plugin installation was unsuccessful due to error "Incorrect Kibana version in plugin [logtrail]. Expected [5.4.0]; found [5.4.3]"`

Thanks!

**Comment by sivasamyk** [comment]
@patrickwolf Kibana requires exact match of plugin and kibana version. You are trying to install 5.4.3 plugin in 5.4.0 Kibana. You have 2 options

1) Download 5.4.0 logtrail plugin and install : https://github.com/sivasamyk/logtrail/releases/download/0.1.14/logtrail-5.4.0-0.1.14.zip
2) Modify kibana.version in 5.4.3 logtrail to 5.4.0 and install . Following are the steps 
- Unzip logtrail 5.4.3 file
- Update the kibana.version to 5.4.0 in package.json file
- zip it back.
- Install it using following command
kibana-plugin.bat install file://<path-to-local-logtrail.zip file>

**Comment by patrickwolf** [comment]
Thank you so much @sivasamyk. I upgraded Kibana and it worked out of the box!
Sorry about the silly questions as it seems pretty obvious now :)

**Comment by sivasamyk** [comment]
Great! Happy logging!
