### ISSUE TITLE
kibana 5.5 issues, when trying to upgrade from logtrail 5.4

### ISSUE THREAD

**Issue by lantern77** [sivasamyk/logtrail#143]
I know Kibana 5.5 was just released yesterday, however I just wanted to point out some issues that appeared when we tried to convert logtrail 5.4 for kibana 5.5 use.

So initially starting we ran into the error of kibana plugins requiring the exact version of kibana which 
was fixed by following the instructions here https://github.com/sivasamyk/logtrail/issues/142

After that however we ran into error with Kibana's chrome module:
```
Uncaught TypeError: _chrome2.default.setNavBackground is not a function (http://172.16.110.31:5601/bundles/logtrail.bundle.js?v=15382:1)
    at window.onerror (http://172.16.110.31:5601/bundles/commons.bundle.js?v=15382:76:8876)
```
Unfortunately after looking at Kibana's theme.js they removed the setNavBackground method
https://github.com/elastic/kibana/blob/master/src/ui/public/chrome/api/theme.js.

So for now we commented chrome.setNavBackground out from app.js in an attempt to get logtrail starting again. However after we now get the error,
```
Cannot read property 'get' of undefined (http://172.16.110.31:5601/bundles/logtrail.bundle.js?v=15382:1)
    at window.onerror (http://172.16.110.31:5601/bundles/commons.bundle.js?v=15382:76:8876)
``` 
Which looking at the reformatted code is the line,
```
 var app = uiModules.get('app/logtrail', []);
```
Within app.js. This is very odd, and as kibana itself can still use uiModules.
By chance do you know this is simply an issue on our end, or could it be Kibana's pathing.

Note* I got this message by modifying the source code of logTrail in Kibana "plugins" and then recompiled the bundles by deleting the bundles folder and restarting kibana.
https://discuss.elastic.co/t/how-does-the-bundling-mechanism-works/48817/6

Thanks for taking the time to read this,
I know this is asking alot since Kibana 5.5 just came out yesterday, but I just wanted to let you know
and was wondering if you were running into the same issues

**Comment by sivasamyk** [comment]
@lantern77 Thanks for the updates. I have not yet tested logtrail with Kibana 5.5 version. Will test over  the weekend and update.

**Comment by sivasamyk** [comment]
@lantern77 I have fixed this issue and release new update at https://github.com/sivasamyk/logtrail/releases/download/v0.1.17/logtrail-5.5.0-0.1.17.zip
Let me know if you face any issues.

**Comment by lantern77** [comment]
I will test it out this monday thanks for the update

**Comment by lantern77** [comment]
Sorry for the late response, had work-space issues on my end. The fixes worked. Thanks much appreciated :)

**Comment by lantern77** [comment]
One thing I'd like to ask though, how did changing the  order of the imports fix this issue? Did Kibana change some of its dependencies?

**Comment by sivasamyk** [comment]
Its not order of imports. The addition of {} around the imported module name as done in this PR https://github.com/elastic/kibana/pull/11323/commits/f9e23e071c21f29d9ecaed55fc66ac6a2c32d327

**Comment by lantern77** [comment]
Did they change the exports then? Sorry for bothering so much but where are the ui/notify files and ui/modules in kibana I can't seem to find them.

**Comment by sivasamyk** [comment]
Yes. They removed default exports. Checkout this PR https://github.com/elastic/kibana/commit/f9e23e071c21f29d9ecaed55fc66ac6a2c32d327

**Comment by lantern77** [comment]
Thanks so much for the help, much appreciated.
