### ISSUE TITLE
filebeat hostnames not visible in All Systems List

### ISSUE THREAD

**Issue by monitoringit** [sivasamyk/logtrail#145]
I am using logtrail (0.1.16) with 5.2.1 kibana.
I am using default mapping beat.hostname to populate hostname. But i am seeing two issues:
A) don't see these hosts in menu options under All Systems. 

    {
      "es": {
        "default_index": "filebeat-*",
        "allow_url_parameter": false
      },
      "tail_interval_in_seconds": 10,
      "es_index_time_offset_in_seconds": 0,
      "display_timezone": "local",
      "display_timestamp_format": "MMM DD HH:mm:ss",
      "max_buckets": 500,
      "nested_objects" : true,
      "default_time_range_in_days" : 0,
      "max_hosts": 100,
      "max_events_to_keep_in_viewer": 5000,
      "fields" : {
        "mapping" : {
            "timestamp": "@timestamp",
            "display_timestamp": "@timestamp",
            "hostname": "beat.hostname",
            "program": "source",
            "message": "message"
        },
        "message_format": "{{{beat.hostname}}} | {{{source}}} | {{{message}}}"
      }
    }

B) 
Logtrail message=> Jul 14 02:10:35 **ip-10-94-132-77** /var/log/syslog:  _ip-10-94-132-77_ | /var/log/syslog | Jul 14 06:10:32 ip-10-94-132-77 dhclient[2287]: XMT: Solicit on eth0, interval 131080ms.

When clicking on hostname (bold) no events are shown in logtrail window < url formed is https://kibana.xxxxxx.com/app/logtrail#/?q=beat.hostname:%20%22ip-10-94-132-77%22&h=ip-10-94-132-77&t=Now&i=filebeat-*&_g=() >. 

But clicking on hostname (italics) that is part of message format works as i can see search window getting populated with beat.hostname: "ip-10-94-132-77"

**Comment by sivasamyk** [comment]
Thanks for the issue. Need to add nested tag to mapping and update the queries in logtrail to handle nested document. Will fix in next release.

**Comment by monitoringit** [comment]
Thanks! Will wait for the fix.

**Comment by christidis** [comment]
Same issue with logspout instead of Filebeat trying to map `docker.name` to `program`.
fields with logspout are like `docker.name` `docker.hostname` etc.

**Comment by jeraldsm** [comment]
I have exactly the same issue and I'm using ELK 5.5.0 with logtrail 0.1.17.
This is a very useful plugin @sivasamyk . Waiting for the fix.

**Comment by sivasamyk** [comment]
@monitoringit @jeraldsm I haved fixed issue in the latest release. It is supported in Kibana  5.5.0 version.
https://github.com/sivasamyk/logtrail/releases/download/v0.1.18/logtrail-5.5.0-0.1.18.zip

Upgrade to latest release and let me know if you face any issues. Note that the nested_objects field is  removed from logtrail.json

**Comment by jeraldsm** [comment]
@sivasamyk Works like charm. Thanks a lot of fixing this

**Comment by christidis** [comment]
Thanks, any chance for this to go on the `5.2` Kibana version of the plugin?

**Comment by sivasamyk** [comment]
@christidis You need the support in 5.2.2 or 5.2.0 version?

**Comment by monitoringit** [comment]
sivasamyk i am using kibana 5.2.1 and when i try latest release ..i keep getting following error on browser:
Uncaught TypeError: Cannot read property 'get' of undefined (https://kibana.xyz.com/bundles/logtrail.bundle.js?v=14707:1)
Version: 5.2.1
Build: 14707
Error: Uncaught TypeError: Cannot read property 'get' of undefined (https://kibana.xyz.com/bundles/logtrail.bundle.js?v=14707:1)
    at window.onerror (https://kibana.xyz.com/bundles/commons.bundle.js?v=14707:69:13503)
I have removed nested_objects from logtrail.json file as well.

**Comment by sivasamyk** [comment]
@monitoringit There are some API changes in Kibana 5.5 that makes it not backward compatible. I assume you took the latest zip and changed the Kibana version in package.json. I will release a new update for 5.2.1 with the fix for this issue.

**Comment by christidis** [comment]
@sivasamyk I am using a containerized ELK which is packaged with the `5.2.0` version of Kibana.

**Comment by monitoringit** [comment]
Yes thats exactly what i did. I changed ver in packaged.json to 5.2.1. I
then installed it but then got the error.

**Comment by sivasamyk** [comment]
I  backported the fix to 5.4.3 Kibana. This should be compatible with 5.2.x version. Please update kibana.version field in package.json to respective 5.2.x version.

https://github.com/sivasamyk/logtrail/releases/download/v0.1.17/logtrail-5.4.3-0.1.17-145.zip

Let me know if you face any issues.

**Comment by christidis** [comment]
Tried this with `5.2.0` and it worked. Thanks for the fix @sivasamyk.

**Comment by monitoringit** [comment]
The new link works great on 5.2.1 kibana after updating version in package.json. Thanks!
