### ISSUE TITLE
How to launch console post configuration?

### ISSUE THREAD

**Issue by manoj-ms** [sivasamyk/logtrail#146]
How to launch console post configuration?

**Comment by sivasamyk** [comment]
After installation and updating the logtrail.json, restart the Kibana instance. You will see that logtrail icon ('L') in the left hand side pane. Select this should how the events in the configured index.

**Comment by manoj-ms** [comment]
Thanks for the information. Just a quick info. I am using Kibana 5.4.1 and Logstash compatible with it. I do not see ('L') icon in the Kibana Console.

Screenshot:
![image](https://user-images.githubusercontent.com/8655362/28258853-0bfffaf0-6af1-11e7-9ef4-9dcd14091014.png)

**Comment by sivasamyk** [comment]
I assume you installed https://github.com/sivasamyk/logtrail/releases/download/v0.1.16/logtrail-5.4.1-0.1.16.zip version. Can you check the kibana logs while starting. It should print info about plugins loaded. Also make sure Kibana did not report any error during installation of logtrail plugin.

**Comment by manoj-ms** [comment]
Yes. it was the same version installed. I found systemctl, though it said Kibana service as stopped, It was not. Had to forcefully kill it and restart it fresh. it worked.

Thanks for the support.

**Comment by sivasamyk** [comment]
Great. Happy logging!
