### ISSUE TITLE
Can't install on kibana 5.0.1

### ISSUE THREAD

**Issue by marchenkov** [sivasamyk/logtrail#15]
# ./bin/kibana-plugin install https://github.com/sivasamyk/logtrail/releases/download/0.1.4/logtrail-5.x-0.1.4.zip
Attempting to transfer from https://github.com/sivasamyk/logtrail/releases/download/0.1.4/logtrail-5.x-0.1.4.zip
Transferring 63065 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Extracting plugin archive
Extraction complete
Plugin installation was unsuccessful due to error "Incorrect Kibana version in plugin [logtrail]. Expected [5.0.1]; found [5.0.0]"

**Comment by sivasamyk** [comment]
Fixed. Please use 1.5.0
 - Kibana 5.x : `./bin/kibana-plugin install https://github.com/sivasamyk/logtrail/releases/download/0.1.5/logtrail-5.x-0.1.5.zip`
