### ISSUE TITLE
handlebar not replacing "log" field

### ISSUE THREAD

**Issue by lpic10** [sivasamyk/logtrail#152]
Similar to https://github.com/sivasamyk/logtrail/issues/120#issuecomment-307639150

For example, this event:

``` 
{ log: '2017-07-25T13:39:02Z my nice log message here!!! \n',
  stream: 'stderr',
  docker: { container_id: '1dc3bbf03bb9ea68b95a940329ea0f685a4ede8dea6f8217907cac3a9010a816' },
  kubernetes:
   { container_name: 'containerA',
     namespace_name: 'namespace-test',
     pod_name: 'containerA-wp9on',
     pod_id: '32aaa4dd-6249-11e7-972f-005056835c46',
     labels: { name: 'containerA' },
     host: '1.1.1.1',
     master_url: 'https://127.0.0.1:443' },
  '@timestamp': '2017-07-25T13:39:02.238397257Z' }
```

and using:

```    
"fields" : {
        "mapping" : {
          "timestamp" : "@timestamp",
          "display_timestamp" : "@timestamp",
          "hostname" : "kubernetes.namespace_name",
          "program": "kubernetes.container_name",
          "message": "log"
        },
        "message_format": "({{{stream}}}) {{{kubernetes.namespace_name}}} {{{log}}}"
```

I get nothing replaced. 

I can reproduce this issue on http://tryhandlebarsjs.com pasting this generated template and the event above:

```
(<a class="ng-binding" ng-click="onClick('stream','{{{stream}}}')">{{{stream}}}</a>) <a class="ng-binding" ng-click="onClick('kubernetes.namespace_name','{{{kubernetes.namespace_name}}}')">{{{kubernetes.namespace_name}}}</a> | {{{log}}}
```

It works by replacing the field name to anything else than "log", I guess it conflicts with the builtin helper for log: http://handlebarsjs.com/builtin_helpers.html

I cannot change my mapping from that unfortunately.

**Comment by lpic10** [comment]
Ok, I've found a workaround by changing `server.js` from
```
var template = handlebar.compile(message_template);
```

to:

```
var template = handlebar.compile(message_template, { knownHelpers :{log: false}, knownHelpersOnly: true});
```

**Comment by sivasamyk** [comment]
Thanks for the issue and workaround :) Will check if there is option disable helpers completely, since logtrail may not use any helpers in its templates

**Comment by Globegitter** [comment]
@sivasamyk running into the same issue. Do you think this is something you want to look into soon? Also happy to make a PR out of the above mentioned workaround if it would get accepted.

**Comment by sivasamyk** [comment]
@Globegitter Thanks. Will provide an option to configure knowHelpers from logtrail.json in next release.

**Comment by Globegitter** [comment]
@sivasamyk there has been a new release now, does that provide such an option by any chance?

**Comment by sivasamyk** [comment]
@Globegitter This release was mostly concerned about color coding feature and fixing a bug in tail.  Will include the fix for this bug in next release.

**Comment by Globegitter** [comment]
@sivasamyk Thanks, that is much appreciated :)

**Comment by sivasamyk** [comment]
@Globegitter  fixed in https://github.com/sivasamyk/logtrail/releases/download/v0.1.21/logtrail-5.6.2-0.1.21.zip
