### ISSUE TITLE
Log trail "Go Live" behavior

### ISSUE THREAD

**Issue by monitoringit** [sivasamyk/logtrail#154]
I am new user of logtrail. I see that after clicking Go Live option (button switches label to PAUSE now) it waits for new data to come in based on search criteria i have selected and then once latest logs are shown it switches back from PAUSE to Go Live and stops streaming until i push Go Live again. 

Is this the expected behavior or is it that once i press Go Live it should continue to stream logs as they arrive until i press PAUSE?

If developer is tailing a log file from a system he would have to keep pressing Go Live again and again after logtrail displays new logs each time. May be thats what it is but i think user experience canbe imporved by continuing to show log stream until user presses PAUSE.

**Comment by sivasamyk** [comment]
No. Once use select go live it should remain in live mode until user selects pause or scrolls up the logs. Can you let me know the browser you are using and send me the screenshot of logtrail in live mode ( i am interested in the location scrollbar in live mode. It should always be in the bottom)?

**Comment by monitoringit** [comment]
I saw this behavior in chrome. I am going to check in IE.

**Comment by monitoringit** [comment]
Just checked IE it is working as expected. Once go live is clicked it continues to stream until PAUSE is clicked. Chrome doesnt show this behavior. Can you test it on your side? I have standard chrome install.

**Comment by sivasamyk** [comment]
I am use Chrome 59 under Ubuntu Linux. It works for me. Can you let me know your Chrome version?

**Comment by monitoringit** [comment]
I am using chrome Version 59.0.3071.115 on win 10 machine.

**Comment by monitoringit** [comment]
is there any setting in browser that i need to set for making this work as desired

**Comment by monitoringit** [comment]
I have another desktop with chrome 60. It is working fine there. So has to be my chrome settings.

**Comment by sivasamyk** [comment]
Logtrail use window height API to decide the status of live tail. Do you have any extra plugins installed in your Chrome?

**Comment by monitoringit** [comment]
i have same set of chrome extensions on chrome 59 and 60 versions. So  the undesired behavior on chrome 59 looks like is attributed to something else. I dont know what chrome setting can interfere with window height API.

**Comment by sivasamyk** [comment]
@monitoringit I did find some issue with scrollbar position in latest chrome browser and I have fixed the same. Check out latest logtrail release and let me know if this issue is solved.

https://github.com/sivasamyk/logtrail/releases/download/v0.1.19/logtrail-5.5.1-0.1.19.zip
