### ISSUE TITLE
LogTrail not continuously tailing 

### ISSUE THREAD

**Issue by MattBorowiec** [sivasamyk/logtrail#156]
Hi,

I've recently installed v0.1.18 on Kibana 5.5.1 and its working well, except that "Go Live" keeps changing to "Pause" automatically, after anywhere from 1-20 seconds after running.

Is there something in my configuration that could be causing this:
```
{"index_patterns" :[
  { "es": {
    "default_index": "logstash-*",
    "allow_url_parameter": false
  },
  "tail_interval_in_seconds": 10,
  "es_index_time_offset_in_seconds": 0,
  "max_buckets": 300,
  "nested_objects" : false,
  "default_time_range_in_days" : 15,
  "max_hosts": 100,
  "max_events_to_keep_in_viewer": 5000,
  "fields" : {
    "mapping" : {
        "timestamp" : "@timestamp",
        "display_timestamp" : "@timestamp",
        "hostname" : "host",
        "program": "program",
        "message": "message"
    }
  }
}
]}
```

Or potentially a bug?

Thanks.

**Comment by sivasamyk** [comment]
@MattBorowiec Thanks for using logtrail!. When you open the logtrail for the first time it will open in live mode ( the button will display Pause). Once you move the vertical scroll bar from the bottom right , the button will display 'Go Live' (it is no more in live mode). You mean when you move the scroll bar and the button goes to 'Go Live',  again it is changing to 'Pause'? Can you let me the browser and OS you are using? Please try with different browser. Also a small GIF of the issue will be helpful.

**Comment by MattBorowiec** [comment]
@sivasamyk When I first click the Logtrail icon it displays "Pause" while it is loading log entries, but as soon as they load the button switches to "Go Live"

Then, I click "Go Live", the button changes to "Pause" and the logs start to tail. Then after a seemingly random amount of time (1 second - 30 seconds it switches back to "Go Live", even if I do not touch the scroll bar.

This is on Chrome, Version 59.0.3071.115 (Official Build) (64-bit)

Doesn't appear to have the issue in Safari or Firefox. Both seem to tail indefinitely.

**Comment by sivasamyk** [comment]
Looks like this behavior is seen in Chrome 59. Chrome 60 does not have this issue.  Refer https://github.com/sivasamyk/logtrail/issues/154

**Comment by MattBorowiec** [comment]
Ok, thanks for the info! And for the super quick response! Really appreciate it.

**Comment by sivasamyk** [comment]
@MattBorowiec I did find some issue with scrollbar position in latest chrome browser and I have fixed the same. Check out latest logtrail release and let me know if this issue is solved.

https://github.com/sivasamyk/logtrail/releases/download/v0.1.19/logtrail-5.5.1-0.1.19.zip
