### ISSUE TITLE
Cannot read property 'index_patterns' of undefined

### ISSUE THREAD

**Issue by mvlach** [sivasamyk/logtrail#157]
commons.bundle.js?v=15405:38 TypeError: Cannot read property 'index_patterns' of undefined

Installed the latest 0.18 version.

File logtrail.json located in folder /usr/share/kibana/plugins/logtrail
![image](https://user-images.githubusercontent.com/6176546/29066182-bcb2a552-7c2e-11e7-88c1-4d62cb92ad87.png)

**Comment by sivasamyk** [comment]
Can you paste the contents of your logtrail.json and capture the response for '/logtrail/config' URI request in Network tab of Chrome debugger?

**Comment by mvlach** [comment]
The problem was on the reverse proxy as the /log.* is proxied to another system. I add the 
        location /logtrail {
                proxy_pass http://IP:5601;
        }

And this problem disappear.
