### ISSUE TITLE
Contributing and custom builds

### ISSUE THREAD

**Issue by Kikketer** [sivasamyk/logtrail#16]
I'm experimenting with this plugin inside an enterprise installation.  We need to have all plugins internally held and there are times when we need to adjust the plugins for our own uses.

What are the steps you go through to create the 5.0.1 version of the plugin?  I noticed that the `npm run build` step runs a grunt process and doesn't modify the package.json to have the appropriate Kibana.version.

The 5.0 branch has this package.json file seems to match what 5.0 expects.  Do you run `npm run build` in that branch?  Or do you use the @elastic/plugin-helpers to produce a working plugin zip file?

**Comment by sivasamyk** [comment]
@Kikketer Thanks for trying out the plugin.  

To create v5.0.1 version of plugin, I manually update the kibana.version property in package.json. Checkout the package.json @ https://github.com/sivasamyk/logtrail/blob/5.0/package.json . The zip file produced by npm run build will not work with Kibana 5.0. You need to modify the contents of zip file to make it work with Kibana 5.0.

I have added build script to 5.0 branch (https://github.com/sivasamyk/logtrail/blob/5.0/build.sh). Running this from logtrail directory will produce a zip file in build dir which will work with 5.x Kibana.

Hope this helps.

**Comment by Kikketer** [comment]
That script helped, thank you.
However with the latest version of plugin-helpers, it creates the `/kibana` folder for you.  So I simply edited the script to look like this:

```bash
#!/bin/bash

rm -rf build/*
npm run build
cd build
zip_name=`ls *.zip`
unzip logtrail*.zip
cp ../logtrail.json kibana/logtrail-*/
zip -r $zip_name kibana/
```

I could do a fork and pull if you wish.

**Comment by sivasamyk** [comment]
Thanks. Sure your pull request is welcome!

**Comment by Kikketer** [comment]
#17 has been created
