### ISSUE TITLE
Seeing <span class='highlight'> instead of highlighted elements

### ISSUE THREAD

**Issue by Globegitter** [sivasamyk/logtrail#161]
See screenshot:

![image](https://user-images.githubusercontent.com/2580254/29672955-09d256ae-88ee-11e7-9d5f-0b34b30b83f3.png)

I am running KIBANA_VERSION 5.5.1 and LOGTRAIL_VERSION 0.1.18 not sure if any other information is needed - let me know.

**Comment by sivasamyk** [comment]
Can you publish your logtrail.json? Make sure the message field specified in message_format is enclosed with `{{{ syslog_message }}}` . Three curly braces.

**Comment by sivasamyk** [comment]
@Globegitter Are you still seeing this issue?

**Comment by sivasamyk** [comment]
@Globegitter Are you still seeing this issue?

**Comment by Globegitter** [comment]
Yep, working now - thanks :)
