### ISSUE TITLE
Propose an alaraming feature like papertrail

### ISSUE THREAD

**Issue by danielpetisme** [sivasamyk/logtrail#162]
Since all the logs are tailed in logtrail, it would make sense to have an alarming feature that trigger an notification (mail, Slack, etc.) every time a regexp is matched.

I'm aware of the Elastalert and Sentinl solution but they are both based on an ElasticSearch query, they don't propose a stream (tail -f basically) as (log|papertrail) so for me the 2 solutions are complementary.
An alarming with logtrail would react on an event in a stream and Elastalert or Sentinel are data-frame oriented (the result of a query).

What do you think?

**Comment by sivasamyk** [comment]
@danielpetisme Thanks for feature request. The tail logic in logtrail is executed inside browser (by periodically querying the Elasticsearch for new events). The is no server component in logtrail that will continuously receive the stream of events from agents and filter them.  You can do this by adding custom filter rules to logstash with email output plugins.

**Comment by danielpetisme** [comment]
Make sense.
So won't feasible in the plugin as-is.
Thanks for the answer

**Comment by Bizzelicious** [comment]
@danielpetisme If you're still looking for a open-source monitoring and alerting solution for ES I suggest you to try ElastAlert. It works great and we run it in production. http://elastalert.readthedocs.io/en/latest/

**Comment by danielpetisme** [comment]
@Bizzelicious I'm currently using elastalert it works fine. My only regrets is the lack of a UI to manage the alerts via Kibana for instance.

I had a look to papertrail alerts and it looks awesome but as mentioned above it requires a backend. The logtrail plugin is only a front app.

**Comment by Bizzelicious** [comment]
@danielpetisme You can actually have a Elastalert GUI in Kibana to manage rules. Have a look at:
https://bitsensor.io/blog/elastalert-kibana-plugin-centralized-logging-with-integrated-alerting

**Comment by danielpetisme** [comment]
It's not compatible with Kibana 5. I tried to install a modified version from the latest build (in the gitlab). It fails to start (a shadow js error) I gave up.

**Comment by Bizzelicious** [comment]
There are alot of Kibana 5 forks of the elastalert-kibana-plugin. We're using this one in prod for Kibana 5.1.2: https://github.com/baoban/elastalert-kibana-plugin

Bitsensor has created their own Kibana 5 fork now which probably works just as good.
https://github.com/bitsensor/elastalert-kibana-plugin/tree/kibana5
