### ISSUE TITLE
message field looks like truncated

### ISSUE THREAD

**Issue by mvlach** [sivasamyk/logtrail#163]
Original message in kibana is displayed with no cut. The same message displayed in the logtrail is truncated...

Ignoring order cancelation request for order order#1009217179 because it is already in state rejected [] {"r":"59a5676ec818e7.32402933"}
vs
Ignoring order cancelation request for order order#1009217179 because it

The message is probably split to the next line.

**Comment by sivasamyk** [comment]
Can you let me know the Kibana and logtrail version your are using? Also attach a screenshot of the logtrail with issue ( make sure you hide sensitive info).

**Comment by mvlach** [comment]
![image](https://user-images.githubusercontent.com/6176546/29833567-27ae3dbc-8cec-11e7-9499-48066527728e.png)
![image](https://user-images.githubusercontent.com/6176546/29833584-31e55cc0-8cec-11e7-80c4-042a73037759.png)

Kibana Version: 5.5.1
"version": "0.1.18",

**Comment by sivasamyk** [comment]
The highlighter by default truncates the message to 100 chars. This happens only when you do highlight (i.e search). Under normal log display it should work fine (can you confirm?). Will fix this issue in next release.

https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-highlighting.html#_highlighted_fragments

**Comment by mvlach** [comment]
Hi, I applied your fix and I looks like it is repaired...
