### ISSUE TITLE
Log colorizer query

### ISSUE THREAD

**Issue by joiningnat** [sivasamyk/logtrail#166]
Hi Siva, is it possible to add log colorizer functionality to Logtrail.
For example, there is a free ATG Log Colorizer utility which colors logs of ATG application running on various app servers.
I just wonder if it is possible to implement this convenient feature in your app.
Thanks!

**Comment by joiningnat** [comment]
Thanks, I believe it is very close.
But it seems that this will not affect java stacktrace appended to the message.
Though let's try with this at first.

**Comment by sivasamyk** [comment]
@joiningnat I have added support for coloring messages. Refer to docs @ https://github.com/sivasamyk/logtrail/blob/feature/colors/docs/color_mapping.md. Download the attached logtrail zip. Give it a try and let me know your comments
[logtrail-5.5.2-0.1.20.zip](https://github.com/sivasamyk/logtrail/files/1284896/logtrail-5.5.2-0.1.20.zip)

**Comment by joiningnat** [comment]
updated the logtrail plugin with the attached one.
Getting error at kibana start:
{"type":"log","@timestamp":"2017-09-15T12:30:33Z","tags":["fatal"],"pid":15716,"level":"fatal","message":"Config schema already has key: logtrail","error":{"message":"Config schema already has key: lo                gtrail","name":"Error","stack":"Error: Config schema already has key: logtrail\n    at Config.extendSchema (/usr/share/kibana/src/server/config/config.js:51:13)\n    at /usr/share/kibana/src/server/pl                ugins/plugin_collection.js:19:12\n    at next (native)\n    at step (/usr/share/kibana/src/server/plugins/plugin_collection.js:49:191)\n    at /usr/share/kibana/src/server/plugins/plugin_collection.js                :49:361"}}

**Comment by sivasamyk** [comment]
Looks like some config info got corrupted in Kibana. Similar to this issue : https://github.com/elastic/kibana/issues/6330
Can you try the plugin in new Kibana installation?

**Comment by joiningnat** [comment]
sorry for the comment, removed it
my fault

**Comment by sivasamyk** [comment]
Great. let me know your feedback on this feature.

**Comment by joiningnat** [comment]
the feature is for 5.2 kibana and after installing on 5.1 it seems that it somehow affected 5.1 kibana UI

**Comment by sivasamyk** [comment]
added support in latest release @ https://github.com/sivasamyk/logtrail/releases/tag/v0.1.21

**Comment by joiningnat** [comment]
Hi Siva, 
Installed logtrail 5.6.1 for ELK 5.6.1.
Configured logtrail.json to have coloring. No error in kibana log.
![logtrail_json](https://user-images.githubusercontent.com/29659271/30912639-13020996-a396-11e7-8973-d5aa9d25d387.png)
Still see no color in the logs.
What have I done the wrong way?

**Comment by sivasamyk** [comment]
The mapping color values should be same as in CSS color.  You can use either `rgb(255,255,255)` or `#FFFFFF` format.

**Comment by joiningnat** [comment]
Changed to:
{
"es": {
"default_index": "jboss-*",
"allow_url_parameter": false
},
"tail_interval_in_seconds": 10,
"es_index_time_offset_in_seconds": 0,
"display_timezone": "local",
"display_timestamp_format": "MMM DD HH:mm:ss",
"max_buckets": 500,
"nested_objects" : false,
"default_time_range_in_days" : 0,
"max_hosts": 100,
"max_events_to_keep_in_viewer": 5000,
"fields" : {
"mapping" : {
"timestamp" : "@timestamp",
"display_timestamp" : "@timestamp",
"hostname" : "server_instance",
"program": "env",
"message": "message"
},
"message_format": "{{{loglevel}}} {{{message}}}"
},
"color_mapping": {
                "field": "loglevel",
                "mapping": {
                    "INFO" : "(#ADD8E6)",
                    "SEVERE" : "(#FF0000)",
                    "WARN" : "(#FFFACD)"
				}
            }
}
Still no effect(

**Comment by sivasamyk** [comment]
In case of HEX values, you need to remove the braces. It should be like 

```
"field": "loglevel",
"mapping": {
"INFO" : "#ADD8E6",
"SEVERE" : "#FF0000",
"WARN" : "#FFFACD"
}
```

**Comment by joiningnat** [comment]
Thanks a lot! So inattentive i am.
