### ISSUE TITLE
Switching Index Pattern in Settings does not always automatically switch hostname

### ISSUE THREAD

**Issue by joiningnat** [sivasamyk/logtrail#167]
When e.g. Jboss Index Pattern is selected  in Settings and you decide to switch to some other Index Pattern, hostname values are not always updated according to your selection.
I just see "No events found" message on the screen and still Jboss log hostname in hostname box, until I manually click hostname and select the required host for another Index Pattern.

Is this enhancement possible? 
Thanks in advance.

**Comment by sivasamyk** [comment]
fixed in latest release @ https://github.com/sivasamyk/logtrail/releases/tag/v0.1.21

**Comment by natburkova** [comment]
Thanks a lot, I have checked in 5.6.1.

**Comment by joiningnat** [comment]
Thanks a lot! the issue gone in 5.6.1.

**Comment by sivasamyk** [comment]
@joiningnat Happy logging!
