### ISSUE TITLE
Wrong timezone deduced  when using fields other @timestamp

### ISSUE THREAD

**Issue by sheinbergon** [sivasamyk/logtrail#169]
Hi.

In my Elasticsearch I'm storing the original message timestamp as "time". Of course we also have  @timestamp. When trying to use "time" for both "display_timestamp" and "timestamp", we're getting wrong timezones displayed.

Example: 
- Assuming that my computer time is UTC+03:00.
- Messages are logged at UTC+00:00. 
- Logtrail is configured to display in "Etc/UTC"

I'm seeing messages  displayed in UTC-03:00

**Comment by sivasamyk** [comment]
@sheinbergon Is the `time` coming from original message and is it generated in logstash? Can you share your logstash config, so I can reproduce this issue locally. With `@timestamp` TZ works fine.

**Comment by sivasamyk** [comment]
Assuming this is same as https://github.com/sivasamyk/logtrail/issues/109. So closing.
