### ISSUE TITLE
Feature request: load/save index patterns configuration in Elasticsearch

### ISSUE THREAD

**Issue by lpic10** [sivasamyk/logtrail#172]
Hello,

It would make sense if the logtrail configuration could be saved/loaded from Elasticsearch directly, even better if it could be edited in logtrail. 

Cheers

**Comment by sivasamyk** [comment]
Thanks.  Are you facing any issues in using logtrail.json? Just want to understand the usecase.

**Comment by lpic10** [comment]
We deploy kibana using docker, and it would be easier if we didn't have to change configuration files on it.  Also it could help when deploying multiple kibana instances.

**Comment by sivasamyk** [comment]
Got it. How about if we provide an option to read complete logtrail.json from ES .kibana index if available. Else it will pick from local config file.  Saving and updating the config file in ES should be done externally using curl. Does this solve the problem?

**Comment by lpic10** [comment]
Yes, that would work.

**Comment by danielmotaleite** [comment]
yes, this please!
right now i also have to inject my logtrail.json config after the plugin install, having the config being loaded from a ES index would make everything easier.
The down side is that you may need to "rename"/update/remove configs when versions change require then. Mark the config with a version and every time a new config change, change the version and make a macro to "upgrade" then or at very least, warn the user about the need to change the config

**Comment by sivasamyk** [comment]
@lpic10 @danielmotaleite I have added initial support for this feature in https://github.com/sivasamyk/logtrail/releases/tag/v0.1.22.

You can upload the logtrail.json file to ES using following curl command:

`curl -XPUT 'localhost:9200/.logtrail/config/1?pretty' -H 'Content-Type: application/json' -d@<path_to_logtrail.json_file>`

If available then logtrail will use the json from ES. Checkout the feature and let me know your comments!

**Comment by sivasamyk** [comment]
Please note any changes to logtrail,json in elasticsearch requires restart of Kibana to take effect.

**Comment by lpic10** [comment]
@sivasamyk it works as expected, many thanks !

**Comment by danielmotaleite** [comment]
Sorry for the delay, only now i manage to upgrade elasticsearch
Works perfect @sivasamyk, thanks a lot for this feature, it makes logtrail much easier to manage

**Comment by danielmotaleite** [comment]
please do not forget to add that curl to the readme, so others can use this feature

**Comment by sivasamyk** [comment]
Updated readme : https://github.com/sivasamyk/logtrail/blob/master/docs/how_to.md#3-load-logtrail-configuration-from-elasticsearch
