### ISSUE TITLE
Change time "Now" button UI glitch

### ISSUE THREAD

**Issue by iKrushYou** [sivasamyk/logtrail#179]
Running your latest logtrail-5.5.1-0.1.21 plugin I'm seeing (and have been seeing in the past) a UI glitch with the "Now" button:

![image](https://user-images.githubusercontent.com/1500721/30396533-f237560c-9897-11e7-8ebf-7bbe17dae717.png)

I'm running Chrome Version 55.0.2883.87 m

------------------------------------------------------------------------

Tried in IE also:
![image](https://user-images.githubusercontent.com/1500721/30396600-2a2864fc-9898-11e7-80f8-e8de7b65e08c.png)

------------------------------------------------------------------------
And just downloaded the latest Firefox for completeness:
![image](https://user-images.githubusercontent.com/1500721/30396672-67214338-9898-11e7-913e-e7cbe36aa254.png)

**Comment by sivasamyk** [comment]
fixed in latest release @ https://github.com/sivasamyk/logtrail/releases/tag/v0.1.21
