### ISSUE TITLE
How you setup directives

### ISSUE THREAD

**Issue by Kikketer** [sivasamyk/logtrail#18]
This isn't an issue, more of a question.
I'm attempting to setup a directive somewhat similar to what you have in your `clickOutside` directive.  I'm currently getting an `unknown provider` error when attempting to hook up a simple directive.  Is there something I'm missing?

I noticed your code has (https://github.com/sivasamyk/logtrail/blob/master/public/app.js#L476)
```javascript
var app = modules.get('my-module', []);
app.controller('controller-name', function() ...

// Then later:
modules.get('controller-name')
  .directive('directive-name', function() ...
```
when I would normally attach directives to the module itself:
```javascript
modules.get('my-module', [])
  .controller('controller-name', function() ...
  .directive('directive-name', function() ...
```

I've tried both ways, attaching it to my controller or my module.
The error claims that the directive I'm attempting to use is not available or perhaps redefining the same module twice.  I guess I'm not 100% sure what the `modules` component gives me.
Am I missing something here?  Is there some sort of hidden documentation around the use of this?

**Comment by sivasamyk** [comment]
@Kikketer Are you trying this your own plugin or adding a new directive in logtrail plugin? I am not well versed with AngularJS concepts (I wrote most of logtrail-kibana integration code by checking old timelion plugin ). If you can share your plugin code, I can debug and check if there are any issues.

**Comment by Kikketer** [comment]
I was actually copying your plugin to figure out how to make my own.  You had a nice simple thing to follow compared to the other intense plugins.
I did figure out what was going on, it seems that the `modules.get` will work either way, but probably preferred to have it ask for the module instead of a controller inside that module.

Elastic has done some crafty things to try and get dependency management to work for the build process and Angular.  Sometimes I wish there was a better way, but what they came up with works.

You can see the details of what they did here:
https://github.com/elastic/kibana/blob/01b426c94957adc7914371d91c9989b3a155a526/src/ui/public/modules.js#L34

We can close this out as my question is answered, we are all learning!
