### ISSUE TITLE
Load balancing across multiple kibana nodes fail

### ISSUE THREAD

**Issue by mohamed-mfarag** [sivasamyk/logtrail#180]
Hi,

We have 2 kibana nodes and we have installed logtrail on both nodes and we are using apache reverse proxy to balance the requests between the 2 nodes.

However once we start up both nodes in the same time we receive the attached error 
![kibana_issue_20170914](https://user-images.githubusercontent.com/14858061/30481497-613d442a-9a1f-11e7-8b4f-6cd177f4a372.png)

there is no error reported in kibana logs and when we checked back with elastic support, they came back pointing toward the logtrail plugin as causing this issue, i have tried to use disable the plugin on both nodes and try again and it did resolve the issue.

Is there any possibility to resolve this issue from your side, i have very limited experience in this area so i cant locate the issue on my side.

Please let me know what kind of info you need to help you trace down the issue.

ELK stack version 5.5.1

Reagrds
Mohamed Farag

**Comment by sivasamyk** [comment]
@mohamed-mfarag I have not tested logtrail plugin in this set up. Did you get any info from Elastic support regarding the issue cause by logtrail plugin? Can you also attach the errors if any, from the Chrome developer console?

**Comment by mohamed-mfarag** [comment]
@sivasamyk  Sadly Elastic didnt offer much as logtrail is not an officially supported plugin, Chrome does not show any errors, that was the strange thing and why i was not able to locate the error in the beginning.

**Comment by sivasamyk** [comment]
Can you share the apache reverse proxy configuration for Kibana? I will try to reproduce the issue locally.

**Comment by mohamed-mfarag** [comment]
Please find it below :

------------------------------------------------------------------------
<Proxy "balancer://balancer-kibana">
    BalancerMember "http://kibana-app01:5601"
    BalancerMember "http://kibana-app02:5601"
</Proxy>


ProxyPass /kibana balancer://balancer-kibana
ProxyPassReverse /kibana balancer://balancer-kibana

ProxyPass /bundles balancer://balancer-kibana/bundles
ProxyPassReverse /bundles balancer://balancer-kibana/bundles

ProxyPass /logtrail balancer://balancer-kibana/logtrail
ProxyPassReverse /logtrail balancer://balancer-kibana/logtrail

ProxyPass /status balancer://balancer-kibana/status
ProxyPassReverse /status balancer://balancer-kibana/status

ProxyPass /api balancer://balancer-kibana/api
ProxyPassReverse /api balancer://balancer-kibana/api

ProxyPass /api/status balancer://balancer-kibana/api/status
ProxyPassReverse /api/status balancer://balancer-kibana/api/status

ProxyPass /plugins balancer://balancer-kibana/plugins
ProxyPassReverse /plugins balancer://balancer-kibana/plugins

ProxyPass /app balancer://balancer-kibana/app
ProxyPassReverse /app balancer://balancer-kibana/app

ProxyPass /elasticsearch balancer://balancer-kibana/elasticsearch
ProxyPassReverse /elasticsearch balancer://balancer-kibana/elasticsearch

ProxyPass /login balancer://balancer-kibana/login
ProxyPassReverse /login balancer://balancer-kibana/login

ProxyPass /logout balancer://balancer-kibana/logout
ProxyPassReverse /logout balancer://balancer-kibana/logout

ProxyPass /app balancer://balancer-kibana/app
ProxyPassReverse /app balancer://balancer-kibana/app

ProxyPass /es_admin balancer://balancer-kibana/es_admin
ProxyPassReverse / balancer://balancer-kibana/es_admin

ProxyPass /ui balancer://balancer-kibana/ui
ProxyPassReverse /ui balancer://balancer-kibana/ui

ProxyPass / balancer://balancer-kibana/app/kibana
ProxyPassReverse / balancer://balancer-kibana/app/kibana

ProxyPreserveHost on

**Comment by sivasamyk** [comment]
@mohamed-mfarag I tried with attached conf (000-default.conf) and it works. Kibana version is 5.5.2

apache2 -v

```
Server version: Apache/2.4.18 (Ubuntu)
Server built:   2017-07-27T14:34:01

```
[reverse-proxy.txt](https://github.com/sivasamyk/logtrail/files/1309998/reverse-proxy.txt)

**Comment by mohamed-mfarag** [comment]
Do you have xpack also enabled ?
________________________________

**Comment by sivasamyk** [comment]
No. Mine is plain Kibana installation with logtrail. I will try with x-pack installed.

**Comment by sivasamyk** [comment]
Oops. Looks like xpack is licensed. I do not have license to run x-pack.

**Comment by mohamed-mfarag** [comment]
Sorry for the late reply, i was not able to update for the last 2 weeks, however i know there is a trail license for x-pack, would you be able to test using this one ?

**Comment by sivasamyk** [comment]
@mohamed-mfarag There is a solution suggested in this link https://discuss.elastic.co/t/kibana-uncaught-typeerror/82107 for same Kibana error.

**Comment by mohamed-mfarag** [comment]
This issue is for only single node as far as i can see from the post and if its related to the user shell it should happen on both node but the issue we have happen only if we use both nodes and balance them using Apache - but if we stop one every thing work fine, have you managed to test with X-pack , please let me know if i can help ?

**Comment by mohamed-mfarag** [comment]
Hi @johnseekins 

Thanks for your suggestion, that did solve the issue !
