### ISSUE TITLE
Search Highlight Issue

### ISSUE THREAD

**Issue by iKrushYou** [sivasamyk/logtrail#181]
When searching for a phrase (a term with multiple words in quotes) there is a bug while logtrail tries to highlight 

![2017-09-18 10 00 54](https://user-images.githubusercontent.com/1500721/30551707-604f30f4-9c69-11e7-86ae-6d167c978b44.png)
![2017-09-18 10 01 21](https://user-images.githubusercontent.com/1500721/30551710-64dffc20-9c69-11e7-9ff4-5cee86292c4f.png)

**Comment by sivasamyk** [comment]
fixed in latest release @ https://github.com/sivasamyk/logtrail/releases/tag/v0.1.21
