### ISSUE TITLE
Error message relating to Elasticsearch host search

### ISSUE THREAD

**Issue by vpm-bradleyhession** [sivasamyk/logtrail#189]
When using an index other than logstash-* the below error appears.

Error! Exception while fetching hosts : [parsing_exception] Expected [START_OBJECT] under [path], but got a [VALUE_STRING] in [nested], with { line=1 & col=36 }

I have tried to change my mapping to include .keyword on the end as we run into the "Fielddata is disabled on text fields" by default issue in elasticsearch.

Any pointers?

Thanks,

**Comment by sivasamyk** [comment]
When the index pattern does not start with logstash-*, the default logstash template mapping is not applied. Hosts query uses term aggregation and it is disabled on text fields. Would recommend to configure custom template in elasticsearch output for logstash. The default template used by logstash is @ https://github.com/logstash-plugins/logstash-output-elasticsearch/blob/master/lib/logstash/outputs/elasticsearch/elasticsearch-template-es5x.json. You can explicitly specify this using `template` field of elasticsearch output.

**Comment by vpm-bradleyhession** [comment]
Hmm. I applied this template to my index, can even see the .keyword value for my field as both searchable and aggregatable. Do I need to wait for a new index creation maybe?

--


.

**Comment by sivasamyk** [comment]
Yes templates are applied at index creation time. But looking at the code now, I see logtrail automatically appends .keyword field only for indices starting with 'logstash-' pattern. I think this needs to be fixed. Will update the code looks to keyword mapping for the field and then append.

**Comment by vpm-bradleyhession** [comment]
Latest commit fixed my issue, also using the template also was a work around.

Thanks!

**Comment by sivasamyk** [comment]
Fixed in https://github.com/sivasamyk/logtrail/releases/tag/v0.1.22
