### ISSUE TITLE
Basic auth error

### ISSUE THREAD

**Issue by faber** [sivasamyk/logtrail#19]
Hey, I'm having an issue where logtrail fails with an authorization error when trying to hit the `/logtrail/validate/es` endpoint.  I'm running Kibana behind nginx with basic auth setup on nginx to protect access.  The elasticsearch instance has its own separate HTTP auth as well.  

The validate request is sending the correct authorization header (for nginx), and the 401 response I get includes this json payload:

```json
{"statusCode":401,"error":"Unauthorized","message":"Unauthorized","attributes":{"realm":"Authorization Required","error":"Unauthorized"}}
```

I'm running kibana 4.4.2 with logtrail 0.1.5.

Any ideas what could be going wrong? Thanks!

**Comment by sivasamyk** [comment]
@faber I followed the following guide ( used httpd-tools/apache2-utils to generated password) and it works fine. I tested with Kibana 4.6.1 and logtrail 0.1.5. Is your Kibana UI working fine with basic auth? Is the issue seen only with logtrail plugin?

https://www.digitalocean.com/community/tutorials/how-to-install-elasticsearch-logstash-and-kibana-elk-stack-on-centos-7

**Comment by faber** [comment]
Hey, my setup is a little bit different than that one but the basic idea is the same, and the nginx config is nearly identical.  Accessing the Kibana UI does work fine, it's only the logtrail page that gets stuck.  I'm wondering if it has to do with the fact that the Elasticsearch instance is on another machine, behind a separate set of HTTP credentials?  Is there anyway logtrail could be missing some of the elasticsearch config from Kibana? I tried to hunt this down but I'm not too familiar w/ the plugin environment in Kibana so I didn't get very far.

Not sure if this is helpful, but here's a screenshot of the network calls made on a Kibana page:

![screen shot 2016-12-08 at 11 00 32 am](https://cloud.githubusercontent.com/assets/43680/21023535/caa760f2-bd35-11e6-8a68-9c21f4612029.png)

And here's a screenshot of the network calls on the Logtrail page:

![screen shot 2016-12-08 at 11 01 16 am](https://cloud.githubusercontent.com/assets/43680/21023547/dcd5b328-bd35-11e6-8148-eaeaaca8d7d4.png)

When the whole page loads for the first time, I authenticate w/ the basic auth configured on nginx.  Then, once that `es` request is sent, it prompts me again, but the credentials no longer work.

**Comment by sivasamyk** [comment]
Logtrail uses a same ES API used by Kibana to talk to Elasticsearch. May be this could be a 401 thrown by ES server due to invalid auth. I will test with ES Auth and get back to you.

**Comment by faber** [comment]
Alright, let me know if and how I can help debug. Thanks!

**Comment by sivasamyk** [comment]
@faber Please reopen if you still face this issue in latest release.
