### ISSUE TITLE
Hosts search

### ISSUE THREAD

**Issue by vpm-bradleyhession** [sivasamyk/logtrail#193]
When running more than 50 hosts, searching is cumbersome. It would be nice to be able to search the host selector. In my case for example, we are shipping logs from Kubernetes with >1000 containers on it, so a search would really help here :)

**Comment by sivasamyk** [comment]
Added support for search in hosts popup when hosts list is greater than 10. Download latest release @ https://github.com/sivasamyk/logtrail/releases/download/v0.1.23/logtrail-5.6.3-0.1.23.zip
