### ISSUE TITLE
Search Input field keeps "Uses lucene query syntax"

### ISSUE THREAD

**Issue by TVictor** [sivasamyk/logtrail#195]
I tried searching if this issue has been logged already or fixed somewhere else, but could not find anything.

Long searches looks as follows:

![screen shot 2017-10-19 at 10 35 47 am](https://user-images.githubusercontent.com/1934066/31761783-74265388-b4b9-11e7-907c-8e8383df0ca6.png)

It makes it difficult to see what you are doing, what would be nice is to either stretch out the search bar and align the buttons to the far right or hide the "Uses lucene query syntax" when you start typing

Thanks.

**Comment by sivasamyk** [comment]
@TVictor Thanks for the issue. Have pushed fix and will be available in next release. I am wondering how the 'Uses Lucene query syntax' text moved to left in your screenshot with empty space on the right. Can you let me know the browser version, OS and screen res you are using?

**Comment by sivasamyk** [comment]
Added option to hide help link when search box contains text. Download latest release at https://github.com/sivasamyk/logtrail/releases/download/v0.1.23/logtrail-5.6.3-0.1.23.zip

**Comment by TVictor** [comment]
I am using macOS X, on Chrome Version 61.0.3163.100 (Official Build) (64-bit) , with screen resolution of 1920X1080
