### ISSUE TITLE
Do not append .raw in fields

### ISSUE THREAD

**Issue by danielmotaleite** [sivasamyk/logtrail#20]
I have fields not analyzed, like hostname, so i do not have the .raw version. Logtrail is trying to append that and fails to list and search those fields.

So i suggests that you change the examples to use the .raw fields directly (and recommend their usage) and stop appending then by default. This will allow admins to choose if they want to use the the exact name of the field to use

**Comment by sivasamyk** [comment]
@danielmotaleite Thanks for the suggestion.  In Elastic 5.0 raw fields have been replaced by .key fields. Will check and see if we can do this logtrail for ES 5.0.

**Comment by danielmotaleite** [comment]
thanks :)
i just upgraded to kibana 5.1.1 (thanks for the logtrail update!) and i still have the problem, now even more confusing :D 

in 5.1.1, logtrail tries to add .keyword... that i do not yet have as i didn't updated the index template because it would break many of my dashboards

so yes, i think is better not to assume everyone have a standard config and logtrail should stop automatically appending .raw and .keywords and use only what the admin setup in the config file. On the config file, add small comment recommending using the .raw/.keyword when possible and let the admin decide what fields to use.

**Comment by sivasamyk** [comment]
@danielmotaleite The raw/keyword fields are not part of source document. Since the field mapping is used to query directly from source document, I am planning to add a new boolean config param called 'use_analyzed_fields'. Setting it to false won't append raw/keyword to field names. Default value : true

**Comment by danielmotaleite** [comment]
That is a good idea! Thanks! :)

i for now removed locally the ``` + ".raw ``` from ./public/app.js and ./server/routes/server.js , removed kibana optimized js and restarted it...now i can finally use the hostname (TLD for me) and program (environment for me) mapped fields

**Comment by sivasamyk** [comment]
Raw fields are removed in latest logstash/ES and replace with .keyword fields. Logtrail has been updated to use .keyword field only when the index pattern is 'logstash-'.
