### ISSUE TITLE
 Exception while fetching hosts : [illegal_argument_exception] Fielddata is disabled on text fields by default

### ISSUE THREAD

**Issue by moreiramarti** [sivasamyk/logtrail#205]
Hello,

I just upgrade to kibana 6.0.0, since then, I see this error : 
Error! Exception while fetching hosts : [illegal_argument_exception] Fielddata is disabled on text fields by default. Set fielddata=true on [host] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory. Alternatively use a keyword field instead.

I use default logstash-* index, can you help me resolve my issue?

Regards,
Martinho MOREIRA

**Comment by moreiramarti** [comment]
Sorry I works fine
My mistake

**Comment by mingfang** [comment]
I'm seeing the problem on some instances but not others.

**Comment by mingfang** [comment]
i found that restarting kibana causes this problem to go away

**Comment by moreiramarti** [comment]
same here

**Comment by sivasamyk** [comment]
Logtrail is loading some meta data on startup. The metadata loading might be different, if the index pattern did not exist during startup. May be on restart the metadata is loaded properly. Will verify and fix it if true.

**Comment by sivasamyk** [comment]
Issue fixed in https://github.com/sivasamyk/logtrail/releases/download/v0.1.24/logtrail-6.1.1-0.1.24.zip

**Comment by ShaneSaww** [comment]
@sivasamyk I'm also seeing this issue on Kibana 5.6.5. Is there a plan to create a logTrail release with this fix for Kibana 5.6.5?
