### ISSUE TITLE
Search returns messages from different time

### ISSUE THREAD

**Issue by serapch** [sivasamyk/logtrail#207]
Greetings,

I'm using ES, logstash and kibana 5.6.3 and logtrail 0.1.23.

I'm gathering information from springboot application, converting the timestamp to a new field with timezone Europe/Sofia, which then is displayed in LogTrail. The logs' timezone is also the same. The dateFormat:tz and display_timezone are also set to"Europe/Sofia"

But when I use the search, I receive messages which are +2 hours from the desired time:
![logtrail](https://user-images.githubusercontent.com/2870357/33175202-9c8094b8-d063-11e7-89c6-84bc12003b41.JPG)

> 2017-11-23 11:23:45,868 bg.vivacom.commerce.integration.aspects.Audit [http-nio-8111-exec-6] INFO : Integration Service Logger Time Execution|ProductDetailWSClientImpl:getProductDetails|241|ms|SUCCESS

Here is the logstash config:

`filter {
  if [type] == "java_log" {
    grok {
      match => { "message" => "%{TIMESTAMP_ISO8601:logdate} %{JAVACLASS:application} \[%{DATA:thread_name}\] %{LOGLEVEL:log_level} : %{GREEDYDATA:data}" }
    }
    mutate {
      gsub => [
        "path", "/apps/app/logs/", ""
      ]
    }
    date {
      match => ["logdate", "ISO8601"]
      timezone => "Europe/Sofia"
      target => "logdate"
    }
  }
}`

and the logtrail config:

`{
  "index_patterns" : [
    {
      "es": {
        "default_index": "logstash-*",
        "allow_url_parameter": false
      },
      "tail_interval_in_seconds": 5,
      "es_index_time_offset_in_seconds": 5,
      "display_timezone": "Europe/Sofia",
      "display_timestamp_format": "MMM DD HH:mm:ss.SSS",
      "max_buckets": 10000,
      "nested_objects" : false,
      "default_time_range_in_days" : 0,
      "max_hosts": 100,
      "max_events_to_keep_in_viewer": 10000,
      "fields" : {
        "mapping" : {
            "timestamp" : "logdate",
            "display_timestamp" : "logdate",
            "hostname" : "host",
            "program": "path",
            "message": "data"
        },
        "message_format": "{{{application}}} [{{{thread_name}}}] {{{log_level}}}: {{{data}}}"
      },
      "color_mapping" : {
        "field" : "log_level",
        "mapping" : {
          "ERROR": "#ff3232",
          "WARN": "#ff7f24",
          "DEBUG": "#ffb90f"
        }
      }
    }
  ]
}`

**Comment by sivasamyk** [comment]
@serapch You need to map `@timestamp` field to timestamp in field mapping of logtrail.json. Checkout the same config for spring boot app at https://github.com/sivasamyk/logtrail-config-examples/blob/master/spring-boot/logtrail.json

**Comment by serapch** [comment]
@sivasamyk The result is the same:
![logtrail2](https://user-images.githubusercontent.com/2870357/33271539-31f86780-d390-11e7-8e43-10ca7acbdc05.JPG)

Also the order of the messages in LogTrail is messed:
![logtrail3](https://user-images.githubusercontent.com/2870357/33271920-49971c0a-d391-11e7-8b58-8d587b11c5d1.JPG)

The reason to use another date field (logdate) is that when I got multiple events in one second, they are displayed randomly and I needed precision to fractions. I suppose that the time used is the one when the events are stored in Elasticsearch index

**Comment by sivasamyk** [comment]
Sorry I did not see that you have added `target` field in logstash date filter. The mapping of logdate to timestamp in your earlier config is correct. Can you try using the "Now" button to specify the date required?  Also can you try search with this filter: `logdate: "2017-11-23T09:23+02:00"` . This should list all logs at 9:23 AM Sofia time.

**Comment by serapch** [comment]
@sivasamyk Yes, with adding +02:00, the correct messages are shown.
Thank you for your help and the time you spent
