### ISSUE TITLE
Kibana 6 : angular error

### ISSUE THREAD

**Issue by ebuildy** [sivasamyk/logtrail#208]
* https://github.com/sivasamyk/logtrail/releases/download/v0.1.23/logtrail-6.0.0-0.1.23.zip
* Version: 6.0.0
* Build: 16070

Cannot use Kibana any more, got this error:

> Error: Uncaught Error: [$injector:unpr] Unknown provider: sessionTimeoutProvider <- sessionTimeout <- $http <- config
> http://errors.angularjs.org/1.6.5/$injector/unpr?p0=sessionTimeoutProvider%20%3C-%20sessionTimeout%20%3C-%20%24http%20%3C-%20config (http://kibana.127.0.0.1.xip.io/bundles/commons.bundle.js?v=16070:35)
>     at window.onerror (http://kibana.127.0.0.1.xip.io/bundles/commons.bundle.js?v=16070:95:24726)

**Comment by sivasamyk** [comment]
@ebuildy Do you have x-pack installed? Looks like this is similar to https://github.com/elastic/kibana/issues/9369.

**Comment by ebuildy** [comment]
Yes, you are right.

I am testing it again so!

**Comment by ebuildy** [comment]
Very sorry to post this issue here!

Deleted ``optimize/*`` and restart did the trick. Thanks you
