### ISSUE TITLE
Logtrail does not show data for object property field

### ISSUE THREAD

**Issue by piotrkochan** [sivasamyk/logtrail#216]
Hi my logs looks like:

```
{
...
    "nginx.error.message": "*135733 client closed connection while waiting for request",
    "nginx.error.pid": 30016,
    "nginx.error.tid": 30016,
    "nginx.error.level": "info",
...
}
```

I want to display "nginx.error.message", so my Logtrail configuration is:

```
      "fields" : {
        "mapping" : {
            "timestamp" : "@timestamp",
            "display_timestamp" : "@timestamp",
            "hostname" : "hostname",
            "message": "nginx.error.message"
        },
        "message_format": "[{{{tag}}}] {{{nginx.error.message}}} {{{message}}}"
      },
```
But nor nginx.error.message and message shows up in Logtrail in Kibana. Only tag is visible.

ElasticSearch version: 6.0.0

**Comment by sivasamyk** [comment]
@piotrkochan Did you try mapping other fields like nginx.error.level in message_format. You can remove `{{{message}}}` from message_format mapping. Can you paste the complete JSON document from ES ( with _source field)?

**Comment by piotrkochan** [comment]
Sure, here it is:

```
{
  "_index": "nginx-2017.12.14",
  "_type": "fluentd",
  "_id": "XOxWVGABNjFnsxSKi8fS",
  "_score": 1,
  "_source": {
    "nginx.error.message": "*136039 client closed connection while waiting for request",
    "nginx.error.pid": 30021,
    "nginx.error.tid": 30021,
    "nginx.error.level": "info",
    "nginx.error.client": "..someipthere...",
    "nginx.error.server": "...someipthere....",
    "hostname": "my-server",
    "@timestamp": "2017-12-14T10:23:50.000000000+01:00",
    "tag": "nginx.error.test"
  },
  "fields": {
    "@timestamp": [
      "2017-12-14T09:23:50.000Z"
    ]
  }
}
```

**Comment by piotrkochan** [comment]
`"message_format": "{{{nginx.error.level}}} {{{nginx.error.pid}}}"` does not work as well

**Comment by sivasamyk** [comment]
Looks like these are not nested properties but keys with dots. Can you try this message_format?

`"message_format": "[{{{tag}}}] {{{[nginx.error.message]}}}"`

Notice I have enclosed the field within [] (Segment literal notation). Logtrail uses handlebar to format the template.

**Comment by piotrkochan** [comment]
It worked, thanks. Does `nested_objects` option makes any difference in current Logtrail version?

**Comment by sivasamyk** [comment]
Nope `nested_objects` config has been removed in latest version of Logtrail.

**Comment by piotrkochan** [comment]
One more question. Now my error message is a link. It is possible to make it not clickable?

**Comment by sivasamyk** [comment]
Looks like logtrail is treating it as link. Will fix it next release

**Comment by piotrkochan** [comment]
I think I figured it out, instead of `{{{[nginx.error.message]}}}` I've used `{{[nginx.error.message]}}` and it looks good now.

**Comment by sivasamyk** [comment]
Ah. Yes you can do it 👍

**Comment by fenneh** [comment]
@piotrkochan - Have you actually clicked on one of the links? I have a similar scenario of fields with dot notation

{{my.field}} = Blank
{{[my.field]}} = Shows data, not clickable
{{{[my.field]}}} = Shows data, is clickable, upon click the lucene query at the bottom is using [my.field] as the field name and throwing errors. 
{{{my.field}}} = Blank

This is in Kibana 6.0 running LogTrail 6.0.0-0.1.23

**Comment by piotrkochan** [comment]
I have same issues
W dniu śr., 3.01.2018 o 13:55 fen <notifications@github.com> napisał(a):

**Comment by fenneh** [comment]
Opened https://github.com/sivasamyk/logtrail/issues/223 to cover issues i'm seeing in this area.
