### ISSUE TITLE
support for 5.6.5

### ISSUE THREAD

**Issue by wdauchy** [sivasamyk/logtrail#217]
Hello,

I cannot install logtrail on ES5.6.5 because of version mismatch.

> STDERR: Plugin installation was unsuccessful due to error "Incorrect Kibana version in plugin [logtrail]. Expected [5.6.5]; found [5.6.4]"

**Comment by sivasamyk** [comment]
Download the latest 5.6.5 release @ https://github.com/sivasamyk/logtrail/releases/download/v0.1.23/logtrail-5.6.5-0.1.23.zip

**Comment by wdauchy** [comment]
thanks
