### ISSUE TITLE
Suggestion: Move search of systems to top and resize search window

### ISSUE THREAD

**Issue by amphibithen** [sivasamyk/logtrail#220]
currently when i click on `all systems`, every time i have to scroll down to the search field in order to start searching.  i think this should be at the top, or the search window should default at the bottom.  most if not all systems that have search capability default to the search box, and provide the capability to scroll to the results, i think this should act the same.

also setting the default size of the search window to larger, or at least being able to resize it, is also desirable because my systems each wrap to 4 lines right now per system, which makes reading through the list even more difficult.
![logtrail-enhancement](https://user-images.githubusercontent.com/9948555/34226858-17ee9164-e599-11e7-9bdb-db309f1b069b.png)

**Comment by sivasamyk** [comment]
I remember testing search box stays at the bottom. Will recheck and fix. will resize the search popup.

**Comment by sivasamyk** [comment]
Fixed the position of search and all systems. Also made the width of systems larger based on content.

Download the latest release from https://github.com/sivasamyk/logtrail/releases/download/v0.1.25/logtrail-6.1.1-0.1.25.zip
