### ISSUE TITLE
Dot notation fields when clicked in message_format

### ISSUE THREAD

**Issue by fenneh** [sivasamyk/logtrail#223]
Hey, 

I've noticed something odd with fields which use dot notation.

`{{my.field}}` = Blank
`{{[my.field]}}` = Shows data, not clickable
`{{{[my.field]}}}` = Shows data, is clickable, upon clicking the lucene query at the bottom is using [my.field] as the field name and throws errors.
`{{{my.field}}}` = Blank

This is in Kibana 6.0 running LogTrail 6.0.0-0.1.23

Is this a case of editing the app.js to strip out the [ ] from the object when clicked or am I screwing up the syntax for message_format?

**Comment by sivasamyk** [comment]
@fenneh Do you have fields with dots in their name or they are nested JSON fields?

**Comment by sivasamyk** [comment]
In case of fields with . in name use  {{{[field.value]}}}. Fixed in latest release  https://github.com/sivasamyk/logtrail/releases/download/v0.1.25/logtrail-6.1.1-0.1.25.zip
