### ISSUE TITLE
v0.1.24 for kibana 6.0.0

### ISSUE THREAD

**Issue by moreiramarti** [sivasamyk/logtrail#224]
Hello, 

Do you think it's possible to have v0.1.24 compatible with kibana 6.0.0 ?

Regards,
Martinho MOREIRA

**Comment by sivasamyk** [comment]
@moreiramarti Following are the steps:

1. Download the latest logtrail zip from https://github.com/sivasamyk/logtrail/releases/download/v0.1.25/logtrail-6.1.1-0.1.25.zip
2. Unzip the contents and change `kibana.version` to 6.0.0 in `package.json`
3. zip it back. Now you can install this in Kibana 6.0.0

**Comment by moreiramarti** [comment]
Thank you very much 
I will do that
