### ISSUE TITLE
Can't Install Plugin

### ISSUE THREAD

**Issue by ayseff** [sivasamyk/logtrail#232]
This may be an issue with my Kibana installation, and if so, please point me in the right direction.  My Kibana is working fine.  But when I run:

`./bin/kibana-plugin install https://github.com/sivasamyk/logtrail/releases/download/v0.1.25/logtrail-6.1.2-0.1.25.zip`

I get:
`-bash: ./bin/kibana-plugin: No such file or directory`

**Comment by sivasamyk** [comment]
Where are you executing `kibana-plugin` command from? Can you check if the file exists?

**Comment by ayseff** [comment]
Was executing from `/opt/kibana/bin/`, which is the same directory as the kibana binary.  You are correct; `kibana-plugin` does not exist.  `sudo find / -type f -iname "*kibana-plugin*"` yields no results.  How do I get the `kibana-plugin `file?

Thanks,

**Comment by sivasamyk** [comment]
Did you download Kibana from : https://www.elastic.co/downloads/kibana? If not can you download from here and check if `kibana-plugin` file is present?

**Comment by ayseff** [comment]
My apologies.  Was on a different server running an older version of ELK.
