### ISSUE TITLE
Field with `-` in the name will not be linked

### ISSUE THREAD

**Issue by philomory** [sivasamyk/logtrail#238]
Ever since 479cd57b4cdce75af1988cc9af7eee0edb7ffee0 changed 
https://github.com/sivasamyk/logtrail/blob/9d4cee28df72945f239511098f16244ccde8c585/server/routes/server.js#L6, it's no longer possible to generate links to field with `-` in the name, e.g. `{{{media-id}}}`.

**Comment by philomory** [comment]
Note that these still work for the defined mappings, I'm only talking about message_format.

**Comment by sivasamyk** [comment]
Break the regex matching. Assumed the field names will contain only `a-zA-Z0-9_.`. Updated the regex

**Comment by sivasamyk** [comment]
Fixed in https://github.com/sivasamyk/logtrail/releases/tag/v0.1.26
