### ISSUE TITLE
Support for Kibana 6.2.x

### ISSUE THREAD

**Issue by x-gnn** [sivasamyk/logtrail#240]
Can you please support the latest Kibana Release 6.2.x. Thanks!
```
Plugin installation was unsuccessful due to error "Incorrect Kibana version in plugin [logtrail]. Expected [6.2.1]; found [6.1.3]"
The command '/bin/sh -c ./bin/kibana-plugin install https://github.com/sivasamyk/logtrail/releases/download/v0.1.25/logtrail-6.1.3-0.1.25.zip' returned a non-zero code: 70
```

**Comment by jdambly-ns** [comment]
👍

**Comment by Vad1mo** [comment]
I see there is a branch for 6.2.1, is there anything left to do a release?

**Comment by sivasamyk** [comment]
Some changes in Kibana 6.2.1 is breaking the UI in logtrail. This needs some work. Will release an update once these issues are fixed.

**Comment by sivasamyk** [comment]
Download logtrail release for 6.2.x from https://github.com/sivasamyk/logtrail/releases/tag/v0.1.26

**Comment by x-gnn** [comment]
Thanks a lot!
