### ISSUE TITLE
Error! Exception while fetching hosts : undefined

### ISSUE THREAD

**Issue by jchannon** [sivasamyk/logtrail#243]
I have the following config file and it seemed to work well until I tried something with my Elasticsearch data.

I exported my data using elasticdump and imported it onto a clean system where logtrail is installed with the below config.

When I imported my data I imported it as a different index name ie. it was exported with `fluentd-YYYYMMDD` and I importerd as `MyCustomer` and went to use log trailI get the below. Any ideas?

```
{
  "index_patterns" : [
    {
      "es": {
        "default_index": "fluentd-*",
        "allow_url_parameter": false
      },
      "tail_interval_in_seconds": 10,
      "es_index_time_offset_in_seconds": 0,
      "display_timezone": "local",
      "display_timestamp_format": "YYYY-MM-DD HH:mm:ss:SSSSSSSSS",
      "max_buckets": 500,
      "nested_objects" : true,
      "default_time_range_in_days" : 0,
      "max_hosts": 100,
      "max_events_to_keep_in_viewer": 5000,
      "fields" : {
        "mapping" : {
            "timestamp" : "@timestamp",
            "display_timestamp" : "@timestamp",
            "hostname" : "@log_name",
            "program": "",
            "message": "info.Message"
        },
        "message_format": "{{{ThreadId}}} {{{level}}} {{{info.Component}}} {{{info.Method}}} {{{info.Message}}}"
      }
    }
  ]
}
```

![screen shot 2018-03-02 at 14 07 13](https://user-images.githubusercontent.com/105126/36902625-0b0dcb28-1e23-11e8-852f-8eb9f7bf1f5f.png)

Version : logtrail-6.0.0-0.1.23

**Comment by sivasamyk** [comment]
@jchannon  If you have imported new data with index name `MyCustomer`, should the `default_index` field in logtrail.json be set to `MyCustomer`? Can you list the indices (`curl 'localhost:9200/_cat/indices?v`) in new setup and check if the `fluentd-*` index patterns are available?

**Comment by jchannon** [comment]
They aren't

**Comment by sivasamyk** [comment]
You mean the index names are still `fluentd-*`? Can you check if there any exceptions in Kibana server logs or logtrail UI ( via Chrome Dev tools console)? Can you list indices in ES?

**Comment by jchannon** [comment]
So on a clean system the log trail is setup to use fluentd but I import the data as MyCustomer and logtrail fails

**Comment by jchannon** [comment]
I've just done another test one where logtrail works and I have a index in ES with fluentd-*, created another index with some data and gone to logtrail but it doesn't see my new index.  Does logtrail not dynamically look up indexes?

**Comment by jchannon** [comment]
*nudge nudge*

**Comment by sivasamyk** [comment]
@jchannon In v0.1.23 the host keyword info is not updated dynamically. Can you upgrade to latest logtrail and verify. You can update package.json to you Kibana version using https://github.com/sivasamyk/logtrail/blob/master/docs/how_to.md#2-update-kibanaversion-in-logtrail-plugin-archive

**Comment by jchannon** [comment]
@sivasamyk I thought logtrail was tied to ES versions. We're currently on 6 although I guess I could try 6.2

**Comment by jchannon** [comment]
Updating to 6.2.2 seemed to fix the hostname issue. Thanks.

However adding a new index to ES is not picked up in the index pattern dropdown in logtrail. How can I get indexes to appear there?
