### ISSUE TITLE
Use field in message format and color mapping simultaneously

### ISSUE THREAD

**Issue by Arcansiel** [sivasamyk/logtrail#244]
It can be useful to use a field that is used in color mapping (log level, severity, etc) in message format - for example for quick search by clicking on it. Right now it seems to be impossible.

**Comment by sivasamyk** [comment]
@Arcansiel  message_format can be customized by  in logtrail.json using `"message_format": "{{{log.level}}} : {{{log_message}}}"`. For more info check out : https://github.com/sivasamyk/logtrail/blob/master/docs/add_fields.md

**Comment by Arcansiel** [comment]
Yep, seems to be a problem with my custom format. It works right now.
