### ISSUE TITLE
Error! Exception while fetching hosts : host field not of type keyword or keyword mapping does not exist.

### ISSUE THREAD

**Issue by ceeeekay** [sivasamyk/logtrail#248]
Hi there,

Just installed Logtrail for ES 6.2.2 + Kibana 6.2.2 and am getting the above error.

I'm getting log results, including clickable host names, so the config seems to be doing what it should, but also have this message plastered across the top of the screen.

The mappings for the host field are correct:

```
GET /xxxx-xxxxxxxxx-2018.03.04/_mapping/field/host?pretty
{
  "xxxx-xxxxxxxxx-2018.03.04" : {
    "mappings" : {
      "doc" : {
        "host" : {
          "full_name" : "host",
          "mapping" : {
            "host" : {
              "type" : "keyword"
            }
          }
        }
      }
    }
  }
}
```
logtrail.json
```{
  "version" : 1,
  "index_patterns" : [
    {
      "es": {
        "default_index": "xxxx-xxxxxxxxx-*"
      },
      "tail_interval_in_seconds": 10,
      "es_index_time_offset_in_seconds": 0,
      "display_timezone": "local",
      "display_timestamp_format": "MMM DD HH:mm:ss",
      "max_buckets": 500,
      "default_time_range_in_days" : 0,
      "max_hosts": 100,
      "max_events_to_keep_in_viewer": 5000,
      "fields" : {
        "mapping" : {
            "timestamp" : "@timestamp",
            "hostname" : "host",
            "program": "program",
            "message": "syslog_message"
        },
        "message_format": "{{{source}}} {{{message}}}"
      },
      "color_mapping" : {
      }
    }
  ]
}
```

I'm not sure if the rest of the plugin is behaving correctly as this is my first time using it.

Thanks :)

**Comment by dbason** [comment]
I have also experienced this issue and I'm pretty sure it's because the call to get fields is using CallWithInternalUser (and also it looks up the admin cluster, not the data one).  This should probably use CallWithRequest instead to ensure that the correct permissions are in place.

**Comment by dbason** [comment]
@ceeeekay @FlochonR after some more testing it's definitely what I stated above.  You can resolve this issue by setting up a new user to in Elasticsearch to run the Kibana service, and giving that user Read permission on the index that contains your data.

**Comment by ceeeekay** [comment]
@dbason I see what you're saying but doing this would potentially give other users of Kibana read access to this index, which has terrible security implications and defeats the purpose of having role-based access in Elasticsearch. Kibana should not be trying to read any indices other than its own.

**Comment by dbason** [comment]
The correct fix is for the plugin to use the CallWithRequest function so it operates in the context of the user, this is just a work around.  This shouldn't give additional users access to that index though as their requests are still made with their user context, not that of the user which runs the Kibana server.

**Comment by dbason** [comment]
Just to update the workaround I described worked in 6.1.2 but doesn't seem to work in 6.2.2.

**Comment by sivasamyk** [comment]
Fixed in https://github.com/sivasamyk/logtrail/releases/download/v0.1.27/logtrail-6.2.2-0.1.27.zip

**Comment by ceeeekay** [comment]
WFM - thanks!

**Comment by ceeeekay** [comment]
@sivasamyk - since installing this version of the plugin, hostnames are no longer clickable - `"No events found."` - although entering a Lucene query for the same hostname gives the correct results.  I've done an A/B test between this version and the previous version with the same copy of the config.

**Comment by vlnrajesh** [comment]
We are still facing this issue, please advice

**Comment by saramaliazhar** [comment]
The issue still exists.

**Comment by ceeeekay** [comment]
Upgraded to 6.2.4 from logtrail-6.2.2-0.1.27.zip, and the issue is occurring again.

:(

**Comment by sivasamyk** [comment]
@ceeeekay do you still see this issue in 0.1.28 release?

**Comment by ceeeekay** [comment]
@sivasamyk, all good, as per #275
