### ISSUE TITLE
Show logs in a time range

### ISSUE THREAD

**Issue by chuski92** [sivasamyk/logtrail#249]
Hello, it is possible to show the logs between a time range? i can show the logs in a determinate time with that @timestamp:"2018-03-01T09:23" but I want to show, for example, all the logs between 2018-03-01 - 2018-03-02, is it possible? If not it will be a very helpful addition. 

Thank you.

**Comment by reszelaz** [comment]
Something like this works for me: `@timestamp:["2018-03-01T09:23" TO "2018-03-01T09:25"]`

**Comment by chuski92** [comment]
wow thank you, it works perfectly!
