### ISSUE TITLE
Error on installing plugin

### ISSUE THREAD

**Issue by mvleandro** [sivasamyk/logtrail#25]
Hello!

I am getting this message when trying to install the logtrail plugin on kibnana.

`"Plugin installation was unsuccessful due to error "Incorrect Kibana version in plugin [logtrail]. Expected [5.1.1]; found [5.0.1]""`

The problem is that my kibana version is the required version. See my info:

```
[root@tpb4deves-01 bin]# yum info kibana
Loaded plugins: product-id, search-disabled-repos, subscription-manager
Installed Packages
Name        : kibana
Arch        : x86_64
Version     : 5.1.1
Release     : 1
Size        : 139 M
Repo        : installed
Summary     : Explore and visualize your Elasticsearch data
URL         : https://www.elastic.co
License     : Apache 2.0
Description : Explore and visualize your Elasticsearch data
```
Can someone help me?

**Comment by sivasamyk** [comment]
I assume you are using logtrail version 5.x-0.1.6 from https://github.com/sivasamyk/logtrail/releases/download/0.1.6/logtrail-5.x-0.1.6.zip

**Comment by mvleandro** [comment]
Thank you. 

I've installed the plugin, but i can't see the link to him on my kibana interface. 

![image](https://cloud.githubusercontent.com/assets/363470/21644390/656d5b20-d274-11e6-90cc-a66ff8194098.png)

**Comment by sivasamyk** [comment]
Were there any errors during installation of the plugin? Did you restart Kibana after installation of the plugin? Please paste the installation logs.

**Comment by mvleandro** [comment]
Hello,

I solved! The problema was the plugin directory permissions. After fix, i restarted the kibana service and the plugin worked!

Thank you so much!
