### ISSUE TITLE
Multiple indexes

### ISSUE THREAD

**Issue by jchannon** [sivasamyk/logtrail#256]
Can logtrail cope with multiple indexes in ES?

I have set my logtrail.json to look for fluentd-* but if I then add more indexes eg foo, bar, customera, customerb I don't see the indexes appear in logtrail.

Would I have to edit the default index pattern in logtrail.json to be `*`, issue with that is the field mapping could be different per index.

**Comment by jchannon** [comment]
But does that mean every time a new index is stored in ES, logtrail.json
would need editing and Kibana rebooted?

**Comment by sivasamyk** [comment]
You need to add an entry for each index pattern not index. I assume you don't create index patterns so frequently. e.g `logstash-*` is an index pattern and `logstash-01-01-2018` , `logstash-01-02-2018` are indices belonging to the pattern.

**Comment by jchannon** [comment]
Yup understood but each index would need a reconfiguration and kibana
reboot?

**Comment by sivasamyk** [comment]
Yes.
