### ISSUE TITLE
Case sensitive

### ISSUE THREAD

**Issue by moreiramarti** [sivasamyk/logtrail#257]
Hello,

Dumb question but I'm trying to filter some term with case sensitivity and I don't know how to do.

Can someone help me?

Regards,
Martinho MOREIRA

**Comment by sivasamyk** [comment]
Can you give an example of search string you are trying and sample log data?

**Comment by moreiramarti** [comment]
![image](https://user-images.githubusercontent.com/16536343/37511867-a4f6bc30-2900-11e8-8822-fb0cb481f8d8.png)
Check my screen capture it will be easier.
I just need to search for ERROR case sensitive.

Thanks

**Comment by sivasamyk** [comment]
The default analyzer for the fields converts all text to lower case. If you need case sensitive search you might have to change the analyzer on the message field. Checkout : https://www.elastic.co/guide/en/elasticsearch/reference/current/analyzer.html
