### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by hariram32** [sivasamyk/logtrail#259]
I have downloaded the latest version of Logtrail 

change Kibana version to 6.2.3 zipped back and installed, installation go well, but not able to see plugin in my kibana GUI

root@ES6:~/b# /usr/share/kibana/bin/kibana-plugin install file:///root/b/logtrai
Attempting to transfer from file:///root/b/logtrail-6.2.3-0.1.27.zip
Transferring 1359205 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Extracting plugin archive
Extraction complete
Optimizing and caching browser bundles...

Plugin installation complete

Any suggestions ?

**Comment by hariram32** [comment]
Looks like after restart, i can see the Plugin in Kibana, but not able to tail the logs
getting RED error mesage

Error! Exception while executing search query :[index_not_found_exception] no such index, with { resource.type="index_or_alias" & resource.id="syslog-ng" & index_uuid="_na_" & index="syslog-ng" }


Here is my config

{
  "version" : 1,
        "index_patterns" : [
    {
      "es": {
        "default_index": "syslog-ng",
        "allow_url_parameter": false
      },
      "tail_interval_in_seconds": 10,
      "es_index_time_offset_in_seconds": 0,
      "display_timezone": "Etc/GMT",
      "display_timestamp_format": "MMM DD HH:mm:ss",
      "max_buckets": 500,
      "default_time_range_in_days" : 0,
      "max_hosts": 100,
      "max_events_to_keep_in_viewer": 5000,
      "fields" : {
        "mapping" : {
            "timestamp" : "@timestamp",
            "display_timestamp" : "@timestamp",
            "hostname" : "ES6",
            "program": "program",
            "message": "syslog_message"
        },
        "message_format": "{{{syslog_message}}}"
      },
      "color_mapping" : {
        "field": "level",
        "mapping" : {
          "0": "#ff0000",
          "1": "#ff3232",
          "2": "#ff4c4c",
          "3": "#ff7f24",
          "4": "#ffb90f",
          "5": "#a2cd5a"
        }
      }
    }
  ]
}

**Comment by sivasamyk** [comment]
Can you verify if you have index named `syslog-ng` in your ES cluster?

**Comment by hariram32** [comment]
Thank you for the reply, yes i have syslog-ng, i can view the logs in Kibrana
any further input required let me know, to resolve this issue.

**Comment by hariram32** [comment]
yes x-pack installed and i can see the syslog-ng in kibana GUI, But in logtrail
any further help to fix the issue.

**Comment by sivasamyk** [comment]
Can you check if Logtrail works fine by disabling X-pack? I have not tried logtrail with X-pack.

**Comment by hariram32** [comment]
I have tried removing x-pack and the results same, how do we diagnosis the issue, where the it breaking ?
it simply say in red banner,

Error! Exception while fetching hosts : host field not of type keyword or keyword mapping does not exist.

Some time even i change 

"es": {
        "default_index": "fping-*",
        "allow_url_parameter": false

in settings do not reflect it still show old ES value there.

any assistance appreciate.

**Comment by hariram32** [comment]
Ok, to simulate the problem is my config or Logtrail.

I have pulled all the config as you described in the below URL.
https://github.com/sivasamyk/logtrail-config-examples/tree/master/elasticsearch

Configured same steps as per my setup.

I can see the Logs and index pattern in my Kibana, But in Log Trail

Now i do not see any errors, But i do not see live logs to view in real time ?

Any suggestions here ?

**Comment by hariram32** [comment]
Do you have any input, i have still the same issue ?
