### ISSUE TITLE
Version upgrade Kibana 6.2.3 

### ISSUE THREAD

**Issue by suikast42** [sivasamyk/logtrail#260]
latest build is not installaable for kibana 6.2.3

**Comment by hariram32** [comment]
Download 5.6.5 logtrail plugin from : https://github.com/sivasamyk/logtrail/releases/download/v0.1.23/logtrail-5.6.5-0.1.23.zip
Unzip logtrail-5.6.5-0.1.23.zip
Update the kibana.version to 6.2.3 in package.json file
zip it back.
Install it using following command
kibana-plugin.bat install file://<path-to-local-logtrail.zip file>

**Comment by rajkumar49** [comment]
is this the right solution ?

**Comment by rajkumar49** [comment]
https://github.com/sivasamyk/logtrail/blob/master/docs/how_to.md#1-hostname-field-need-to-be-of-type-keyword  this is the right solution . thanks .

**Comment by sivasamyk** [comment]
You can download Logtrail for 6.2.3 from https://github.com/sivasamyk/logtrail/releases/download/v0.1.27/logtrail-6.2.3-0.1.27.zip
