### ISSUE TITLE
Keep tabulation in message

### ISSUE THREAD

**Issue by moreiramarti** [sivasamyk/logtrail#261]
Hello,

I wonder if it's possible to keep tabulation in start of message field ?
For example with java stack traces.

Here is my logtrail.json conf : 

      "fields" : {
        "mapping" : {
            "timestamp" : "@timestamp",
            "display_timestamp" : "@timestamp",
            "hostname" : "host.keyword",
            "program": "program",
            "message": "message"
        },

Thank you.

**Comment by sivasamyk** [comment]
@moreiramarti Logtrail does preserve the tabs in stacktraces. What is the logtrail version you are using? Can share a screenshot of what you are seeing?

**Comment by moreiramarti** [comment]
Hi @sivasamyk ,

I'm using v0.12.3.
And this my screenshot : 

![image](https://user-images.githubusercontent.com/16536343/38029919-6f83f9fa-3297-11e8-99f9-af93f6f37525.png)

Thanks

**Comment by sivasamyk** [comment]
Looks like each line in the stack trace is  stored as separate document in
elasticsearch. You need to combine the complete stacktrace as single log
event .

**Comment by moreiramarti** [comment]
Ok I will try that 
Thanks you
