### ISSUE TITLE
Installed Logtrail, but don't have "L" button in Kibana menu

### ISSUE THREAD

**Issue by vitalykarasik** [sivasamyk/logtrail#266]
I installed Logtrail on Kibana (Elastic 5.6.3 stack with X-Pack), but haven't received "L" menu in Kibana. 
I don't see any relevant things into Kibana logs.
Any suggestions?
 TIA,
Vitaly

kibana-plugin list
 gauge-sg@5.0.0
 kibana-plugin-line-sg@5.0.0
 kibana-plugin-traffic-sg@5.0.0
 logtrail@0.1.22
 x-pack@5.6.3

**Comment by sivasamyk** [comment]
Did you restart Kibana after installation of Logtrail?

**Comment by vitalykarasik** [comment]
Yes, and I restarted kibana 2nd time  now just to be sure.

**Comment by vitalykarasik** [comment]
I'm curious if there is a way to get list of loaded Kibana plugins?

**Comment by sivasamyk** [comment]
Kibana prints the plugins loaded in server logs. Can you check the Kibana server logs?

**Comment by vitalykarasik** [comment]
Sivasamy, many thanks for your assistance!
And shame on me - I ran kibana-install as root, so Kibana just didn't see this plugin.
