### ISSUE TITLE
color coding for Kibana 5.5.0?

### ISSUE THREAD

**Issue by vgersh99** [sivasamyk/logtrail#268]
Is there's a version of the plugin with color_coding for Kibana 5.5.0? or the color_coding start with 5.6.x only?

**Comment by sivasamyk** [comment]
Color coding support was added in 0.1.21 which is supported in 5.6.0. You can try manually changing the kibana version in package.json of 0.1.21 zip and verify in 5.5.x. For more info checkout : https://github.com/sivasamyk/logtrail/blob/master/docs/how_to.md#2-update-kibanaversion-in-logtrail-plugin-archive
