### ISSUE TITLE
Don't have "Go live" button 

### ISSUE THREAD

**Issue by vitalykarasik** [sivasamyk/logtrail#269]
I'm running Kibana 5.6.3 with X-Pack with logtrail-5.6.3-0.1.22, Chrome 
65.0.3325.181  on OS X.
I do have "Search", "Now", "Setting" buttons, but not "Go Live".
Any ideas?

TIA,
Vitaly

**Comment by sivasamyk** [comment]
If Kibana sidebar is expanded the Live tail button won't be visible. Can you try Collapsing the Kibana side based from lower left corner?

**Comment by vitalykarasik** [comment]
Wow! Many thanks, it was exactly the issue.
Vitaly
