### ISSUE TITLE
Am I missing something in plugin installation procedure?

### ISSUE THREAD

**Issue by Azbests** [sivasamyk/logtrail#272]
Hello,

I have seem to run into installation issue of logtrail plugin.

Steps I followed:
* Downloaded the lograil archive from github
* Unzipped archive, changed version to mach my elasticsearch/kibana installation version in package.json file, repackaged the zip
* Uploaded to server host and installed it from file via "bin/kibana-plugin install file:..." method and by what I can tell the installation was successful. 
* After that I run "chown -R kibana:kibana /path/to/kibana/optimize" as I have run previous command from root.
* After kibana service restart I do not see lograil menu in gui.

In kibana logs all that I see related to logtrail is:
`Apr 26 14:00:40 elk kibana[6718]: {"type":"log","@timestamp":"2018-04-26T11:00:40Z","tags":["plugin","warning"],"pid":6718,"path":"/usr/share/kibana/plugins/logtrail","message":"Skipping non-plugin directory at /usr/share/kibana/plugins/logtrail"}`

Any clues to where I should look for the problem?

**Comment by sivasamyk** [comment]
What is the Kibana version you are using?

**Comment by Azbests** [comment]
Whole stack is v6.2.4

**Comment by sivasamyk** [comment]
@Azbests Released and verified a new version for 6.2.4 at https://github.com/sivasamyk/logtrail/releases/download/v0.1.27/logtrail-6.2.4-0.1.27.zip. 

Your steps to update version looks fine although I am not aware of `chown` command to change the owner.  Let me know if the above zip works.

**Comment by Azbests** [comment]
It looks like everything is working correctly now with your updated package. 

Also thanks for the nice plugin for ELK. This is perfect if you want to browse logs in a bit more classic look of syslog. :)

**Comment by sivasamyk** [comment]
Great! Thanks for your kind words. Happy logging!
