### ISSUE TITLE
Oldest log printed

### ISSUE THREAD

**Issue by moreiramarti** [sivasamyk/logtrail#273]
Hello,

Since I upgrade my elasticsearch from 6.0.0 to 6.2.3 when I go to logtrail I saw the oldest log of my index instead of the last (I'm using logtail v0.1.27)
.
It seems to be ok when I hit ctrl + F5 but I don't understand what is my issue?

Can it be related to a performance issue or something?

Thanks,
Martinho MOREIRA

**Comment by sivasamyk** [comment]
Can you get the logs printed on chrome debug console when you open logtrail for the first time? It should print the query sent to the server. Make sure the debug level is enabled in chrome debug console.

**Comment by sivasamyk** [comment]
Closing this issue. Please reopen if you are still facing this issue with the above logs.
