### ISSUE TITLE
searching does not work , as query using the wrong field names

### ISSUE THREAD

**Issue by nak2000** [sivasamyk/logtrail#276]
Search is not working for us in 6.2.4

we have our field mappings as below
"fields" : {
        "mapping" : {
            "timestamp" : "@timestamp",
            "hostname" : "Host.Hostname",
            "program": "DeepHealth.ApplicationName",
            "message": "DeepHealth.OverallDeepHealthStatusDesc"
        }

now when we search, the query going out is
{"searchText":"*","timestamp":null,"rangeType":"gte","order":"asc","**host**":"xxxxxx","index":"my-index-*"}

instead of

{"searchText":"*","timestamp":null,"rangeType":"gte","order":"asc","**Host.Hostname**":"xxxxxx","index":"my-index-*"}

the reason for this is that in your api, you are not reverse mapping to the original field names as supplied in the mapping.

**Comment by nak2000** [comment]
just to add to above, this applies to the HOST dropdown,

**Comment by P1llus** [comment]
Might be just me, as it has been some time, but is this not set in the logtrail.json config file?

`"version" : 1, "index_patterns" : [ { "es": { "default_index": "filebeat-*" }, "tail_interval_in_seconds": 10, "es_index_time_offset_in_seconds":0, "display_timezone": "local", "display_timestamp_format": "MMM DD HH:mm:ss", "max_buckets": 500, "default_time_range_in_days" : 0, "max_hosts": 100, "max_events_to_keep_in_viewer": 5000, "fields" : { "mapping" : { "timestamp" : "@timestamp", **"hostname" : "host",** "message": "message" }, "message_format": "{{{message}}}" }, "color_mapping" : { } }, { "es": { "default_index": "logstash-zookeeper" }, "tail_interval_in_seconds": 10, "es_index_time_offset_in_seconds": 0, "display_timezone": "local", "display_timestamp_format": "MMM DD HH:mm:ss", "max_buckets": 500, "default_time_range_in_days" : 0, "max_hosts": 100, "max_events_to_keep_in_viewer": 5000, "fields" : { "mapping" : { "timestamp" : "@timestamp", "hostname" : "host", "program": "logger_name", "message": "log_message" }, "message_format": "{{{log_message}}}" }, "color_mapping" : { } } ] }`

**Comment by sivasamyk** [comment]
@nak2000 Are you still facing this issue?

**Comment by sivasamyk** [comment]
Closing the issue. Please reopen if you are still facing this issue.
