### ISSUE TITLE
Modify index.html

### ISSUE THREAD

**Issue by chuski92** [sivasamyk/logtrail#279]
Hello,
How can I modify the public/index.html file to change the default placeholder to another?
Because I had modified it but it has no effect after reloading kibana.

**Comment by sivasamyk** [comment]
Can you try this? - Download load the plugin zip, modify the index.html, zip it back and install the updated zip. Not sure what do you mean by `change the default placeholder to another`

**Comment by chuski92** [comment]
It gives me that error:

Retrieving metadata from plugin archive
Error: end of central directory record signature not found
    at /usr/share/kibana/node_modules/yauzl/index.js:179:14
    at /usr/share/kibana/node_modules/yauzl/index.js:539:5
    at /usr/share/kibana/node_modules/fd-slicer/index.js:32:7
    at FSReqWrap.wrapper [as oncomplete] (fs.js:683:17)
Plugin installation was unsuccessful due to error "Error retrieving metadata from plugin archive"

**Comment by sivasamyk** [comment]
@chuski92 I tried following steps and it worked:
1) Shutdown Kibana
2) Uninstall existing logtrail installation from Kibana using `./kibana-plugin remove logtrail`
3) Download the plugin zip from github.com and extract
4) Extract the zip and make changes in CSS/index.html
5) Zip the contents back using `zip -r logtrail-xxx.zip kibana` from the extracted dir
6) Install the plugin using `kibana-plugin install file:///<path to newly created logtrail-xxx.zip>`
7) Start Kibana

**Comment by chuski92** [comment]
Thank you for your help!
It gives me that error:
Attempting to transfer from file:///tmp/logtrail-master.zip
Transferring 310729 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Plugin installation was unsuccessful due to error "No kibana plugins found in archive"

**Comment by sivasamyk** [comment]
@chuski92 Looks like you downloaded the logtrail source from master branch for editing. You need to download the plugin release zip from https://github.com/sivasamyk/logtrail/releases (based on your kibana version) and follows the above steps.

**Comment by chuski92** [comment]
It works! 
Thank you very much!
