### ISSUE TITLE
Refreshing stops after a while

### ISSUE THREAD

**Issue by C0rn3j** [sivasamyk/logtrail#28]
If I leave a LogTrail window open and go back at forth it will stop refreshing(won't show new logs) at some point(few minutes spent in another tab seem to be enough).

Elastic stack 5.1.1, and the browser is Firefox 50.1.

Let me know if you need any more information

**Comment by sivasamyk** [comment]
Can you please let me know if you see any exception or logs in Javascript debug console?

**Comment by C0rn3j** [comment]
Nothing, starts with `connection to elasticsearch successful` when I launch the page and nothing else ever gets logged into it.

**Comment by sivasamyk** [comment]
@C0rn3j Are you still seeing this issue?

**Comment by C0rn3j** [comment]
I don't have a test machine setup atm, so I'll either have to set one up or wait for our prod to catch up to ES 5.3.0 and retest.

I'll get back to you when that happens.

**Comment by C0rn3j** [comment]
Updated to 5.3.0 and latest logtrail and I can't seem to reproduce the problem again, so I'm closing this issue.
