### ISSUE TITLE
Changing CSS does not take any effect

### ISSUE THREAD

**Issue by Teressss** [sivasamyk/logtrail#281]
Hi, when I change any color in main.css located in /usr/share/kibana/plugins/logtrail/public/css/, after restarting kibana or whole server nothing happend. When I change colors stupidly from black, white etc. to for example PINK = still the same, no effect change, colors are still at some defaults.

**Comment by chuski92** [comment]
I think is the same issue that happens to me, sivasamyk tells me to download plugin zip, modify it, repack the plugin and then reinstall it to have the changes to take effect, but it doesn't work for me, but you can try if it works for you.

**Comment by sivasamyk** [comment]
@Teressss Since kibana optimize the plugin source during installation, any changes of plugin install location won't work. Checkout the steps mentioned here https://github.com/sivasamyk/logtrail/issues/279#issuecomment-394218654 on how to make changes to plugin zip.

**Comment by Teressss** [comment]
Thanks. Little complicated, but finally that worked.

**Comment by jemijin** [comment]
> @Teressss Since kibana optimize the plugin source during installation, any changes of plugin install location won't work. Checkout the steps mentioned here [#279 (comment)](https://github.com/sivasamyk/logtrail/issues/279#issuecomment-394218654) on how to make changes to plugin zip.

You can change the css in ${kibana}/optimize/bundles/logtrail.style.css.
