### ISSUE TITLE
Build release for 6.3.0

### ISSUE THREAD

**Issue by Evesy** [sivasamyk/logtrail#283]
Hi,

Would it be possible to build a release for 6.3.0 (https://www.elastic.co/blog/kibana-6-3-0-released)?

Cheers,
Mike

**Comment by hariram32** [comment]
Siva

looking forward to test, as the last version not worked for me, still struggle to get tail output from the logs in real time

**Comment by P1llus** [comment]
I will also be available to test, holding the upgrade back a bit, as this plugin is just awesome for us :)

**Comment by hariram32** [comment]
is there any time line to release this new version,

P1llus - is the old version working for you ?

**Comment by sivasamyk** [comment]
Download the latest release for 6.3.0 from https://github.com/sivasamyk/logtrail/releases/download/v0.1.27/logtrail-6.3.0-0.1.27.zip

@hariram32 https://github.com/sivasamyk/logtrail/blob/master/logtrail.json, the config in this file for filebeat works fine for me.
