### ISSUE TITLE
.keyword - configurable?

### ISSUE THREAD

**Issue by fenneh** [sivasamyk/logtrail#285]
Hey,

I'm wondering if instead of forcing people to use the `.keyword` field, if this can be configurable for the unanalyzed fields, either as a direct replacement or even better, to be an array of acceptable suffixes e.g. .raw,.keyword ? 

The reason for this is if you've been upgrading ELK since the early days there's a good chance you'll be using `.raw` fields and have persisted to do so.

Which would mean to use logtrail all saved searches, visualizations and dashboards would need to be updated to use .keyword as opposed to whatever suffix is in use.

**Comment by sivasamyk** [comment]
Introduced `keyword_suffix` parameter in logtrail.json in 0.1.28 release. Checkout https://github.com/sivasamyk/logtrail/releases/download/v0.1.28/logtrail-6.3.0-0.1.28.zip

Specifies the keyword suffix to be appended for hostname & program fields. Set it to "" to not append any suffix.By default set to keyword. If not specified ( undefined) logtrail will append .keyword for backward compatibility.

**Comment by fenneh** [comment]
Awesome - going to test this out right now.

**Comment by fenneh** [comment]
Works perfectly. Thanks @sivasamyk
