### ISSUE TITLE
error: venture field not of type keyword or keyword mapping does not exist.

### ISSUE THREAD

**Issue by danielmotaleite** [sivasamyk/logtrail#286]
Hi
My indexes are not completely standard, i removed several .keyworkd fields and forced the main name to be not  analyzed (ie: like the .keyword), but logtrail insist to use the .keyword. To workaround this i then created for some key fields (venture and environment) a .keyword field, just to make logtrail happy... and it mostly works, except this error that happens mostly when i enter logtrail for the first time

`Error! Exception while fetching hosts : venture field not of type keyword or keyword mapping does not exist. `

Not only venture is type keyword, but venture.keyword also exist and have the same type... so i'm a bit confused about this.

I do not want to make the venture a normal analyzed field as i already have many dashboards, healthchecks and visualizations using it

Usually if i reload the page again, it will not complain anymore and everything works

My logtrail config is like this:
```
{
              "es": {
                "default_index": "logstash-*",
                "allow_url_parameter": false
              },
              "tail_interval_in_seconds": 10,
              "max_buckets": 500,
              "max_events_to_keep_in_viewer": 5000,
              "nested_objects": false,
              "display_timestamp_format": "MMM DD HH:mm:ss",
              "es_index_time_offset_in_seconds": 0,
              "display_timezone": "local",
              "default_time_range_in_days": 1,
              "fields": {
                "mapping": {
                  "timestamp": "@timestamp",
                  "display_timestamp": "@timestamp",
                  "hostname": "venture",
                  "program": "environment",
                  "message": "message"
                },
                "message_format": "{{{message}}}"
              },
              "color_mapping": {
                "field": "level",
                "mapping": {
                  "ERROR": "#FF0000",
                  "WARN": "#FFEEAD",
                  "WARNING": "#FFEEAD",
                  "DEBUG": "#B5E7A0",
                  "TRACE": "#CFE0E8"
                }
              },
              "field": "response",
              "mapping": {
                "200": "#B5E7A0",
                "301": "#CFE0E8",
                "302": "#CFE0E8",
                "304": "#CFE0E8",
                "400": "#EEAC99",
                "401": "#622569",
                "403": "#622569",
                "404": "#EEAC99",
                "500": "#FF0000",
                "502": "#FFEF96",
                "503": "#FF0000",
                "504": "#FFEF96"
              }
            },
```

so any hint how to fix this is more than welcome...

i again have to suggest like #285 and #20, that logtrail should use what the user configure and not automatically add any .keyword, but the `use_raw_fields` option was never added ... maybe adding that now solves this?

Thanks for logtrail

**Comment by sivasamyk** [comment]
@danielmotaleite added `keyword_suffix` field in logtrail.json to specify the suffix to append for keyword fields. Set it to `""` to not append any values. Checkout the new release at https://github.com/sivasamyk/logtrail/releases/download/v0.1.28/logtrail-6.3.0-0.1.28.zip

**Comment by sivasamyk** [comment]
@danielmotaleite in your case you need to set the `keyword_suffix` parameter in logtrail.json to `""`, so that logtrail does not append `.keyword` to the host field.
