### ISSUE TITLE
Color mappings not working

### ISSUE THREAD

**Issue by hariram32** [sivasamyk/logtrail#290]
My config looks like below

 "color_mapping" : {
        "field": "log_level",
        "mapping" : {
          "ERROR": "#ff0000",
          "WARN": "#ff0000",
          "DEBUG": "#ff0000",
          "TRACE": "#ff0000"

===

Jul 01 07:06:27 ES6 :  Jul  1 07:06:27 R2 005269: %OSPF-4-CFG_NBR_INVALID_NET_TYPE: Can not use configured neighbor 10.10.10.1 on Ethernet0/0. Neighbor command only allowed on NBMA and P2MP networks
Jul 01 07:06:45 ES6 :  Jul  1 07:06:45 R2 005270: %SYS-5-CONFIG_I: Configured from console by console
Jul 01 09:40:33 ES6 :  Jul  1 09:40:32 R2 005271: %SYS-5-PRIV_AUTH_PASS: Privilege level set to 15 by unknown on console
Jul 01 09:42:31 ES6 :  Jul  1 09:42:31 R2 005272: %SYS-5-CONFIG_I: Configured from console by console
Jul 01 09:43:15 ES6 :  Jul  1 09:43:14 R2 005273: %SYS-5-CONFIG_I: Configured from console by console
Jul 01 10:25:18 ES6 :  Jul  1 10:25:18 R2 005274: %SYS-5-PRIV_AUTH_PASS: Privilege level set to 15 by unknown on console

i do not see any coloring, apart from ES6 and : different colors

how can i make different coloring display ?

R!

**Comment by sivasamyk** [comment]
Do you have a `log_level` field in your ES document? Can you paste a sample ES document for your logs?

**Comment by hariram32** [comment]
here is example of json output.

{
  "_index": "logstash-syslog",
  "_type": "doc",
  "_id": "mKUpVWQB4DAKHTXyLIs0",
  "_version": 1,
  "_score": null,
  "_source": {
    "@timestamp": "2018-07-01T09:25:18.923Z",
    "path": "/var/syslog-ng/raw/alldevice.log",
    "type": "logstash-syslog",
    "@version": "1",
    "message": "Jul  1 10:25:18 R2 005274: %SYS-5-PRIV_AUTH_PASS: Privilege level set to 15 by unknown on console",
    "log_level": 0,
    "host": "ES6",
    "tags": [
      "logstash-syslog",
      "_grokparsefailure"
    ]
  },
  "fields": {
    "@timestamp": [
      "2018-07-01T09:25:18.923Z"
    ]
  },
  "sort": [
    1530437118923
  ]
}

**Comment by sivasamyk** [comment]
@hariram32 Looks like your log-level values are integers and you have mapped strings (ERROR,DEBUG) to color values. The color mapping should be like

```
"mapping" : {
          "0": "#ff0000",
          "1": "#ff3232",
          "2": "#ff4c4c",
          "3": "#ff7f24",
          "4": "#ffb90f",
          "5": "#a2cd5a"
        }
```
