### ISSUE TITLE
ES performance issue while using logtrail

### ISSUE THREAD

**Issue by sergeyarl** [sivasamyk/logtrail#295]
Hi! 

Not sure if this is the right place to post this question. So please forgive me if it isn't :)

Some time back when we first introduced ES/Kibana/Logtrail in our infrastructure for log management, we had a huge performance issues while using Logtrail. When I opened Logtrail, first refresh always  caused huge IO waits on ES server. After that all further refreshes were rather fast + no IO waits. 

I changed  **default_time_range_in_days** parameter in logtrail config from 0 (default value) to 1. And right after that we no longer had any performance issues. Everything worked like a charm. 

Anyway, the amount of logs that we receive daily grows bigger and bigger. And now we sometimes see, that even with **default_time_range_in_days=1** first refresh in Logtrail window causes high IO waits on ES node. 

So my question is, probably there is a way to specify the default search period (default_time_range_in_days) equal to 15 minutes, as it is for **discover** page in Kibana ? 

Thanks! 

Regards,
Sergey

**Comment by sivasamyk** [comment]
Will add an option to specify the time range in minutes in next release.

**Comment by sivasamyk** [comment]
Added new conf field in logtrail.json - `default_time_range_in_minutes`. when specified this will be used instead of `default_time_range_in_days`. `default_time_range_in_minutes` is not yet documented. Please note default search will show results only from `default_time_range_in_minutes`

**Comment by sergeyarl** [comment]
@sivasamyk Thank you!

**Comment by sergeyarl** [comment]
@sivasamyk Download link is not working, can you please check?

**Comment by sergeyarl** [comment]
Ah, I'm sorry, I found a correct one on releases page.

**Comment by sivasamyk** [comment]
np. I changed the download URL after release.
