### ISSUE TITLE
Auth error 

### ISSUE THREAD

**Issue by lacion** [sivasamyk/logtrail#3]
im trying to run this against an elasticsearch sever protected by SearchGuard though i think having it in front of a nginx proxy with auth would cause the same problem.

{ [Error: Unauthorized]
  data: null,
  isBoom: true,
  isServer: false,
  output:
   { statusCode: 401,
     payload:
      { statusCode: 401,
        error: 'Unauthorized',
        message: 'Unauthorized',
        attributes: [Object] },
     headers: { 'WWW-Authenticate': 'Basic realm="shield", error="Unauthorized"' } },
  reformat: [Function] }
{"type":"response","@timestamp":"2016-09-15T21:48:47+00:00","tags":[],"pid":12,"method":"post","statusCode":200,"req":{"url":"/logtrail/search","method":"post","headers":{"host":"xxxxxx","content-type":"application/json;charset=UTF-8","origin":"http://xxxxx","content-length":"83","connection":"keep-alive","kbn-version":"4.5.4","accept":"application/json, text/plain, */*","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/601.7.8 (KHTML, like Gecko) Version/9.1.3 Safari/601.7.8","referer":"http://xxxxxx/app/logtrail","accept-language":"en-us","accept-encoding":"gzip, deflate"},"remoteAddress":"10.128.0.3","userAgent":"10.128.0.3","referer":"http://xxxxx/app/logtrail"},"res":{"statusCode":200,"responseTime":143,"contentLength":9},"message":"POST /logtrail/search 200 143ms - 9.0B"}

is there a way to define logtrail with auth ?

**Comment by sivasamyk** [comment]
@lacion thanks for trying out the plugin. I have not tested logtrail with Safegaurd/Shield protected ES instance. Logtrail uses the elasticsearch API provided by Kibana to talk to ES instance. I assume your Kibana queries are working fine. Will test and let you know.

**Comment by sivasamyk** [comment]
Initial analysis shows the Authorization request headers (HTTP Basic Auth credentials) are not sent as part of logtrail http requests.

**Comment by sivasamyk** [comment]
fixed . Please install latest release and let me know if it works!

`./bin/kibana plugin -i logtrail -u https://github.com/sivasamyk/logtrail/releases/download/v4.x-0.1.1/logtrail-4.x-0.1.1.tar.gz`

**Comment by lacion** [comment]
finally got arround to testing this, yes sire this is now working.

**Comment by lacion** [comment]
i am having a small batch of issues, but is mostly because i am running a custom index, that does not resembles logstash at all. i cant use the search bar on logtrail, im going to debug a little bit and come back with the findings.

great project you have here.
