### ISSUE TITLE
TCP input doesn't work with rsyslog

### ISSUE THREAD

**Issue by C0rn3j** [sivasamyk/logtrail#30]
From what I've read, rsyslog should use TCP by default and it seems to have an UDP fallback?

http://pastebin.com/EctYZjCe

Here's a logstash log of 2 startups. First startup there is only TCP enabled, and you can see
```    
Starting tcp input listener {:address=>"0.0.0.0:5000"}
```
However ES seemingly never receives anything.
Second startup is both TCP and UDP enabled, you can see
```
    Starting tcp input listener {:address=>"0.0.0.0:5000"}
    Starting UDP listener {:address=>"0.0.0.0:5000"}
    UDP listener started {:address=>"0.0.0.0:5000", :receive_buffer_bytes=>"106496", :queue_size=>"2000"}
```
This works. 

Comparing these 2 logs makes me think that the TCP listener never gets started?

Not sure if this is a logstash issue, or a logtrail example config issue, or something else.

Using LXC container(Ubuntu 16.04) with OpenJDK and Elastic Stack 5.1.1

**Comment by sivasamyk** [comment]
In the /etc/rsyslog.conf while configuring syslog server endpoints specifying '@' before the hostname will use UDP. If you specify '@@' before hostname, it will use TCP. So if you change the rsyslog.conf from `*.*     @localhost:5000` to `*.*     @@localhost:5000`, then syslog events will sent using TCP. I tested the same. Please check http://www.rsyslog.com/doc/rsyslog_conf_examples.html for more info

**Comment by C0rn3j** [comment]
That explains a lot, it now works, thank you!
