### ISSUE TITLE
Defined X index_patterns, but still logs are not updating when selecting from Settings -> index pattern

### ISSUE THREAD

**Issue by remi-bast** [sivasamyk/logtrail#301]
Hi,

I have configured FileBeat -> LogStash -> Elasticsearch <- Kibana + Logtrail.

FileBeat collects logs from different projects. Logtash strucutres these logs and split them into different indexes by project & week using following output: index => "logs-%{project}-%{+YYYY}w%{+ww}"

Above is working fine and the documents are stored in the right index.

My goal then is to be able to view from Kibana logtrail the logs for a specific project. So I have configured several index_patterns in logtrail.json. For example:
*  "default_index": "logs-projectA-*", 
*  "default_index": "logs-projectB-*", 
etc.

In the UI of Kibana logTrail, under Settings, I can see in the drop down my different index pattern:  logs-projectA-*, logs-projectB-*, etc.

Problem: when selecting logs-projectB-*, I am not getting the logs of my projectB. It still shows the logs of logs-projectA-* that was initially selected.

Am I doing something wrong?

Note: it works fine when changing the i parameter in the URL: http://localhost:5601/app/logtrail#/?q=*&h=All&t=Now&i=logs-projectB-*&_g=()

Apparently, the dropdown selection is not used correctly?

**Comment by sivasamyk** [comment]
Hi @remi-bast 

- What is the version of Kibana & Logtrail you have installed?
- when you change the dropdown does the URL change?
- Can you check in the browser debug console, the search query sent from logtrail?

**Comment by remi-bast** [comment]
Hi sivasamyk,

I have Kibana version 6.3.2: kibana-6.3.2-windows-x86_64
I have installed Logtrail using: ./bin/kibana-plugin install https://github.com/sivasamyk/logtrail/releases/download/v0.1.29/logtrail-6.3.2-0.1.29.zip
Inside kibana-6.3.2-windows-x86_64\plugins\logtrail\package.json, it shows below information, so version 0.1.29 isntalled:
  "name": "logtrail",
  "version": "0.1.29",
  "description": "Plugin to view, search & tail logs in Kibana",
  "main": "index.js",
  "kibana": {
    "version": "6.3.2"
  }

When I select a new value in the dropdown, the URL does not change. The settings popup even does not close. When I click search, the popup closes, but the URL does not change.

From debug console, the search query is still using non selected index.

In below screenshot, I have selected logs-default-*, but still querying log-zainirq-* that was used by default.

![image](https://user-images.githubusercontent.com/38810070/43999750-bc007d56-9e3c-11e8-800d-740329186e7f.png)

**Comment by sivasamyk** [comment]
Looks like you are using Windows OS. Which browser are you using?

**Comment by remi-bast** [comment]
Yes, using Windows 10 Pro - 64 bits.

I tried with different browsers but same behaviour:
* IE 11
* Chrome Version 68.0.3440.106
* Firefox Quantum 61.0.1
* Opera 54

**Comment by sivasamyk** [comment]
Can you share the full screenshot of the settings popup? There should be `Ok` button in settings popup. Clicking the OK button will change the selected index pattern.
