### ISSUE TITLE
I can't fetch any rows on some index

### ISSUE THREAD

**Issue by alantany** [sivasamyk/logtrail#305]
Hi,sivasamyk
I config five index in the logtrail.json,but one index can not fetch any rows,I am sure it has rows in the time gap,I can get rows from kibana-discover .
index mapping:
`{
  "oracle_syslog-2018-08-17": {
    "aliases": {},
    "mappings": {
      "doc": {
        "properties": {
          "@timestamp": {
            "type": "date"
          },
          "@version": {
            "type": "text",
            "fields": {
              "keyword": {
                "type": "keyword",
                "ignore_above": 256
              }
            }
          },
          "beat": {
            "properties": {
              "hostname": {
                "type": "text",
                "fields": {
                  "keyword": {
                    "type": "keyword",
                    "ignore_above": 256
                  }
                }
              },
              "name": {
                "type": "text",
                "fields": {
                  "keyword": {
                    "type": "keyword",
                    "ignore_above": 256
                  }
                }
              },
              "version": {
                "type": "text",
                "fields": {
                  "keyword": {
                    "type": "keyword",
                    "ignore_above": 256
                  }
                }
              }
            }
          },
          "error_type": {
            "type": "text",
            "fields": {
              "keyword": {
                "type": "keyword",
                "ignore_above": 256
              }
            }
          },
          "host": {
            "type": "text",
            "fields": {
              "keyword": {
                "type": "keyword",
                "ignore_above": 256
              }
            }
          },
          "offset": {
            "type": "long"
          },
          "prospector": {
            "properties": {
              "type": {
                "type": "text",
                "fields": {
                  "keyword": {
                    "type": "keyword",
                    "ignore_above": 256
                  }
                }
              }
            }
          },
          "source": {
            "type": "text",
            "fields": {
              "keyword": {
                "type": "keyword",
                "ignore_above": 256
              }
            }
          },
          "system": {
            "properties": {
              "syslog": {
                "properties": {
                  "hostname": {
                    "type": "text",
                    "fields": {
                      "keyword": {
                        "type": "keyword",
                        "ignore_above": 256
                      }
                    }
                  },
                  "message": {
                    "type": "text",
                    "fields": {
                      "keyword": {
                        "type": "keyword",
                        "ignore_above": 256
                      }
                    }
                  },
                  "pid": {
                    "type": "text",
                    "fields": {
                      "keyword": {
                        "type": "keyword",
                        "ignore_above": 256
                      }
                    }
                  },
                  "program": {
                    "type": "text",
                    "fields": {
                      "keyword": {
                        "type": "keyword",
                        "ignore_above": 256
                      }
                    }
                  },
                  "timestamp": {
                    "type": "text",
                    "fields": {
                      "keyword": {
                        "type": "keyword",
                        "ignore_above": 256
                      }
                    }
                  }
                }
              }
            }
          },
          "tags": {
            "type": "text",
            "fields": {
              "keyword": {
                "type": "keyword",
                "ignore_above": 256
              }
            }
          }
        }
      }
    },
    "settings": {
      "index": {
        "creation_date": "1534464006639",
        "number_of_shards": "5",
        "number_of_replicas": "1",
        "uuid": "cKhO3xaUQYiaHXa6sAWwIg",
        "version": {
          "created": "6030099"
        },
        "provided_name": "oracle_syslog-2018-08-17"
      }
    }
  }
}`

logtrail configuration:
`      "es": {
        "default_index": "oracle_syslog*"
      },
      "tail_interval_in_seconds": 10,
      "es_index_time_offset_in_seconds": 0,
      "display_timezone": "local",
      "display_timestamp_format": "MMM DD HH:mm:ss",
      "max_buckets": 500,
      "default_time_range_in_days" : 0,
      "default_time_range_in_minutes" : 0,
      "max_hosts": 100,
      "max_events_to_keep_in_viewer": 5000,
      "default_search": "",
      "fields" : {
        "mapping" : {
            "timestamp" : "@timestamp",
            "hostname" : "beat.hostname",
            "message": "message"
        },
        "message_format": "{{{ message }}}",
        "keyword_suffix" : "keyword"
      },
      "color_mapping" : {
      }
    },`

![image](https://user-images.githubusercontent.com/26447990/44265857-e9ea4180-a25a-11e8-8317-0c3a59bd1620.png)
![image](https://user-images.githubusercontent.com/26447990/44265868-fcfd1180-a25a-11e8-8989-48199627602f.png)

Thank you!

**Comment by sivasamyk** [comment]
Can you check the name of the message field? Form logtrail.json I see you have mapped `message`, in kibana UI I see `system.syslog.message`

**Comment by alantany** [comment]
Hi,sivasamyk
I am sorry it's my mistake ,I type a wrong message name
I have a question:
Why can not get index_name list  from es like the way kibana discover do? so that we need'nt config the logtrail.json ,we have nearly over 300 indexes in es,I can't imagine how to config it use logtrail.json 

Thank you!

**Comment by sivasamyk** [comment]
The logtrail configuration is specific for each index pattern (like mapping etc). It cannot be done automatically by reading from ES. It needs user input. There are plans to develop a UI configure logtrail, but not in near-term :)

**Comment by alantany** [comment]
Thank you!
