### ISSUE TITLE
RouterOS 6.37.1  bsd-syslog parse failure

### ISSUE THREAD

**Issue by C0rn3j** [sivasamyk/logtrail#31]
Hi! I've added a mikrotik device syslog(UDP) but only grok_parsefailures end up in Kibana.

http://i.imgur.com/mKVyOnm.png

I've tried looking into /var/log/logstash/ but the logs in there say nothing about such failures, nothing in journalctl -xe either.

How can I possibly provide some usable info for you? I've no idea how to get the whole log message that's being sent to logstash so I could post it here.

My other devices that forward rsyslog logs work great.

My logstash.conf, it's just like the example conf. http://i.imgur.com/OdWTeEg.png

**Comment by sivasamyk** [comment]
Looks like the syslog event format sent by these devices are in different format. Can enable debug output in your logstash conf to print the actual message received:

`output {
  stdout { codec => rubydebug }
}`

Else you can use syslog input instead of tcp to parse the events. Please note in this case you might need to customize logtrail.json to map fields appropriately. https://www.elastic.co/guide/en/logstash/current/plugins-inputs-syslog.html

**Comment by C0rn3j** [comment]
http://pastebin.com/pWFkR2KE

I've enabled the output to stdout which gets me this when I do `systemctl status logstash`, is this any helpful for you?

**Comment by sivasamyk** [comment]
Looks like the syslog message does not match the pattern specified in logstash conf. I see that it does not have program field. This pattern should work : `%{SYSLOGTIMESTAMP:syslog_timestamp} %{SYSLOGHOST:hostname} %{GREEDYDATA:syslog_message}`. You can use this pattern for logs from these routers.

**Comment by C0rn3j** [comment]
Thanks, do I just add another 'match' line in grok? 

If yes, could you add it to the readme so other people don't run into this issue? ^^

**Comment by sivasamyk** [comment]
You can check this blog on handling varying syslog format in logstash: https://kartar.net/2014/09/when-logstash-and-syslog-go-wrong/

There a various syslog format available. The readme just gives an example configuration. I don't think adding this specific Mikrotik syslog format will help.

**Comment by C0rn3j** [comment]
While I'd welcome just adding it to the default config, would it be possible to maintain a separate config file with examples for various devices if some differ and break the default grok filter? ^^

Also, adding it worked for me, the other servers are just using the correct time but the Mikrotik device is a few minutes forward, which skews the log view.

I believe that when this happens LogTrail stops tailing the older logs, and shows just the ones with newer timestamp?

**Comment by sivasamyk** [comment]
Added new repo to collect logtrail + logstash config examples at https://github.com/sivasamyk/logtrail-config-examples

Regarding the timestamp issue, adding date filter in logstash config, will by default add `@timestamp` field to event which is based on the event receive time in logstash. Mapping this field to timestamp in logtrail.json should display the entries properly.
