### ISSUE TITLE
Release link for 6.4.0

### ISSUE THREAD

**Issue by lpic10** [sivasamyk/logtrail#310]
Just noticed (due to automated build) the link for downloading the release for 6.4.0 is different than usual:

https://github.com/sivasamyk/logtrail/releases/download/v0.1.29/logtrail-6-4.0-0.1.29.zip
vs.
https://github.com/sivasamyk/logtrail/releases/download/v0.1.29/logtrail-6.4.0-0.1.29.zip

**Comment by sivasamyk** [comment]
Thanks for catching it. Fixed the link.
