### ISSUE TITLE
Error messages do not disappear

### ISSUE THREAD

**Issue by ZhaoBaymax** [sivasamyk/logtrail#311]
hi , 
   When I make an error query, an error message pops up, and then I make a correct query again, the error message always exist
   
![before](https://user-images.githubusercontent.com/28599497/44970275-6f703000-af83-11e8-93bb-d1dafe43eb8b.png)

![2018-09-03_140707](https://user-images.githubusercontent.com/28599497/44970283-76973e00-af83-11e8-8202-74ce550e0ab3.png)

**Comment by sivasamyk** [comment]
Fixed in latest release at https://github.com/sivasamyk/logtrail/releases/download/v6.4.0_0.1.30/logtrail-6.4.0-0.1.30.zip
