### ISSUE TITLE
Lines appearing out of order with filebeat

### ISSUE THREAD

**Issue by apoland** [sivasamyk/logtrail#318]
Using filebeat agent to push log messages to a kubernetes load balanced ES 6.3.1 cluster.  Frequently we see adjacent lines posted to ES with the exact same timestamp, down to the maximum resolution of one millisecond.  This causes them to appear randomly in the wrong order when queried within logtrail.  (See lines 5 & 6 of this screenshot for an example set of rows that trigger the problem)

![screen shot 2018-10-02 at 5 01 55 pm](https://user-images.githubusercontent.com/3091714/46376810-fab51200-c664-11e8-856d-c51d0dd6b502.png)

It looks like filebeat sends a separate field for "offset" which refers to the byte offset in the original log file.  When we patched Logtrail to include "offset" as a secondary sort field the problem goes away:

https://github.com/DemandJump/logtrail/compare/e8dc741e3cd92be975370bd3266ad387cd1b5b9f...DemandJump:ce1a026e590be1fb19a3e9c92697a237f15e78aa

Would it be useful to generalize this into a config option so users could specify the name of an optional secondary sort field?  If so I can submit as a PR.

**Comment by sivasamyk** [comment]
@apoland Sure, this would be useful. Please submit a PR. Thanks!
