### ISSUE TITLE
ANSI colors / escape sequences

### ISSUE THREAD

**Issue by rmoriz** [sivasamyk/logtrail#322]
Some of our log files capture colorized outputs, sadly logtrail/kibana won't display them and shows escape sequences instead.

There are[ tools to strip the sequences](https://github.com/sabre1041/kibana-ansi), but actually I would like to see them interpreted (afaik like papertrail)

**Comment by sivasamyk** [comment]
@rmoriz This PR https://github.com/sivasamyk/logtrail/pull/264/files added ANSI HTML support in logtrail. Can you let me know the logtrail version you are running?

**Comment by rmoriz** [comment]
`logtrail-6.4.2-0.1.30`

our stack/workflow:
- process output with ansi color is written to a file on a node
- `fluentbit` picks up the file, delivers it to a remote `fluentd`
- `fluentd` pushes it to `elasticsearch`
- `kibana` with `logtrail` is used to watch.

I'll investigate if any process destroys/strippes the escape codes and report back

**Comment by sivasamyk** [comment]
@rmoriz Did you find out if the ANSI colors are removed anywhere in the pipeline?
