### ISSUE TITLE
logtrail missing specific entries

### ISSUE THREAD

**Issue by ShaheryarAhmad** [sivasamyk/logtrail#327]
I am facing an issue where my logs are being successfully stored in ES and visible on Kibana but logtrail is missing specific log entries each time.

![screenshot from 2018-11-19 14-25-33](https://user-images.githubusercontent.com/19635765/48703206-d3b29f80-ec14-11e8-956d-927d71ca2276.png)

![screenshot from 2018-11-19 14-26-06](https://user-images.githubusercontent.com/19635765/48703212-d90fea00-ec14-11e8-87e6-d136c771f3ae.png)

{
"version" : 1,
"index_patterns" : [
{
"es": {
"default_index": "logstash-*"
},
"tail_interval_in_seconds": 6,
"es_index_time_offset_in_seconds": 0,
"display_timezone": "local",
"display_timestamp_format": "MMM DD HH:mm:ss",
"max_buckets": 500,
"default_time_range_in_days" : 0,
"max_hosts": 100,
"max_events_to_keep_in_viewer": 5000,
"fields" : {
"mapping" : {
"timestamp" : "@timestamp",
"hostname" : "host",
"message": "message"
},
"message_format": "{{msg}}"
},
"color_mapping" : {
"field": "level",
"mapping": {
"error": "rgb(212, 15, 15)"
}
}
}

]
}

I have two different environment. code for generating the logs is same and for both environments logs get saved in ES successfully and fetched by kibana but logtrail is missing logs for one environment and working fine for the other environment.

log parsed by logstash and appearing on logtrail for successful env

{
"EnvId" => "5b6abf6413c2970012a5719c",
"SRVC" => "5b6abd8613c2970012a57197",
"host" => "172.18.0.1",
"level" => "info",
"message" => "{"EnvId":"5b6abf6413c2970012a5719c","FE":"true","PKG":"HA-CT-Pkg2","SRVC":"5b6abd8613c2970012a57197","Type":"FERL","level":"info","msg":"checking endpoint.... ","source":"notifier/Logging.go:41","time":"2018-11-19T07:56:25Z"}",
"source" => "notifier/Logging.go:41",
"time" => "2018-11-19T07:56:25Z",
"PKG" => "HA-CT-Pkg2",
"port" => 48674,
"@timestamp" => 2018-11-19T07:56:25.067Z,
"@version" => "1",
"msg" => "checking endpoint.... ",
"Type" => "FERL",
"FE" => "true"
}

log parsed by logstash and appearing on kibana but not logtrail.

{
"EnvId" => "5bf264dba7d8f70020000008",
"SRVC" => "5b31f2805b13b30012730e98",
"host" => "172.18.0.1",
"level" => "error",
"message" => "{"EnvId":"5bf264dba7d8f70020000008","FE":"true","PKG":"CR-AWS","SRVC":"5b31f2805b13b30012730e98","Type":"FERL","level":"error","msg":"Cannot create subnet group for rds ","source":"notifier/Logging.go:34","time":"2018-11-19T07:56:11Z"}",
"source" => "notifier/Logging.go:34",
"time" => "2018-11-19T07:56:11Z",
"PKG" => "CR-AWS",
"port" => 48674,
"@timestamp" => 2018-11-19T07:56:11.050Z,
"@version" => "1",
"msg" => "Cannot create subnet group for rds ",
"Type" => "FERL",
"FE" => "true"
}

**Comment by sivasamyk** [comment]
Are the logs missing only during live tail? Does fresh fetch of logs shows the missing logs in logtrail?

**Comment by ShaheryarAhmad** [comment]
No, logs are not shown even on refreshing.

**Comment by ShaheryarAhmad** [comment]
resolved
