### ISSUE TITLE
Plugin installation was unsuccessful 

### ISSUE THREAD

**Issue by doublewhammy** [sivasamyk/logtrail#329]
Having an issue with what appears to be be a node java memory issue. Out of the box install on CentOS7 with 16GB ram sitting idle, have tried Kibana 6.5.0-1 and the latest with same results. SELinux temp off. Can anyone shed any light on what is going astray at all? (edit - time between optimizing and caching browser bundles and error message is around 15/20 mins) 

-------------------------------------------------------------------------------------------------------------
@es-node01 kibana] ./bin/kibana-plugin install https://github.com/sivasamyk/logtrail/releases/download/v0.1.30/logtrail-6.5.0-0.1.30.zip
Attempting to transfer from https://github.com/sivasamyk/logtrail/releases/download/v0.1.30/logtrail-6.5.0-0.1.30.zip
Transferring 2083168 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Extracting plugin archive
Extraction complete
Optimizing and caching browser bundles...

Plugin installation was unsuccessful due to error "Command failed: /usr/share/kibana/node/bin/node /usr/share/kibana/src/cli --env.name=production --optimize.useBundleCache=false --server.autoListen=false --plugins.initialize=false
(node:1673) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/usr/share/kibana/node/bin/node]
 2: 0x8c21ec [/usr/share/kibana/node/bin/node]
 3: v8::Utils::ReportOOMFailure(char const*, bool) [/usr/share/kibana/node/bin/node]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/usr/share/kibana/node/bin/node]
 5: v8::internal::Factory::NewRawTwoByteString(int, v8::internal::PretenureFlag) [/usr/share/kibana/node/bin/node]
 6: v8::internal::String::SlowFlatten(v8::internal::Handle<v8::internal::ConsString>, v8::internal::PretenureFlag) [/usr/share/kibana/node/bin/node]
 7: v8::internal::String::Flatten(v8::internal::Handle<v8::internal::String>, v8::internal::PretenureFlag) [/usr/share/kibana/node/bin/node]
 8: v8::internal::String::LastIndexOf(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>) [/usr/share/kibana/node/bin/node]
 9: v8::internal::Builtin_StringPrototypeLastIndexOf(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/share/kibana/node/bin/node]
10: 0x2cd4e540697d

{"type":"log","@timestamp":"2018-11-22T12:00:23Z","tags":["info","optimize"],"pid":1673,"message":"Optimizing and caching bundles for ml, logtrail, stateSessionStorageRedirect, status_page, timelion, graph, monitoring, space_selector, login, logout, dashboardViewer, apm, canvas, infra and kibana. This may take a few minutes"}

<--- Last few GCs --->

[1673:0x3819bc0]  1413789 ms: Mark-sweep 1321.7 (1469.9) -> 1321.6 (1470.9) MB, 1840.7 / 0.0 ms  allocation failure GC in old space requested
[1673:0x3819bc0]  1415861 ms: Mark-sweep 1321.6 (1470.9) -> 1321.6 (1436.9) MB, 2071.7 / 0.0 ms  last resort GC in old space requested
[1673:0x3819bc0]  1417735 ms: Mark-sweep 1321.6 (1436.9) -> 1321.6 (1436.9) MB, 1874.2 / 0.0 ms  last resort GC in old space requested

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x1208d9e25879 <JSObject>
    0: builtin exit frame: lastIndexOf(this=0x13287894e941 <Very long string[6713195]>,0x11830028ca51 <String[1]\: \n>)

    1: has_nlb(aka has_nlb) [0x13bdeff822d1 <undefined>:5970] [bytecode=0x32eac8b9f4a9 offset=15](this=0x13bdeff822d1 <undefined>)
    2: prepend_comments [0x13bdeff822d1 <undefined>:~5974] [pc=0x2cd4e6dc9c7f](this=0x2d17158d0f41 <Object map = 0x68a3b724229>,node=0x3eac5a8f7a2...

**Comment by sivasamyk** [comment]
Might be regression in Kibana. Can you try the workaround mentioned here? - https://github.com/elastic/kibana/issues/21794

**Comment by doublewhammy** [comment]
Ahh that got it ! Did need to export the variable which was not indicated on 21794 so updating to to 6.5.1 and using the following ended with success:

export NODE_OPTIONS=--max_old_space_size=4096
bin/kibana-plugin install file:///usr/share/kibana/logtrail-6.5.1-0.1.30.zip

Many thanks for the pointer - should of searched harder and fixed myself!
