### ISSUE TITLE
Support for Kibana 6.5.3

### ISSUE THREAD

**Issue by alexbowers** [sivasamyk/logtrail#332]
Is support for Kibana 6.5.3 expected soon?

Thanks

**Comment by alexbowers** [comment]
PR sent in https://github.com/sivasamyk/logtrail/pull/333

**Comment by sivasamyk** [comment]
Thanks for the PR! Download the package from https://github.com/sivasamyk/logtrail/releases/download/v0.1.30/logtrail-6.5.3-0.1.30.zip
