### ISSUE TITLE
Color mapping issue advice needed

### ISSUE THREAD

**Issue by joiningnat** [sivasamyk/logtrail#334]
Hi Sivasamy,
I need your advise on color mapping which works unexpectedly (6.5.2 version):
**logtrail.json**:
  "message_format": "{{{log_level}}} | {{{thread_id}}} | {{{thread_name}}} | {{{rest_message}}}",
        "keyword_suffix" : "keyword"
      },
      "color_mapping" : {
      "field": "log_level",
      "mapping": {
        "E": "#FF0000",
        "W": "#FFEF96",
        "D": "#B5E7A0"
              }
**Logtrail:**
![image](https://user-images.githubusercontent.com/29659271/50478692-9e535b80-09e3-11e9-81c0-1b6fb916f816.png)

**Logstash log**:
 "thread_id" => "0x80379ade0",
       "log_level" => "D",
       "timestamp" => "2018-12-27 14:32:16.343455",
    "rest_message" => ": \"Update\" executed successfully.",
      "@timestamp" => 2018-12-27T11:32:23.267Z,
      "source_log" => "some_log"
}

It seems that only pipes from message format are colored.

Thanks in advance!

**Comment by sivasamyk** [comment]
Hi @joiningnat Can you try this message format? `"message_format": "{{{log_level}}} | {{{thread_id}}} | {{{thread_name}}} | {{rest_message}}",`. Can you also share the complete logtrail.json?

**Comment by joiningnat** [comment]
Hi @sivasamyk, I updated the message format and now get the colored rest_message as you described.
![image](https://user-images.githubusercontent.com/29659271/50901148-61965400-1428-11e9-825e-83e03dcc3721.png)

Here is my logtrail.json:
`{
  "version" : 2,
  "index_patterns" : [
	{      
      "es": {
        "default_index": "front1_cloudwebservice*"
      },
      "tail_interval_in_seconds": 10,
      "es_index_time_offset_in_seconds": 0,
      "display_timezone": "local",
      "display_timestamp_format": "MMM DD HH:mm:ss",
      "max_buckets": 500,
      "default_time_range_in_days" : 0,
      "max_hosts": 100,
      "max_events_to_keep_in_viewer": 5000,
      "default_search": "",
      "fields" : {
        "mapping" : {
            "hostname" : "env",
            "timestamp" : "@timestamp",
            "program": "",
            "message": "message"
        },
        "message_format": "{{{log_level}}} | {{{thread_id}}} | {{{thread_name}}} | {{rest_message}}",
        "keyword_suffix" : "keyword"
      },
      "color_mapping" : {
      "field": "log_level",
      "mapping": {
        "E": "#FF0000",
        "W": "#FFEF96",
        "D": "#B5E7A0"
              }
     }
  }

  ]
}`
