### ISSUE TITLE
Support for Kibana 6.6.0

### ISSUE THREAD

**Issue by chetanc** [sivasamyk/logtrail#338]
We tried updating kibana.version in logtrail package.json. 
It seems there are some Kibana APIs broken which are consumed by logtrail.

**Comment by gabrielcalderon** [comment]
@sivasamyk Kibana 6.6 API changes are listed here: https://www.elastic.co/blog/kibana-plugin-api-changes-in-6-6

**Comment by sammcj** [comment]
Any update on this, it's preventing us from upgrading at present, let me know if there is a beta version you'd like me to test and report back on.

**Comment by alexizmailov** [comment]
+1

**Comment by sivasamyk** [comment]
Tried adding support for 6.6 over the weekend. But looks like something is broken from the API (apart for document changes 6.6), due to which the left-hand sidebar (the one with app icons) is not rendering properly on selecting logtrail. Will investigate further

**Comment by sivasamyk** [comment]
Released a initial version with support for 6.6 - https://github.com/sivasamyk/logtrail/releases/download/v0.1.31/logtrail-6.6.0-0.1.31.zip

Known issues (will continue to debug and release when fixed):

- on selecting logtrail the icons won't be rendered properly
- boom not handled properly

**Comment by sivasamyk** [comment]
Released a new version 6.6.1 and fixed issue with sidebar icons when logtrail is selected

https://github.com/sivasamyk/logtrail/releases/download/v0.1.31/logtrail-6.6.1-0.1.31.zip
