### ISSUE TITLE
Support for 6.7.1

### ISSUE THREAD

**Issue by sk4mi** [sivasamyk/logtrail#348]
Hi!
I’ll update my elastic cluster to 6.7.1, could you update logtrail to 6.7.1 too ?
Thanks in advance.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by sivasamyk** [comment]
Here you go! - https://github.com/sivasamyk/logtrail/releases/download/v0.1.31/logtrail-6.7.1-0.1.31.zip
