### ISSUE TITLE
whether next version of logtrail that is compatible with kibana version 7 is available?

### ISSUE THREAD

**Issue by saravanakumarangamuthu** [sivasamyk/logtrail#353]
I am trying to install logtrail on our kibana and I am using kibana7

# /usr/share/kibana/bin/kibana --version
7.0.1
++++
Attempting to transfer from https://github.com/sivasamyk/logtrail/releases/download/v0.1.31/logtrail-6.7.1-0.1.31.zip
Transferring 3878451 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Extracting plugin archive
Extraction complete
Plugin installation was unsuccessful due to error "Plugin logtrail [6.7.1] is incompatible with Kibana [7.0.1]"

**Comment by saravanakumarangamuthu** [comment]
I have downloaded, tried changing kibana version on package.json, but couldn't install the same with kibana_plugin install command(looks like it expects an url)

**Comment by sand-max** [comment]
I replaced version on package.json to 7.1.0  and plugin started(but it was installed before update ELK to 7.1.0). And plugin has liitle trouble with fields I suppose because of changed kibana UI.

**Comment by saravanakumarangamuthu** [comment]
i think https://github.com/sivasamyk/logtrail/blob/master/docs/how_to.md#2-update-kibanaversion-in-logtrail-plugin-archive is working, but sivasamy can you please confirm?

**Comment by stdeviation** [comment]
> I have downloaded, tried changing kibana version on package.json, but couldn't install the same with kibana-plugin install command(looks like it expects an url)

You can still install the plugin using file:/// url

i.e ./bin/kibana-plugin install file:///usr/share/kibana/plugins/logtrail-7.1.0.zip

**Comment by sand-max** [comment]
> > I have downloaded, tried changing kibana version on package.json, but couldn't install the same with kibana-plugin install command(looks like it expects an url)
> 
> You can still install the plugin using file:/// url
> 
> i.e ./bin/kibana-plugin install file:///usr/share/kibana/plugins/logtrail-7.1.0.zip

But last version  logtrail-6.7.1-0.1.31.zip, Where is located logtrail-7.1.0.zip?

**Comment by sivasamyk** [comment]
@sand-max logtrail for 7.1.0 is not yet release. The instructions are to install logtrail plugin built locally using https://github.com/sivasamyk/logtrail/blob/master/docs/how_to.md#2-update-kibanaversion-in-logtrail-plugin-archive. I will release new version 7.x kibana this weekend.

**Comment by sivasamyk** [comment]
https://github.com/sivasamyk/logtrail/releases/download/v0.1.31/logtrail-7.1.0-0.1.31.zip - logtrail plugin release for 7.1.0

**Comment by sand-max** [comment]
Hi!

Looks like need to correct CSS

Thanks by advance!



>Пятница, 24 мая 2019, 19:58 +03:00 от Sivasamy Kaliappan <notifications@github.com>:
>
>https://github.com/sivasamyk/logtrail/releases/download/v0.1.31/logtrail-7.1.0-0.1.31.zip - logtrail plugin release for 7.1.0
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
Макс

**Comment by acarsercan** [comment]
@sand-max seen the issue

**Comment by tmihaldinec** [comment]
hi
now when 7.1.0 is working fine.. when can we expect 7.1.1 
thanks

**Comment by sivasamyk** [comment]
Logtrail  for 7.1.1 is at https://github.com/sivasamyk/logtrail/releases/download/v0.1.31/logtrail-7.1.1-0.1.31.zip

**Comment by sivasamyk** [comment]
Will add support to 7.2 once it is GA.
