### ISSUE TITLE
Will log trail support 7.2.0 Kibana

### ISSUE THREAD

**Issue by abhi-dwivedi** [sivasamyk/logtrail#356]
Will log trail support 7.2.0 Kibana?

**Comment by sivasamyk** [comment]
Here you go - https://github.com/sivasamyk/logtrail/releases/download/v0.1.31/logtrail-7.2.0-0.1.31.zip

**Comment by abhi-dwivedi** [comment]
Hi

After installing this plugin how can i see the in kibana UI
