### ISSUE TITLE
Will Logtrail supported 7.3.0?

### ISSUE THREAD

**Issue by nuaays** [sivasamyk/logtrail#359]

**Comment by sivasamyk** [comment]
Yes. Will make a release this weekend.

**Comment by bmerry** [comment]
Note that Kibana 7.3.1 has just been released.

**Comment by sivasamyk** [comment]
Released 7.3.0 - https://github.com/sivasamyk/logtrail/releases/download/v0.1.31/logtrail-7.3.0-0.1.31.zip and 7.3.1 - https://github.com/sivasamyk/logtrail/releases/download/v0.1.31/logtrail-7.3.1-0.1.31.zip
