### ISSUE TITLE
How can I set my index?

### ISSUE THREAD

**Issue by LiuZeng520** [sivasamyk/logtrail#360]
![image](https://user-images.githubusercontent.com/43592564/64141240-d98f0f80-ce39-11e9-8252-d00f100faae5.png)

How can I choose an index like this?

![image](https://user-images.githubusercontent.com/43592564/64141292-0e9b6200-ce3a-11e9-86a7-b0513bf66bb6.png)

thank you very much.

**Comment by sivasamyk** [comment]
Hi @LiuZeng520, You can configure multiple index patterns in `logtrail.json`. Checkout the example here - https://github.com/sivasamyk/logtrail/issues/304#issuecomment-413800784
