### ISSUE TITLE
Kibana 7.4.0 support

### ISSUE THREAD

**Issue by verenion** [sivasamyk/logtrail#365]
Will there be an official kibana 7.4.0 release? If so, any guesses on when that might be?

**Comment by sivasamyk** [comment]
Here you go! - https://github.com/sivasamyk/logtrail/releases/download/v0.1.31/logtrail-7.4.0-0.1.31.zip

**Comment by verenion** [comment]
Hmm. I can't seem to see what's wrong with this, but using that plugin causes kibana to not start correctly.

I get "Kibana server is not ready yet" when I try to access the page, but there are no errors in the log at all. Any ideas?
