### ISSUE TITLE
Is it possible to add custom javascript in logtrail?

### ISSUE THREAD

**Issue by jemijin** [sivasamyk/logtrail#371]
Hi!!! This plugin is really useful to me. Thanks.

Then I have 1 question.
I want to add some javascript code for UI data representation.
Do you have any way to do this?

**Comment by sivasamyk** [comment]
Hi, You need dev env to adjust the code in logtrail.
- setup kibana dev env - https://github.com/elastic/kibana/blob/master/CONTRIBUTING.md#setting-up-your-development-environment
- setup plugin dev env and clone logtrail source code - https://www.elastic.co/guide/en/kibana/current/development-plugin-resources.html - you need to clone the logtrail repo inside `plugins` dir of kibana
- modify logtrail code and test
- build a custom version of logtrail

**Comment by jemijin** [comment]
Thanks your reply. 
One more question.
Do you have any way to run logtrail without kibana?

**Comment by sivasamyk** [comment]
No. Logtrail is developed to be Kibana plugin and it has a lot of dependency on Kibana API.

**Comment by jemijin** [comment]
Okay. thanks!!!!
