### ISSUE TITLE
Using firefox, userDateTime input text is not visible

### ISSUE THREAD

**Issue by fbaligand** [sivasamyk/logtrail#38]
When I use LogTrail in firefox, if I type some text in userDateTime input, it is not visible. 
It seems that text is displayed using blank color.

I don't reproduce the problem with Chrome or Edge.

Here's an example :
![image](https://cloud.githubusercontent.com/assets/3750300/22173561/ed6798b4-dfc7-11e6-9624-9b9a28c1b6a3.png)

I have entered "05/Nov/2016 23:00 AM", but entered text is not visible.

Environment : I use firefox 50.1 (last version) and LogTrail for Kibana 4.x

**Comment by fbaligand** [comment]
Sorry @sivasamyk, I hadn't seen you fixed the issue (I'm not notified when a commit references the issue).
So, lately : many thanks for this fix !

Is it possible to backport the fix for Kibana 4 ?

**Comment by sivasamyk** [comment]
@fbaligand https://github.com/sivasamyk/logtrail/releases/download/0.1.8/logtrail-4.x-0.1.8.tar.gz - Updated a new 4.x release with the fix. Let me know if you face any issues.

**Comment by fbaligand** [comment]
I just tested it and it works perfectly !
Thank you very much !
