### ISSUE TITLE
How to delete old logs

### ISSUE THREAD

**Issue by bittu664** [sivasamyk/logtrail#383]
I am using Kubernetes with logtrail  but whenever I delete the pod then the oldest pod logs still there and too much clutter so how to keep my only latest pod logs.  you can see the samples :- 
```
demo-sync.var.log.pods.fn-dev_demo-7ff4c564c7-q5tg2_ecc6b5ff-8b3b-41d3-a95b-dbf3e045b8f1.cb-sync.0.log
demo-sync.var.log.pods.fn-dev_demo-94b4cf695-r9624_0306c0fe-2a22-4046-a6ee-237824e0ce0f.cb-sync.0.log
keeto-sync.var.log.pods.fn-dev_keto-sync-b465f5fc7-8t25z_b772b2a7-9dcc-4fa7-ad29-8a1fc25ab98c.cb-sync.0.log
```
is there any solutions for this ?

**Comment by sanketrk** [comment]
We are facing same issue. In other words, how to Un-register a system or program from log-trail?

**Comment by sivasamyk** [comment]
logtrail is a frontend to view the logs stored in elasticsearch. It does not modify the content of the logs index. I assume once the pod is dead it won't be shipping the logs, so it won't clutter the logs of active pods. 

If you still need to remove the logs for dead pods, I would recommend purging them from elasticsearch periodically.
