### ISSUE TITLE
Need support for 7.6.0

### ISSUE THREAD

**Issue by sk4mi** [sivasamyk/logtrail#384]
Hello,

Could you support release 7.6.0 ?

Thank you :)

**Comment by sk4mi** [comment]
I try to fix myself version in `package.json`.

At install step, when trying:
```
/ # /sur/share/kibana/bin/kibana-plugin install file:/logtrail-7.6.0-0.1.31.zip 
```

I got this error message
`Plugin installation was unsuccessful due to error “Cannot delete files/directories outside the current working directory. Can be overridden with the ‘force’ option. `

A workaround to avoid this error is to execute install command in the `/usr/share/kibana/plugins/` directory

For a quick and dirty fix it works !

**Comment by kycfeel** [comment]
Hey. I'm also looking for a way to install the logtrail on kibana 7.6.0.

So procedures that you did is, modified the version number at package.json, and simply installed it after made a compression file named `logtrail-7.6.0-0.1.31.zip`?

**Comment by sivasamyk** [comment]
Here is the release for 7.6.0 - https://github.com/sivasamyk/logtrail/releases/download/v0.1.31/logtrail-7.6.0-0.1.31.zip and 7.6.1 - https://github.com/sivasamyk/logtrail/releases/download/v0.1.31/logtrail-7.6.1-0.1.31.zip
