### ISSUE TITLE
Plugin installation was unsuccessful due to error "Plugin logtrail [7.6.1] is incompatible with Kibana [7.6.2]"

### ISSUE THREAD

**Issue by switz** [sivasamyk/logtrail#391]
Any plans to upgrade to support Kibana 7.6.2, or is there some way of bypassing this error?

**Comment by sivasamyk** [comment]
Here you go - https://github.com/sivasamyk/logtrail/releases/download/v0.1.31/logtrail-7.6.2-0.1.31.zip

**Comment by switz** [comment]
Wow, thank you so much for the quick update! You're awesome.
