### ISSUE TITLE
Kibana 7.4.2 support

### ISSUE THREAD

**Issue by johary** [sivasamyk/logtrail#392]
Hi, 

I'm using ES 7.4.2 and I notice that there's no version of logtrail available for that version of kibana. 

Can you support this version ? 

Best regards,

**Comment by devon-whil** [comment]
Just adding that 7.4.2 is the latest version supported by aws elasticsearch.

**Comment by sivasamyk** [comment]
Here you go! - https://github.com/sivasamyk/logtrail/releases/download/v0.1.31/logtrail-7.4.2-0.1.31.zip
