### ISSUE TITLE
Request Kibana 7.7.x support

### ISSUE THREAD

**Issue by ryebread157** [sivasamyk/logtrail#395]
7.7.0 is the first release to support RHEL8/CentOS8, and we are looking forward to upgrading to it. Might a logtrail release be made for this? Much appreciation for you providing and updating logtrail, it is used regularly in my environment!

**Comment by sivasamyk** [comment]
@ryebread157 Here you go! - https://github.com/sivasamyk/logtrail/releases/download/v0.1.31/logtrail-7.7.0-0.1.31.zip

Thanks for using logtrail!

**Comment by caiconkhicon** [comment]
@sivasamyk: Hi, I am not sure if it is related, but I am trying Logtrail with Kibana 7.7.0, and Kibana cannot start with the error:
`FATAL  Error: Feature logtrail specifies app entries which are not granted to any privileges: logtrail,kibana`
Do you have any idea on this?

**Comment by ryebread157** [comment]
Thanks much for the quick turnaround @sivasamyk! I'm actually getting the exact same error as @caiconkhicon is getting though, might you please look at it? Perhaps it is caused by security changes introduced in Kibana 7.7? These don't make sense to me, but perhaps they do to you? https://www.elastic.co/guide/en/kibana/current/release-notes-7.7.0.html

**Comment by sivasamyk** [comment]
I tested in local dev setup and it worked fine. I will  install 7.7.0 official kibana release and check

**Comment by sivasamyk** [comment]
Can you please confirm if you are using Kibana with x-pack installed?

**Comment by caiconkhicon** [comment]
Hi @sivasamyk, I can confirm that I am using the Basic version with x-pack enabled

**Comment by sivasamyk** [comment]
Looks like there was an issue use to local code in last release zip - this should work - https://github.com/sivasamyk/logtrail/releases/download/v0.1.31/logtrail-7.7.0-0.1.31.zip I verified with xpack

**Comment by ryebread157** [comment]
Much thanks @sivasamyk! Just installed it and it works perfectly.
