### ISSUE TITLE
Logtrail support 7.7.1 ?

### ISSUE THREAD

**Issue by berrywirattama** [sivasamyk/logtrail#397]
Could you add support for Kibana 7.7.1 ?
thanks

**Comment by ryebread157** [comment]
Might you also please support Kibana 7.8, which just came out? The ELK stack at 7.8 is the first release where all three components support RHEL/CentOS8, see: https://www.elastic.co/support/matrix

**Comment by sivasamyk** [comment]
@berrywirattama 7.7.1 - https://github.com/sivasamyk/logtrail/releases/download/v0.1.31/logtrail-7.7.1-0.1.31.zip

@ryebread157 7.8.0 - https://github.com/sivasamyk/logtrail/releases/download/v0.1.31/logtrail-7.8.0-0.1.31.zip

**Comment by berrywirattama** [comment]
thankyou @sivasamyk

**Comment by ryebread157** [comment]
Thank you so much @sivasamyk !!!
