### ISSUE TITLE
Request for support for kibana 6.8.12

### ISSUE THREAD

**Issue by mohdahmad17** [sivasamyk/logtrail#405]
Hello, 

Elastic recommends that in order to upgrade from 6.X to 7.X to first upgrade to 6.8.X. The latest patch there is 6.8.12. Any plans to support that? Thanks.

**Comment by sivasamyk** [comment]
Can you check if this works? - https://github.com/sivasamyk/logtrail/releases/download/v0.1.31/logtrail-6.8.12-0.1.31.zip

**Comment by mohdahmad17** [comment]
Thanks!
