### ISSUE TITLE
Request for support Kibana 7.9.2

### ISSUE THREAD

**Issue by Raphyyy** [sivasamyk/logtrail#408]
Hello,

As Kibana 7.9.2 is out, could it be possible to upgrade logtrail as well ? Or is there anyway to bypass this message : 
`Plugin installation was unsuccessful due to error "Plugin logtrail [7.9.1] is incompatible with Kibana [7.9.2]"`

Thank you for your amazing work

**Comment by sivasamyk** [comment]
Here you go! - https://github.com/sivasamyk/logtrail/releases/download/v0.1.31/logtrail-7.9.2-0.1.31.zip

**Comment by Raphyyy** [comment]
Damn that was effective ! Thank you for your quick support
