### ISSUE TITLE
"Incorrect Kibana version in plugin [logtrail]. Expected [5.1.1]; found [5.1.2]"

### ISSUE THREAD

**Issue by ecuevasg** [sivasamyk/logtrail#45]
Hi,

I'm trying to install the plugin and I'm having this error:

> ./kibana-plugin install file:///tmp/logtrail-5.x-0.1.7.zip
Attempting to transfer from file:///tmp/logtrail-5.x-0.1.7.zip
Transferring 63520 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Extracting plugin archive
Extraction complete
Plugin installation was unsuccessful due to error "Incorrect Kibana version in plugin [logtrail]. Expected [5.1.1]; found [5.1.2]"

It supposed to be compatible with 5.x

Thanks for you help!

**Comment by sivasamyk** [comment]
Unfortunately Kibana has a strict restriction on the version supported for a plugin. I would recommend you to upgrade Kibana to 5.1.2 to use 0.1.7 logtrail. 

If you are forced to use Kibana 5.1.1, you can install logtrail 0.1.6 from https://github.com/sivasamyk/logtrail/releases/download/0.1.6/logtrail-5.x-0.1.6.zip

I would recommend upgrading Kibana to 5.1.2
