### ISSUE TITLE
Logtrail shows both last and first items in log

### ISSUE THREAD

**Issue by daghb** [sivasamyk/logtrail#49]
After having shown the tail elements in the log, after a small second, also the head of the log is shown below. The Javascript console hints that two requests have been made which confirms this:

{"searchText":"*","timestamp":null,"rangeType":null,"order":"desc","hostname":null,"index":"log"}
{"searchText":"*","timestamp":null,"rangeType":"gte","order":"asc","hostname":null,"index":"log"}

To me, it looks like timestamp is not set to "current time" for the initial ascending request. This works in Opera, but not in Chrome and Edge.

**Comment by sivasamyk** [comment]
Thanks for the bug report.

I assume as per the report, logtrail is working fine in Opera but not in Chrome & Edge. These was an issue similar to this earlier which has been fixed and updated in 0.1.7. Please download the latest logtrail form https://github.com/sivasamyk/logtrail/releases/tag/0.1.7 and let me know if it works.

**Comment by daghb** [comment]
Thanks for your answer. I am running the latest 0.1.7 together with Kibaian 5.1.2

**Comment by sivasamyk** [comment]
Can you let me know contents your logtrail.json file? I assume you downloaded the plugin zip today. It has been recently updated. Please make sure the config property `es_index_time_offset_in_seconds`  is correctly referenced in app.js file line# 462 in doTail function ( present in plugins/logtrail/public/app.js under kibana installation)

**Comment by daghb** [comment]
The zip is downloaded today. I don't know about the app.js file, but here is the logtrail.json. Logtrail is mapping the correct fields and I have two indexes available in the GUI.

    {
        "index_patterns" : [
            {
            "es": {
                "default_index": "log",
                "allow_url_parameter": false,
                "timezone": "CET"
            },
            "tail_interval_in_seconds": 10,
            "max_buckets": 500,
            "nested_objects" : false,
            "default_time_range_in_days" : 0,
            "fields" : {
                "mapping" : {
                    "timestamp" : "@timestamp",
                    "display_timestamp" : "@timestamp",
                    "hostname" : "hostname",
                    "program": "source",
                    "message": "message"
                }
            }
            },
            {
            "es": {
                "default_index": "message",
                "allow_url_parameter": false,
                "timezone": "CET"
            },
            "tail_interval_in_seconds": 10,
            "max_buckets": 500,
            "nested_objects" : false,
            "default_time_range_in_days" : 0,
            "fields" : {
                "mapping" : {
                    "timestamp" : "@timestamp",
                    "display_timestamp" : "@timestamp",
                    "hostname" : "sender",
                    "program": "contentType",
                    "message": "message"
                }
            }
            }
        ]
    }

**Comment by sivasamyk** [comment]
I assume you copied the logtrail.json from earlier installation. `es_index_time_offset_in_seconds` is missing. Please update yours accordingly to the latest json.

> {
  "index_patterns" : [
    {      
      "es": {
        "default_index": "logstash-*",
        "allow_url_parameter": false
      },
      "tail_interval_in_seconds": 10,
      "es_index_time_offset_in_seconds": 0,
      "display_timezone": "local",
      "display_timestamp_format": "MMM DD HH:mm:ss",
      "max_buckets": 500,
      "nested_objects" : false,
      "default_time_range_in_days" : 0,
      "fields" : {
        "mapping" : {
            "timestamp" : "@timestamp",
            "display_timestamp" : "@timestamp",
            "hostname" : "hostname",
            "program": "program",
            "message": "syslog_message"
        }
      }
    }  
  ]
}

**Comment by daghb** [comment]
Thanks, that solved the problem. Sorry for missing the information about the new field in the last comment. Magic!
