### ISSUE TITLE
logtrail ignores server.basePath from kibana

### ISSUE THREAD

**Issue by soster** [sivasamyk/logtrail#5]
It seems that logtrail works with the assumption that kibana is always running on / on the web server. This is not necessarily the case, I use the setting server.basePath: "/gt" which is ignored by logtrail.

**Comment by sivasamyk** [comment]
@soster this issue has been fixed by pull request from @benningm. I have merged to master. Will update the build later with this fix and create a new release in sometime,

**Comment by soster** [comment]
That was quick, thank you!

**Comment by sivasamyk** [comment]
Here you go. Update 0.1.2 should have the fix.
 `./bin/kibana plugin -i logtrail -u https://github.com/sivasamyk/logtrail/releases/download/v4.x-0.1.2/logtrail-4.x-0.1.2.tar.gz`

**Comment by soster** [comment]
It works, thank you very much!
