### ISSUE TITLE
Search and show more than one message field

### ISSUE THREAD

**Issue by daghb** [sivasamyk/logtrail#50]
When logging, I often attach exceptions and stack traces in addition to the log message. These are individual fields in ES, but are not shown or searched wihtin in logtrail. I wish for a possible inclusion of additional fields in the search, and perhaps some zooming function to avoid cluttering the default view, like a link on the time/date field popping up a window showing all the fields available in the index.

To get around this now, I use logtrail to find the log entry, and Sense with a time & date match to query against the index fetching the additional fields.

**Comment by sivasamyk** [comment]
You can search specific fields in ES using the following query in search bar 
`fieldname:"value"` . e.g. `stacktrace:"java.lang.String"`

**Comment by daghb** [comment]
Ah, wasn't aware of that, thanks!

Also I found I could use Tampermonkey to establish links to specific queries finding whatever I like to link to using the ID field from the log which is a hidden field. This means I have a workaround for the "zoom" behaviour.

**Comment by sivasamyk** [comment]
:+1: great
Also if possible, can you please post the Tampermonkey script, so that it can be useful for others also?

**Comment by daghb** [comment]
I definitely will - after adding a few comments and refining it for common use

**Comment by sivasamyk** [comment]
Thanks!

**Comment by sivasamyk** [comment]
@daghb In release 0.1.10 I added option to configure logtrail to show additional fields as part of the event. Click the additional fields will be list all logs matching the field value. For more info refer https://github.com/sivasamyk/logtrail/blob/message_format/docs/add_fields.md

Release 5.3.0-0.1.10 can be downloaded from https://github.com/sivasamyk/logtrail/releases/download/0.1.10/logtrail-5.3.0-0.1.10.zip

**Comment by daghb** [comment]
Great - this further widens our possibilities! BTW, we threw away the Tampermonkey script after adding the regex possibilities in the pull request we sent.

**Comment by sivasamyk** [comment]
Added support to customize the message field by adding custom fields. For more info check https://github.com/sivasamyk/logtrail/blob/message_format/docs/add_fields.md
