### ISSUE TITLE
is support for kibana 5.2.0 coming?

### ISSUE THREAD

**Issue by virtuman** [sivasamyk/logtrail#51]
are there any differences between 5.1.2 and 5.2.0 that would not make it possible to use logtrail with most recent kibana?

**Comment by sivasamyk** [comment]
Yes! There are some API changes in 5.2. Will push a release soon.

**Comment by sivasamyk** [comment]
Use the latest binary from https://github.com/sivasamyk/logtrail/releases/download/0.1.8/logtrail-5.2.0-0.1.8.zip

**Comment by cadab** [comment]
Ive tried installing but i get the following error:

Plugin installation was unsuccessful due to error "Incorrect Kibana version in plugin [logtrail]. Expected [5.2.1]; found [5.2.0]"
