### ISSUE TITLE
Support for Logstash/ES 5.X templates (.keyword)

### ISSUE THREAD

**Issue by Bizzelicious** [sivasamyk/logtrail#53]
In 5.X templates; .raw fields has a **.keyword** extension instead. See https://github.com/logstash-plugins/logstash-output-elasticsearch/blob/master/lib/logstash/outputs/elasticsearch/elasticsearch-template-es5x.json for the default template.

If you are using 5.x templates, you won't be able to "click" on systems or host in the Logtrail gui, since those defaults to .raw extensions.

**Comment by sivasamyk** [comment]
In 0.1.8 release, I have updated the code to use 5.X templates. You might have to upgrade Kibana & ES to 5.2.0

https://github.com/sivasamyk/logtrail/releases/download/0.1.8/logtrail-5.2.0-0.1.8.zip

**Comment by Bizzelicious** [comment]
Perfect! Unfortunately we're stuck on 5.1.2 Kibana since the AWS ES service is now version 5.1.1 and will probably stay there for a while. I'll try to mirror the changes.
