### ISSUE TITLE
Suggestion: Default search

### ISSUE THREAD

**Issue by Bizzelicious** [sivasamyk/logtrail#55]
In Elasticsearch we save several applications logs in the same Index. This means that per default, Logtrail will tail all the logs from all the applications.
Me as a developer for just one of these applications can see all the other logs from the other applications which I don't really care about. I can easily filter this so i only see the applications I like and since the search/filter is saved in the URL, I can easily bookmark this.
However, my suggestion is that a "default search/filter" is applied everytime I start logtrail from within Kibana. This search filter can be configured from the logtrail.json -file eg: `"default_search": "program.keyword:webb01",`. With this setting, everytime I start Logtrail I will have: `program.keyword:webb01` in the search box and thus, I will only see logs with that or those fields.

**Comment by sivasamyk** [comment]
added `default_search` parameter in logtrail.json. Checkout the latest release at https://github.com/sivasamyk/logtrail/releases/tag/v0.1.29
