### ISSUE TITLE
eventIds not updated on 'prepend' action

### ISSUE THREAD

**Issue by markmssd** [sivasamyk/logtrail#56]
Hey,

When doing an 'append' action, the eventIds is being updated with the new logs (after ```removeDuplicates(newLogs)``` method), to avoid duplicates in the list.

However, on 'prepend' action, new logs are being added to the ```$scope.events``` array, but ```eventIds``` is not being updated. It is missing the ```eventIds.add(event.id);``` line after this one: https://github.com/sivasamyk/logtrail/blob/master/public/app.js#L241

**Comment by sivasamyk** [comment]
Good catch. Thanks!

**Comment by markmssd** [comment]
Thumbs up for that super fast fix! 👍
