### ISSUE TITLE
Logtrail versioning is confusing

### ISSUE THREAD

**Issue by C0rn3j** [sivasamyk/logtrail#58]
I'm currently on 5.1.2 (waiting to see what Gitlab EE will support in the next release), and from the documentation it is a bit unclear whether the current plugin version only works with 5.2.0 or any 5.x. 

My guess is 5.x will work fine, but could you simply say "up to 5.2.0" if that is the case? Thanks!
 
> Logtrail is supported and tested with Kibana 4.x and **5.x**

>Kibana **5.2.0** : ./bin/kibana-plugin install https://github.com/sivasamyk/logtrail/releases/download/0.1.8/logtrail-5.2.0-0.1.8.zip

EDIT: Checking release notes  for older versions- 

> 3) Support for Kibana 5.1.2 ( no backward compatible to 5.1.1) 

So it only supports some versions... The latest release is named 5.2.0, does it support 5.1.2? This is confusing

**Comment by sivasamyk** [comment]
Kibana forces exact version match between Kibana and plugins from 5.x version on wards. Initially the plan was to have 2 logtrail releases each for 4.x and 5.x. So the logtrail plugin releases were named accordingly. But from 0.1.8 version, I removed the 5.x version string and started mentioning exact Kibana release in logtrail release version. So each version of logtrail supports only specific version of Kibana (this will be mentioned in the version string) will be supported (from 4.x releases are compatible across minor release versions). 

https://github.com/sivasamyk/logtrail/releases/tag/0.1.8 - This release will supports only 5.2.0 Kibana. The releases are not backward/forward compatible. 

Hope this helps.

**Comment by C0rn3j** [comment]
I see, thanks a lot. 

https://gitlab.com/gitlab-org/gitlab-ee/issues/1253

Would you consider backporting the patches to ES 5.1.2 if this is what Gitlab EE will end up using(and it seems like that's the case)?

I'll understand if you'll only want to keep moving forwards though ^^

**Comment by sivasamyk** [comment]
@C0rn3j Sorry that I cannot backup port all the patches to 5.1.2. If you are interested in any specific issue, I can help you in porting the fix to 5.1.2.

**Comment by C0rn3j** [comment]
Hi, that's understandable, what I ran into was the 10(?) Servers only to
choose from when there's more of them, it's not that vital(as I can just
filter it manually) but it'd be nice to have ^^

**Comment by sivasamyk** [comment]
Moved the versioning of logtrail release like logtrail-es-version-logtrail-version.zip . With this the logtrail plugin will exactly specify the elasticsearch version it supports

e.g. logtrail-5.2.2-0.1.9.zip
