### ISSUE TITLE
How do you install on 5.1.1? 

### ISSUE THREAD

**Issue by cjlyons81** [sivasamyk/logtrail#62]
I tried to install with the 5.2 version provided but get an error that my version does not match.  I assume this can be installed on any 5.x version...

Thanks!

**Comment by sivasamyk** [comment]
@cjlyons81 The latest version of logtrail supports only 5.2 Kibana version. Kibana forces strict match between Kibana and plugin versions. 

For 5.1.1 Kibana, use https://github.com/sivasamyk/logtrail/releases/download/0.1.6/logtrail-5.x-0.1.6.zip
Please be aware that the bug fixes will be available only in latest releases.
