### ISSUE TITLE
Logtrail plugin fails to install on Kibana 5.2.2

### ISSUE THREAD

**Issue by AndrewStickler** [sivasamyk/logtrail#63]
Install of the 1.8.0 plug-in fails with:
Plugin installation was unsuccessful due to error "Incorrect Kibana version in plugin [logtrail]. Expected [5.2.2]; found [5.2.0]"

Is there no way to specify the plugin as supporting 5.x or 5.2.x rather than the explicit 5.2.0?

Thanks,
Andrew

**Comment by sivasamyk** [comment]
Kibana requires the exact match of Kibana and version specified in plugin. I will release a new version soon to support 5.2.2
Meanwhile you can unzip the logtrail.zip file and update the kibana.version to 5.2.2 in package.json and zip it back. Please note this logtrail has not been sanity tested against Kibana 5.2.2.

**Comment by lisakaymera** [comment]
Will there be a version to support 5.2.1?

**Comment by sivasamyk** [comment]
Yes

**Comment by danielmotaleite** [comment]
Please notice that it is elastic that is enforcing that the plugin matches the kibana/logstash/elasticsearch version. They probably do not want broken plugins... but that also require more work for the plugin maintainer or users to manually unzip, fix the version, rezip, deploy and pray that it is still compatible.

**Comment by jetnet** [comment]
hm, changing the "kibana.version"  to "5.2.2" in the package.json does not work for me:

```
Attempting to transfer from file://C:/install/ELK/logtrail-5.2.0-0.1.8.zip
Transferring 68377 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Error: Unsupported file type "undefined"
Plugin installation was unsuccessful due to error "Error retrieving metadata from plugin archive"
```

does it check the checksum?
Thanks!

**Comment by danielmotaleite** [comment]
i just done this and it worked fine!

maybe you mess something in the file (like changing file format, from Unix to DOS)

Try again and make sure a diff will report the version line as the only change.

**Comment by jetnet** [comment]
thank you for verifying! I just tried another archiver (7z) and it worked too!
It seems, that the previous one (Double Commander built-in) screwed up the archive somehow.
Thanks again!

**Comment by sivasamyk** [comment]
Use the latest release from https://github.com/sivasamyk/logtrail/releases/download/0.1.9/logtrail-5.2.2-0.1.9.zip

**Comment by noel-reddy** [comment]
The plugin does not work for kibana 5.2.2. 
Plugin installation was unsuccessful due to error "Incorrect Kibana version in plugin [logtrail]. Expected [5.5.2]; found [5.2.2]"

"Use the latest release from https://github.com/sivasamyk/logtrail/releases/download/0.1.9/logtrail-5.2.2-0.1.9.zip"
