### ISSUE TITLE
Docker image of Kibana with logtrail

### ISSUE THREAD

**Issue by rutsky** [sivasamyk/logtrail#64]
What is the best way to use logtrail in container-based pipeline, for example when Kibana is installed from the docker images (e.g. in Kubernetes deployment)?

Should there be Kibana Docker image with preinstalled logtrail (e.g. on Docker Hub) or there are better ways to install Kibana plugins to containerized Kibana distributions?

**Comment by sivasamyk** [comment]
Currently logtrail does not support official docker image.

There are few dockerfiles with Kibana + logtrail intergration. They may not be updated with logtrail releases.  Checkout : https://hub.docker.com/r/linkyard/kibana-logtrail/~/dockerfile/

**Comment by rutsky** [comment]
@sivasamyk thanks for your respond!

[Here](https://github.com/docker-library/kibana/issues/27#issuecomment-166761497) @tianon says that probably best way to create custom Docker image with preinstalled plugins.

This approach is not very convenient, but looks like there is no alternative.

**Comment by rutsky** [comment]
I don't see easy way to create "composable" solution, so for myself I created custom Kibana image with installed logtrail plugin: https://github.com/rutsky/kibana-logtrail-kubernetes

I'm using it as a replacement for Kubernetes' Kibana image, so it based on it.

Feel free to reopen this issue if you think it should be considered in more general way.
