### ISSUE TITLE
Document how to generate one logtrail release ?

### ISSUE THREAD

**Issue by harobed** [sivasamyk/logtrail#67]
Document how to generate one logtrail release ? (this file for instance: https://github.com/sivasamyk/logtrail/releases/download/0.1.8/logtrail-5.2.0-0.1.8.zip)

**Comment by harobed** [comment]
I found this solution:

```
$ git clone git@github.com:sivasamyk/logtrail.git -b 5.2.0_support
$ cd logtrail/
$ npm install
$ export PATH=`pwd`/node_modules/.bin/:$PATH
$ npm run build
$ ./build.sh
$ ls build/logtrail-0.1.8.zip
build/logtrail-0.1.8.zip
```

**Comment by danielmotaleite** [comment]
npm install returns this to me:

npm ERR! 404 'elastic/eslint-config-kibana' is not in the npm registry.

**Comment by sivasamyk** [comment]
logtrail use 0.0.2 version. npm show versions shows 0.0.2 version in npm registry. 

```
npm show @elastic/eslint-config-kibana versions
 
[ '0.0.1',
  '0.0.2',
  '0.0.3',
  '0.1.0',
  '0.2.0-alpha1',
  '0.2.0',
  '0.2.1',
  '0.2.2',
  '0.3.0',
  '0.4.0',
  '0.5.0',
  '0.6.0',
  '0.6.1',
  '0.7.0',
  '0.8.0',
  '0.8.1',
  '0.9.0',
  '0.10.0',
  '0.11.0' ]


```

**Comment by sivasamyk** [comment]
Added a How To item to describe how to update kibana version in package.json
https://github.com/sivasamyk/logtrail/blob/master/docs/how_to.md#2-update-kibanaversion-in-logtrail-plugin-archive
Note: Changing version in package is not guaranteed to work across all Kibana versions.
