### ISSUE TITLE
'All Systems' button shows only [All Systems]

### ISSUE THREAD

**Issue by gerulf-profitsee** [sivasamyk/logtrail#69]
i am using https://github.com/sivasamyk/logtrail/releases/download/0.1.8/logtrail-5.2.0-0.1.8.zip with Kibana and Elasticsearch 5.2.0.

A typical entry in logtrail looks like this:

> Mar 11 13:40:01 group1/machine1/m1-container_type3 cron: (root) CMD (test -x /usr/sbin/run-crons && /usr/sbin/run-crons)
> Mar 11 13:40:01 group1/machine1/src@machine1 cron: (root) CMD (test -x /usr/sbin/run-crons && /usr/sbin/run-crons)
> Mar 11 13:40:01 group1/machine1/m1-container_type1 cron: (root) CMD (test -x /usr/sbin/run-crons && /usr/sbin/run-crons)
> Mar 11 13:40:01 group1/machine1/m1-container_type2 cron: (root) CMD (test -x /usr/sbin/run-crons && /usr/sbin/run-crons)
> Mar 11 13:40:01 group1/machine1/m1-container_type4 cron: (root) CMD (test -x /usr/sbin/run-crons && /usr/sbin/run-crons)
> Mar 11 13:40:01 group2/machine2/src@machine2 cron: (root) CMD (test -x /usr/sbin/run-crons && /usr/sbin/run-crons)
> Mar 11 13:40:01 m1-container supervisord: [...]

**Comment by gerulf-profitsee** [comment]
my logtrail.json


```
{
  "index_patterns" : [
    {
      "es": {
        "default_index": "syslog-ng_*",
        "allow_url_parameter": false
      },
      "tail_interval_in_seconds": 10,
      "es_index_time_offset_in_seconds": 0,
      "display_timezone": "UTC",
      "display_timestamp_format": "MMM DD HH:mm:ss",
      "max_buckets": 500,
      "nested_objects" : false,
      "default_time_range_in_days" : 0,
      "max_hosts": 100,
      "max_events_to_keep_in_viewer": 5000,
      "fields" : {
        "mapping" : {
            "timestamp" : "@timestamp",
            "display_timestamp" : "@timestamp",
            "hostname" : "HOST",
            "program": "PROGRAM",
            "message": "MESSAGE"
        }
      }
    }
  ]
}
```

**Comment by sivasamyk** [comment]
Do you see any exceptions in kibana sever console or app?

Can you copy paste the sample Elastocsearch document?

**Comment by gerulf-profitsee** [comment]
no exceptions or errors on the console or in syslog. 
kibana floods the syslog with:

```
Mar 11 15:56:37 net@xxxx supervisord: kibana {"type":"response","@timestamp":"2017-03-11T15:56:37Z","tags":[],"pid":55,"method":"get","statusCode":200,"req":{"url":"/api/reporting/jobs/list_completed_since?since=2017-03-04T22%3A15%3A31.167Z","method":"get","headers":{"host":"xxxxx:5601","user-agent":"Mozilla/5.0 (Windows NT 10.0; WOW64; rv:51.0) Gecko/20100101 Firefox/51.0","accept":"application/json, text/plain, */*","accept-language":"de,en-US;q=0.7,en;q=0.3","accept-encoding":"gzip, deflate, br","kbn-system-api":"true","kbn-version":"5.2.0","referer":"https://xxxx/app/logtrail","x-forwarded-for":"xxxxx","x-forwarded-host":"xxxx","x-forwarded-server":"xxxxx","connection":"Keep-Alive"},"remoteAddress":"xxxxx","userAgent":"xxxx","referer":"https://xxxx/app/logtrail"},"res":{"statusCode":200,"responseTime":2,"contentLength":9},"message":"GET /api/reporting/jobs/list_completed_since?since=2017-03-04T22%3A15%3A31.167Z 200 2ms - 9.0B"}
Mar 11 15:56:37 net@xxxx supervisord: kibana {"type":"response","@timestamp":"2017-03-11T15:56:37Z","tags":[],"pid":55,"method":"post","statusCode":200,"req":{"url":"/logtrail/search","method":"post","headers":{"host":"xxxx:5601","user-agent":"Mozilla/5.0 (Windows NT 10.0; WOW64; rv:51.0) Gecko/20100101 Firefox/51.0","accept":"application/json, text/plain, */*","accept-language":"de,en-US;q=0.7,en;q=0.3","accept-encoding":"gzip, deflate, br","content-type":"application/json;charset=utf-8","kbn-version":"5.2.0","referer":"https://xxxx/app/logtrail","x-forwarded-for":"xxxx","x-forwarded-host":"xxxx","x-forwarded-server":"xxxx","connection":"Keep-Alive","content-length":"114"},"remoteAddress":"xxxx","userAgent":"xxxx","referer":"https://xxxx/app/logtrail"},"res":{"statusCode":200,"responseTime":4,"contentLength":9},"message":"POST /logtrail/search 200 4ms - 9.0B"}
```

otherwise, there is nothing.

**Comment by gerulf-profitsee** [comment]
```
{
  "_index": "syslog-ng_2017.03.11",
  "_type": "test",
  "_id": "xxxx",
  "_score": null,
  "_source": {
    "_SDATA": {
      "meta": {
        "sequenceId": "288"
      }
    },
    "PROGRAM": "kernel",
    "PRIORITY": "warning",
    "MESSAGE": "[585060.749160] xxxx ",
    "ISODATE": "2017-03-11T16:08:09+00:00",
    "HOST": "group1/machine1/kernsrc@machine1",
    "FACILITY": "kern",
    "@timestamp": "2017-03-11T16:08:09+00:00"
  },
  "fields": {
    "ISODATE": [
      1489248489000
    ],
    "@timestamp": [
      1489248489000
    ]
  },
  "sort": [
    1489248489000
  ]
}
```
if thats what you meant by 'sample Elastocsearch document'

**Comment by gerulf-profitsee** [comment]
also, there is no 'PAUSE' button like in the screenshot of the README.
and no banner with 'LOGTRAIL' at the top.
Instead, a 'Settings' Button next to 'Now'.
Tested with Chrome and Firefox.

When resizing the browser window fast in Firefox, the 'PAUSE' button seems to appear for a fraction of a second. But i am not 100% sure.

**Comment by ifourmanov** [comment]
Absolutely same symptoms here: kibana 5.2.0 with logtrail 5.2.0 All Systems button non functional. It's supposed to show list of the systems, right?
If i click on some system in the list filtering works just fine.

We use fqdn as system names so they contain dots naturally, not sure if it matters.

Nothing in kibana logs or F12 browser console logs

**Comment by ifourmanov** [comment]
Digged down a bit further and it turns out in elk5 they switched from .raw fields to keyword fields - https://www.elastic.co/guide/en/logstash/current/plugins-outputs-elasticsearch.html#_template_management_for_elasticsearch_5_x

I see that all fields button still tries to get raw field: https://github.com/sivasamyk/logtrail/blob/5.2.0_support/server/routes/server.js#L152

**Comment by sivasamyk** [comment]
Move all field references to .keyword

Use latest release from https://github.com/sivasamyk/logtrail/releases/download/0.1.9/logtrail-5.2.2-0.1.9.zip along with Elastic search and logstash 5.2.2
