### ISSUE TITLE
Cant user field names with dots

### ISSUE THREAD

**Issue by lacion** [sivasamyk/logtrail#7]
im editing the logtrail json for my custom setup. but im having issues with this

{
    "es": {
        "default_index": "kube-*",
        "allow_url_parameter": false,
        "timezone": "UTC"
    },
    "tail_interval_in_seconds": 10,
    "max_buckets": 500,
    "fields": {
        "mapping": {
            "timestamp": "@timestamp",
            "display_timestamp": "@timestamp",
            "hostname": "kubernetes.pod",
            "program": "kubernetes.container_name",
            "message": "message"
        }
    }
}

this is how a line in logtrail looks like

2016-09-19T23:29:03.388Z : Sep 19 23:29:02 xxxx-kube-xxx-xxxxx yyyyyy: INFO pipeline_workflow_finished_uploading_tiles

it seems its missing hostname or program, if i click on the ":" on log trail i get a empty search with this text in the search box: kubernetes.container_name: 'undefined'

**Comment by sivasamyk** [comment]
@lacion What is the elasticsearch version your are running? v2.3 and v2.4 does not allow '.' in field names.

**Comment by lacion** [comment]
v2.3.5 which is weird because i can use them in kibana ni problem.


{
  "_index": "kube-2016.09.19",
  "_type": "default_xxxx-kube-xxxxxx-xxxxxxxx",
  "_id": "AVdExPFS-2sTY4UcRmmX",
  "_score": null,
  "_source": {
    "message": "Sep 19 23:25:38 xxxxx-kube-xxxx-xxxxx dd-xxxx: INFO     xxxxxxxxxxxxxxxxxxxxxxxxxxxx\n",
    "@version": "1",
    "@timestamp": "2016-09-19T23:25:39.538Z",
    "tags": [
      "kubernetes",
      "kubernetes_filtered"
    ],
    "kubernetes": {
      "replication_controller": "xxxxx-kube-xxxxxxx",
      "pod": "xxxxxx-kube-xxxxxxxxx",
      "namespace": "default",
      "container_name": "xxxxxx",
      "container_id": "fb6032f1001e10431fc4719bfcebad4744d954e25106775595be3705f0382205"
    }
  },
  "fields": {
    "@timestamp": [
      1474327539538
    ]
  },
  "sort": [
    1474327539538
  ]
}

**Comment by sivasamyk** [comment]
I think I can see the issue. You have a nested document in ES. ( I have not tested with nested documents). This might need some fix in logtrail.

**Comment by lacion** [comment]
let me know if i can help in anyway

**Comment by sivasamyk** [comment]
@lacion I have added support for nested fields in logtrail. Install the attached plugin zip and change the value nested_objects to true in logtrail.json. 

In order get list of all hosts to show in [All Systems] button, logtrail uses aggregate queries which requires you to setup custom nested types in Elasticsearch. I have added support in logtrail hosts query but was not able test (might need your help here, if you are using something other than logstash to ship logs to ES) . Kibana also does not support aggregate queries in nested objects (checkout https://github.com/elastic/kibana/issues/1084). 

For more info on managing nested type in ES check https://www.elastic.co/guide/en/elasticsearch/guide/current/nested-objects.html

Let me know if it works for you.

[logtrail-0.1.2.tar.gz](https://github.com/sivasamyk/logtrail/files/483033/logtrail-0.1.2.tar.gz)

**Comment by lacion** [comment]
hostname and appname are now being displayable if i click on hostname the filter works and i only see logs for that host, but the app name is not working.


also first time the plugin is loaded this error comes up


logtrail.bundle.js?v=1:53444 Error while fetching hosts :  [search_parse_exception] Expected [START_OBJECT] under [path], but got a [VALUE_STRING] in [nested], with: {"line":1,"col":29}(anonymous function) @ logtrail.bundle.js?v=1:53444processQueue @ commons.bundle.js?v=1:41839(anonymous function) @ commons.bundle.js?v=1:41855$eval @ commons.bundle.js?v=1:43083$digest @ commons.bundle.js?v=1:42894$apply @ commons.bundle.js?v=1:43191done @ commons.bundle.js?v=1:37640completeRequest @ commons.bundle.js?v=1:37838requestLoaded @ commons.bundle.js?v=1:37779


this is the error in kibana log

Error while fetching hosts { [Error: [search_parse_exception] Expected [START_OBJECT] under [path], but got a [VALUE_STRING] in [nested], with: {"line":1,"col":29}]
  status: 400,
  message: '[search_parse_exception] Expected [START_OBJECT] under [path], but got a [VALUE_STRING] in [nested], with: {"line":1,"col":29}',
  path: '/kube-*/_search',
  query: {},
  body:
   { error:
      { root_cause: [Object],
        type: 'search_phase_execution_exception',
        reason: 'all shards failed',
        phase: 'query',
        grouped: true,
        failed_shards: [Object] },
     status: 400 },
  statusCode: 400,
  response: '{"error":{"root_cause":[{"type":"search_parse_exception","reason":"Expected [START_OBJECT] under [path], but got a [VALUE_STRING] in [nested]","line":1,"col":29}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"kube-2016.09.19","node":"x7LY1QspRZmVm_G06sYE5A","reason":{"type":"search_parse_exception","reason":"Expected [START_OBJECT] under [path], but got a [VALUE_STRING] in [nested]","line":1,"col":29}}]},"status":400}',
  toString: [Function],
  toJSON: [Function] }

**Comment by Malet** [comment]
I wasn't able to get this working myself using the 0.1.4 release. I've tried using `nested_objects: true` which didn't work either.

Here's my config:

```json
{
  "es": {
    "default_index": "container_logs-*",
    "allow_url_parameter": false,
    "timezone": "UTC"
  },
  "tail_interval_in_seconds": 5,
  "max_buckets": 500,
  "nested_objects" : false,
  "fields" : {
    "mapping" : {
        "timestamp" : "time",
        "display_timestamp" : "time",
        "hostname" : "host.raw",
        "program": "container_name.raw",
        "message": "log"
    }
  }
}
```

```json
{
  "_index": "container_logs-2016.11.02",
  "_type": "fluentd",
  "_id": "AVgmDerE_HzUU3u00WS0",
  "_score": null,
  "_source": {
    "log": "I1102 17:19:52.031573       1 nanny_lib.go:106] Resources are within the expected limits.\n",
    "stream": "stderr",
    "host": "10.66.4.23",
    "pod_name": "heapster-455756180-x8mmz",
    "namespace": "kube-system",
    "container_name": "eventer-nanny",
    "docker_id": "7b0cfdbbbe9d9c2b44493579664966393860178aef65c9674e3e5808d6b6b02d",
    "time": "2016-11-02T17:19:52.316341590+00:00",
  },
  "fields": {
    "time": [
      1478107192316
    ]
  },
  "sort": [
    1478107192316
  ]
}
```

Changing `container_name.raw` -> `container_name` works fine - but clicking on an `program` name link in LogTrail fills the search query, but this will not only return the container, but also other containers with matching tokens.

**Comment by sivasamyk** [comment]
@Malet Do you have the host.raw and container_name.raw fields already created in ES using some templates? From your sample document, I do not see any nested fields that requires `nested_objects:true` config.  I see that you are using fluentd to send the documents to ES. In this case the .raw fields won't be created in ES.

**Comment by Malet** [comment]
@sivasamyk I'm using a dynamic template to add those .raw fields. Querying `container_name.raw` and `host.raw` manually in the search bar in both kibana/logtrail works fine.

The links for hostname/program in the log view are empty when using the .raw fields and clicking the hostname and program links fills the query out like this: `container_name.raw: 'undefined'`

<img width="626" alt="screen shot 2016-11-17 at 13 07 49" src="https://cloud.githubusercontent.com/assets/358505/20390467/ea867e28-acc6-11e6-9e03-1aad569e64d9.png">

**Comment by sivasamyk** [comment]
Malet,

 I have fixed this by doing program search based on raw fields. Can you install attached plugin tar.gz in Kibana and let me know if it works. Please use the following configuration:

[logtrail-4.x-0.1.5.tar.gz](https://github.com/sivasamyk/logtrail/files/597640/logtrail-4.x-0.1.5.tar.gz)

<pre>
{
  "es": {
    "default_index": "container_logs-*",
    "allow_url_parameter": false,
    "timezone": "UTC"
  },
  "tail_interval_in_seconds": 5,
  "max_buckets": 500,
  "nested_objects" : false,
  "fields" : {
    "mapping" : {
        "timestamp" : "time",
        "display_timestamp" : "time",
        "hostname" : "host",
        "program": "container_name",
        "message": "log"
    }
  }
}
</pre>
