### ISSUE TITLE
Increase the field to show 

### ISSUE THREAD

**Issue by vincent927** [sivasamyk/logtrail#70]
I want to Increase the field to show more log information.
But now i can't , only show 4 fileds。
I want more,thanks a lot

**Comment by sivasamyk** [comment]
@vincent927 This feature is added in latest release of logtrail. Please upgrade and let me know your comments. 
https://github.com/sivasamyk/logtrail/releases/download/0.1.10/logtrail-5.3.0-0.1.10.zip

Please note you need to upgrade Kibana & ES to 5.3.0

To how to enable this please refer: 
https://github.com/sivasamyk/logtrail/blob/message_format/docs/add_fields.md
