### ISSUE TITLE
Logtrail No Events Found

### ISSUE THREAD

**Issue by lisakaymera** [sivasamyk/logtrail#77]
I think there's something wrong with my logtrail.json file, but I can't figure out what. I have filebeats and metricbeats in my ELK stack. To simplify matters though, I put in simple stdin inputs of the format:

![image](https://cloud.githubusercontent.com/assets/25789042/24348706/4d4f9ce0-12e5-11e7-9b0d-eda674fd6305.png)

My config file:

{
  "index_patterns" : [
    {      
      "es": {
        "default_index": "logstash-2017.03.27",
        "allow_url_parameter": false       
      },
      "tail_interval_in_seconds": 10,
      "es_index_time_offset_in_seconds": 0,
      "display_timezone": "local",
      "display_timestamp_format": "MMM DD HH:mm:ss",
      "max_buckets": 500,
      "nested_objects" : false,
      "default_time_range_in_days" : 7,
      "max_hosts": 100,
      "max_events_to_keep_in_viewer": 5000,
      "fields" : {
        "mapping" : {
            "timestamp" : "@timestamp",
            "display_timestamp" : "@timestamp", 
	    "version" : "@version",
            "id" : "_id",
            "index" : "_index",
            "score" : "_score",
            "type" : "_type",
            "hostname": "host",
            "program" : "host",
            "message" : "message"
        }
      }
    }  
  ]
}

Here are screenshots if that is easier to see:
![screenshot from 2017-03-27 12 00 35](https://cloud.githubusercontent.com/assets/25789042/24348664/2b860130-12e5-11e7-8bcd-d7dac15f54a0.png)

I wasn't sure if program was a required field, so I just put in host as program just in case.
Any tips?

**Comment by sivasamyk** [comment]
In the fields.mapping section, its enough to map only timestamp, display_timestamp, hostname, program and message. Please remove other fields. Also let me know if you are seeing any exceptions in Kibana server logs.

**Comment by lisakaymera** [comment]
That works, thank you!
