### ISSUE TITLE
Initial request causes "Request Timeout after 30000ms" error

### ISSUE THREAD

**Issue by timeu** [sivasamyk/logtrail#8]
The initial request, when opening logtrail, fails with a "Request Timeout after 30000ms". 
The log screen is empty and the loading indicator is shown. 

However when I search for a message it properly shows the messages and when I reset the search, logtrail works without any issues.

**Comment by sivasamyk** [comment]
@timeu Can check  if there are any errors in browser debug console and Kibana server logs?

**Comment by timeu** [comment]
LogTrail shows following error notification: 

`Exception while executing search query :undefined`
  

The browser console displays an error message + object: 

`Error while fetching events` 

Kibana log shows following error: 
```
Error while executing search { [Error: Request Timeout after 30000ms]
  status: undefined,
  message: 'Request Timeout after 30000ms',
  body: undefined } 
```

**Comment by sivasamyk** [comment]
As per https://github.com/elastic/kibana/issues/7120 , this happens when your Elasticsearch server is busy. Can you try increasing the timeout value if kibana.yml file?  Do you have huge number of events in ES server?

**Comment by timeu** [comment]
Yes we have quite a lot of messages, however kibana itself displays the syslog messages just fine without timeout. What is the default timerange for logtrail?

Also the error only happens for the initial load. As soon as I search for something and then reset the search it works fine without any errors

**Comment by sivasamyk** [comment]
While loading first time, logtrail fecthes latest 500 events ( i.e fetch 500 events sorted by descending order of timestamp).

**Comment by sivasamyk** [comment]
If you are indexes are based are dates, you may test by reducing the time range by editing default-index variable in logtrail.json and providing appropriate regex for index pattern (say consider index create only for this year/month)

**Comment by timeu** [comment]
Yeah that's probably the issue because we create a new index for each day and to get the first 500 events it would have to query all indices which might take a time and thus run into the timeout issue. Kibana itself does probably route the events to the correct index/indices based on the time range specified by the user. 
So the workaround is either: 

1. Increase timeout setting in Kibana. But does it really make sense to query all indices, even though we are only interested in the first 500 
2. Change the index pattern in the logtrail.json to only search only the recent indices but this is not maintainable because we would have to change it constantly. 

I think a more comprehensive solution would be if we logtrail could add some logic to restrict the search to only the recent indices/index.

**Comment by sivasamyk** [comment]
Sure. Will check how Kibana has handled this and see if logtrail can implement a similar solution.

**Comment by sivasamyk** [comment]
@timeu I have added an option in logtrail.json `default_time_range_in_days` which can be configured to specify the default time range (in days) to fetch the events from. This will be used to fetch the events when logtrail is launched. (you are free to specify or view logs outside this time range after launch). The default value is 30 days. Can you please download the attached plugin gz and configure the required time range and let me know if you are still seeing timeout?
[logtrail-0.1.2.tar.gz](https://github.com/sivasamyk/logtrail/files/489543/logtrail-0.1.2.tar.gz)

**Comment by timeu** [comment]
@sivasamyk: I tested it and it works now without a timeout ! 

Thanks !

**Comment by sivasamyk** [comment]
great!

**Comment by sivasamyk** [comment]
@timeu You can refer to #93 for dynamic date ranges in elastic search index pattern

https://www.elastic.co/guide/en/elasticsearch/reference/current/date-math-index-names.html
