### ISSUE TITLE
Multiple field mappings depending on (filebeat) type

### ISSUE THREAD

**Issue by LuckyType** [sivasamyk/logtrail#85]
We have multiple filebeat prospectors for multiple services (With different log formats obviously), would be nice if we could define multiple index_patterns depending on the prospector type.

For example, we have apache2_access, apache2_error, django, nginx and many more.
Those are parsed by logstash differently with different fields, so for some logs he is trying to map a field which doesn't exsist.

If my english is too crappy, this is what i mean:
```
{
  "index_patterns" : [
    {
      "es": {
        ...
      },
      ...
      "type" : "django",
      "fields" : {
        "mapping" : {
            "timestamp" : "@timestamp",
            "display_timestamp" : "@timestamp",
            "hostname" : "host",
            "program": "program",
            "message": "message"
        },
        "message_format": "{{level}} {{msg}}"
      }
    },
    {
      "es": {
        ...
      },
      ...
      "type" : "apache2_access",
      "fields" : {
        "mapping" : {
            "timestamp" : "@timestamp",
            "display_timestamp" : "@timestamp",
            "hostname" : "host",
            "program": "program",
            "message": "message"
        },
        "message_format": "{{vhost_name}} {{msg}}"
      }
    },
  ]
}
```

**Comment by LuckyType** [comment]
Thanks for the quick response, i already knew about the default_index thing but im not sure if this is exacly what i want. Right now we have multiple beats, these beats currently define our Index names, so filebeat indexes are always called filebeat-*. So something like this would be awesome:

```
{
	"index_patterns" : [
		{
			"es": {
				"default_index": "filebeat-*",
                                ...
			},
			...
			"type_patterns" : [
				{
					"type" : "django",
					"fields" : {
						"mapping" : {
							"timestamp" : "@timestamp",
							"display_timestamp" : "@timestamp",
							"hostname" : "host",
							"program": "program",
							"message": "message"
						},
						"message_format": "{{level}} {{msg}}"
					}
				},
				{
					"type" : "apache2_access",
					"fields" : {
						"mapping" : {
							"timestamp" : "@timestamp",
							"display_timestamp" : "@timestamp",
							"hostname" : "host",
							"program": "program",
							"message": "message"
						},
						"message_format": "{{vhost_name}} {{msg}}"
					}
				}
			]
		},
	]
}

```

**Comment by sivasamyk** [comment]
Got it. There are messages with different fields being logged under same index.   I would recommend you to use logstash to parse them and map them to different indexes or map the messages to common format. Logstash is meant to do this kind of job.

**Comment by LuckyType** [comment]
Again, thanks for the quick response. This makes way more sense i guess. I will try that out right now.

**Comment by LuckyType** [comment]
Works fine, gonna close the Issue. Thanks!!
