### ISSUE TITLE
Adding multiple indices to Logtrail

### ISSUE THREAD

**Issue by lisakaymera** [sivasamyk/logtrail#86]
Is my syntax right for adding another indice mapping? I'm not seeing it show up in Logtrail, not sure how to debug this.
{
  "index_patterns" : [
    {
      "es": {
        "default_index": "kpush-dev-*",
        "allow_url_parameter": false
      },
      "tail_interval_in_seconds": 10,
      "es_index_time_offset_in_seconds": 0,
      "display_timezone": "local",
      "display_timestamp_format": "MMM DD HH:mm:ss",
      "max_buckets": 500,
      "nested_objects" : false,
      "default_time_range_in_days" : 0,
      "max_hosts": 100,
      "max_events_to_keep_in_viewer": 5000,
      "fields" : {
        "mapping" : {
            "timestamp" : "@timestamp",
            "display_timestamp" : "@timestamp",
            "hostname" : "host",
            "program": "source",
            "message": "message"
        }
      }
    },
      {
      "es": {
	"default_index": "keepalive-*",
	"allow_url_parameter": false
      },
      "tail_interval_in_seconds": 10,
      "es_index_time_offset_in_seconds": 0,
      "display_timezone": "local",
      "display_timestamp_format": "MMM DD HH:mm:ss",
      "max_buckets": 500,
      "nested_objects" : false,
      "default_time_range_in_days" : 0,
      "max_hosts": 100,
      "max_events_to_keep_in_viewer": 5000,
      "fields" : {
	"mapping" : {
            "timestamp" : "@timestamp",
            "display_timestamp" : "@timestamp",
            "hostname" : "@host",
            "program": "http_poller_metadata.request.url",
            "message": "message"
	}
      }
    }
  ]
}

**Comment by sivasamyk** [comment]
@lisakaymera I think you index paramter should be, a pattern like **kpush-dev-***, instead of **kpush-dev-**

**Comment by soulis-siluos** [comment]
@lisakaymera is correct, all our patterns look like log-syslog-* to search through all indexes that have that pattern,  if you have only one index in ES  with the fixed name 'kpush-dev-' your pattern would likely work. but i'm guessing you have a daily pattern after it like kpush-dev-MM.DD.YYYY

**Comment by lisakaymera** [comment]
I don't think the * shows up for some reason, probably because it's a special character?
And I misspoke earlier.
Both indices show up in the settings drop down, but if I go to All Systems, I only see 'kpush-dev'.
This is only just a small issue, but I'm wondering why that is the case. 

Just to clarify - what shows up in 'All Systems' would be whatever goes under the 'hostname' field, right?
Other than that, it's a great tool and I love it!

**Comment by lisakaymera** [comment]
Also, what is 'default-index'? Should I just make one of the entries in there simply 'index'?

**Comment by sivasamyk** [comment]
@lisakaymera Glad to hear you like the tool. Thanks!

There was an issue in populating hosts dropdown case of multiple indexes #87 . This has been fixed in logtrail 0.1.11 release.

The "default-index" is the name of index pattern. You cannot change the name "default-index". The value supplied to this field should point to an index name/pattern.
Hope this helps.
