### ISSUE TITLE
Multiple Indexes in logtrail.json

### ISSUE THREAD

**Issue by soulis-siluos** [sivasamyk/logtrail#87]
Currently if you add multiple entries into logtrail.json  you can toggle between them. However on the client side, when you switch between these indexes; the available systems will always pull its entries from the first configured index in logtrail.json.  There are 2 problems here as far as i can tell.  
1)  the $scope.onSettingsChange method does not call setupHostsList() which will cause a requery for the hosts.  And secondly the query for the setupHostsList posts a get call with query parameters which are not picked up on the server side in server.js server.route({ ... })
changing the following line may be prudent to using query parameters

from 
var index = request.params.index;
to
var index = (request.query && request.query.index) ? request.query.index : request.params.index;

and on the client side in the setupHostsList() from

$http.get(chrome.addBasePath('/logtrail/hosts'),params).... 
to 
$http.get(chrome.addBasePath('/logtrail/hosts'), { 'params' : params }).

Has anyone else run into this and found a more elegant solution?

**Comment by sivasamyk** [comment]
@soulis-siluos   Thanks for the bug!

logtrail 0.1.11 has the fix for this issue.
https://github.com/sivasamyk/logtrail/releases/download/0.1.11/logtrail-5.3.0-0.1.11.zip

For changes done checkout the commit https://github.com/sivasamyk/logtrail/commit/bbad9566c4c1af47c878e78597a583de97a4df22
