### ISSUE TITLE
start a search via GET parameter

### ISSUE THREAD

**Issue by tbarbugli** [sivasamyk/logtrail#9]
is there a way to provide a search via GET param? eg. `http://path/to/logtrail/?q=searchthis`

**Comment by sivasamyk** [comment]
@tbarbugli Currently it is not possible. Will explore options to provide this feature.

**Comment by sivasamyk** [comment]
Following options are added to get params 

- q - query string
- h - host name
- t - time

These get params will be automatically updated based on current search context, so URL can be shared to go to required context.

**Comment by sivasamyk** [comment]
Fixed in 0.1.4. Install the latest release using following command

`./bin/kibana plugin -i logtrail -u https://github.com/sivasamyk/logtrail/releases/download/0.1.4/logtrail-4.x-0.1.4.tar.gz`
