### ISSUE TITLE
Clicking on the host name will show 'no events found'

### ISSUE THREAD

**Issue by lisakaymera** [sivasamyk/logtrail#90]
The Logtrail correctly shows my indices. I'm using filebeat to forward logs, and my conf file looks like this:

{
"index_patterns" : [
{
"es": {
"default_index": "kpush-dev-",
"allow_url_parameter": false
},
"tail_interval_in_seconds": 10,
"es_index_time_offset_in_seconds": 0,
"display_timezone": "local",
"display_timestamp_format": "MMM DD HH:mm:ss",
"max_buckets": 500,
"nested_objects" : false,
"default_time_range_in_days" : 0,
"max_hosts": 100,
"max_events_to_keep_in_viewer": 5000,
"fields" : {
"mapping" : {
"timestamp" : "@timestamp",
"display_timestamp" : "@timestamp",
"hostname" : "host",
"program": "source",
"message": "message"
}
}
},
{
"es": {
"default_index": "keepalive-",
"allow_url_parameter": false
},
"tail_interval_in_seconds": 10,
"es_index_time_offset_in_seconds": 0,
"display_timezone": "local",
"display_timestamp_format": "MMM DD HH:mm:ss",
"max_buckets": 500,
"nested_objects" : false,
"default_time_range_in_days" : 0,
"max_hosts": 100,
"max_events_to_keep_in_viewer": 5000,
"fields" : {
"mapping" : {
"timestamp" : "@timestamp",
"display_timestamp" : "@timestamp",
"hostname" : "@host",
"program": "http_poller_metadata.request.url",
"message": "message"
}
}
}
]
}

Here is the log format for the index that doesn't work:
![screenshot from 2017-04-09 11 51 22](https://cloud.githubusercontent.com/assets/25789042/24836067/f0f52dbc-1d1a-11e7-84a9-354b12efaa27.png)

Here is the log format for the index that actually does work.
![screenshot from 2017-04-09 11 53 54](https://cloud.githubusercontent.com/assets/25789042/24836080/3c596ba6-1d1b-11e7-8255-51c7297bb1c0.png)

1. All Systems does not show any of the hosts.
2. It seems we can click on the host name/source. When I do that, I get 'no events found'.
3. The keepalive-* index is working normally. So if I click on the host or source, I correctly get the filtered logs.
4. I don't have a template for keepalive, but I do have one for filebeat.

Any thoughts?

**Comment by sivasamyk** [comment]
@lisakaymera I assume the keepalive index is pushed via logstash. Whereas the kpush-dev is directly pushed into elasticsearch by filebeat. In case of logstash indexes, the logstash ES template is used which adds .keyword field to strings. In case of filebeat the custom template used may not have these keyword fields. On clicking the hostname is console window, logtrail will append hostname.keyword in search field. Can you remove the .keyword string manually and check if it works. I have not tested logtrail with events directly pushed from filebeat. I  will test logtrail and fix if there any issues.

**Comment by lisakaymera** [comment]
I think that is the case. Removing .keyword does not work. For some reason, my templates are not appending .keyword, and thus all of those fields are not analyzed, which I find a bigger issue.

It's probably better that I figure out why the indices pushed to elasticsearch aren't analyzed anymore.

**Comment by sivasamyk** [comment]
@lisakaymera I recommend you to configure filebeat to send the logs to logstash rather than to elasticsearch directly. This way you will get the logstash templates by default for the indexes.

**Comment by sivasamyk** [comment]
Using the right ES template in filebeat and forwarding the logs to logstash will add required analyzers. Closing the issue.
