### ISSUE TITLE
How to use nested_objects attribution

### ISSUE THREAD

**Issue by lynch0227** [sivasamyk/logtrail#91]
Hi Guys,
I have a hostname fields in the nested objects, here is the data sample:
{
         "localtime" => 2013-08-16T19:26:36.471Z,
             "level" => "ERROR",
            "logger" => "com.tst.Bar",
         "throwable" => "java.lang.tst:error message",
            "thread" => "main",
           "message" => "Message flushed with immediate flush=true",
        "@timestamp" => 2017-04-18T09:54:35.393Z,
          "@version" => "1",              
        "contextMap" => {
        "APP_BUILD_VERSION" => "111-39",
                 "HOSTNAME" => "127.0.0.1"
    }
}

when I configure nested_objects is true, then I got the below error message:
Error! Exception while fetching hosts : [parsing_exception] Expected [START_OBJECT] under [path], but got a [VALUE_STRING] in [nested], with { line=1 & col=36 }

Here is the logtrail conf:
{
  "index_patterns" : [
    {
      "es": {
        "default_index": "logstash-*",
        "allow_url_parameter": false
      },
      "tail_interval_in_seconds": 10,
      "es_index_time_offset_in_seconds": 0,
      "display_timezone": "local",
      "display_timestamp_format": "YYYY-MM-DD HH:mm:ss",
      "max_buckets": 500,
      "nested_objects" : true,
      "default_time_range_in_days" : 3,
      "max_hosts": 1000,
      "max_events_to_keep_in_viewer": 5000,
      "fields" : {
        "mapping" : {
            "timestamp" : "@timestamp",
            "display_timestamp" : "localtime",
            "hostname" : "contextMap.HOSTNAME",
            "program": "level",
            "message": "throwable"
        },
        "message_format": "{{throwable}}"
      }
    }
  ]
}

How can I fix this issue? 
Thank you.

**Comment by sivasamyk** [comment]
@lynch0227 Can you paste the complete error log from Kibana console?

**Comment by lisakaymera** [comment]
I've got the same issue, but nothing appeared in the Kibana console output

**Comment by mohamed-mfarag** [comment]
I got also the same error after enabling the nested Object to be able to read the hostname coming from the different beats - below the error log from Kibana

Error while fetching hosts { [parsing_exception] Expected [START_OBJECT] under [path], but got a [VALUE_STRING] in [nested], with { line=1 & col=36 } :: {"path":"/cbk-*/_search","query":{},"body":"{\"size\":0,\"aggs\":{\"nested\":{\"path\":\"beat\"},\"aggs\":{\"hosts\":{\"terms\":{\"field\":\"beat.hostname.keyword\",\"size\":100}}}}}","statusCode":400,"response":"{\"error\":{\"root_cause\":[{\"type\":\"parsing_exception\",\"reason\":\"Expected [START_OBJECT] under [path], but got a [VALUE_STRING] in [nested]\",\"line\":1,\"col\":36}],\"type\":\"parsing_exception\",\"reason\":\"Expected [START_OBJECT] under [path], but got a [VALUE_STRING] in [nested]\",\"line\":1,\"col\":36},\"status\":400}"}
    at respond (/opt/kibana-5.3.0-linux-x86_64/node_modules/elasticsearch/src/lib/transport.js:289:15)
    at checkRespForFailure (/opt/kibana-5.3.0-linux-x86_64/node_modules/elasticsearch/src/lib/transport.js:248:7)
    at HttpConnector.<anonymous> (/opt/kibana-5.3.0-linux-x86_64/node_modules/elasticsearch/src/lib/connectors/http.js:164:7)
    at IncomingMessage.wrapper (/opt/kibana-5.3.0-linux-x86_64/node_modules/elasticsearch/node_modules/lodash/lodash.js:4968:19)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
  status: 400,
  displayName: 'BadRequest',
  message: '[parsing_exception] Expected [START_OBJECT] under [path], but got a [VALUE_STRING] in [nested], with { line=1 & col=36 }',
  path: '/cbk-*/_search',
  query: {},
  body: 
   { error: 
      { root_cause: [Object],
        type: 'parsing_exception',
        reason: 'Expected [START_OBJECT] under [path], but got a [VALUE_STRING] in [nested]',
        line: 1,
        col: 36 },
     status: 400 },
  statusCode: 400,
  response: '{"error":{"root_cause":[{"type":"parsing_exception","reason":"Expected [START_OBJECT] under [path], but got a [VALUE_STRING] in [nested]","line":1,"col":36}],"type":"parsing_exception","reason":"Expected [START_OBJECT] under [path], but got a [VALUE_STRING] in [nested]","line":1,"col":36},"status":400}',
  toString: [Function],
  toJSON: [Function] }

**Comment by sivasamyk** [comment]
Fixed in 0.1.12 release . Download the latest release ( supported in Elastic 5.4.0) https://github.com/sivasamyk/logtrail/releases/download/0.1.12/logtrail-5.4.0-0.1.12.zip

**Comment by sasso** [comment]
This still happens in 5.3.2 version. What was the fix?

**Comment by dileepfrog** [comment]
Is there any fix for this that does not require Elasticsearch 5.4.x? We are currently using AWS Elasticsearch which constrains us to 5.3.

**Comment by sivasamyk** [comment]
@dileepfrog You can try using https://github.com/sivasamyk/logtrail/releases/download/v0.1.17/logtrail-5.4.3-0.1.17-145.zip. Unzip the file and update kibana.version to 5.3.0 or as required in package.json and zip it back. As part of fix for #145 I have removed nested_object attribute from logtrail.json. Hope this helps.
