### ISSUE TITLE
is kibvana 4 support dropped?

### ISSUE THREAD

**Issue by InformatiQ** [sivasamyk/logtrail#92]
have you dropped kibana 4 support? 
i see new releases do not have kibana 4 artifacts

**Comment by sivasamyk** [comment]
No. I did not test the recent changes with ES and Kibana 4. Will make the changes and release an update.

**Comment by InformatiQ** [comment]
great thanks

**Comment by InformatiQ** [comment]
any chnaces we get a kibana 4 update?

**Comment by sivasamyk** [comment]
@InformatiQ You can download the latest release from https://github.com/sivasamyk/logtrail/releases/download/0.1.14/logtrail-4.x-0.1.14.tar.gz

Please note 'message_format' new field is introduced in logtrail.json.
