### ISSUE TITLE
Dose highlight text support when searching?

### ISSUE THREAD

**Issue by zhengyhn** [sivasamyk/logtrail#94]
Hi,
    Thanks to this great plugin, we can view log comfortably. However, there is no highlight text when  searching. Can this feature be supported?

**Comment by tigrlily** [comment]
Hi!

I was just about to write a question on the same thing! Would be extraordinary :+1: !

Best regards, 
Magnys

**Comment by eiser82** [comment]
👍

**Comment by zhengyhn** [comment]
Thank you! We have used this feature in production!

**Comment by sivasamyk** [comment]
Awesome! I assume you did a build from master branch.

**Comment by sivasamyk** [comment]
Added support in 0.1.14 release. Download latest release @
https://github.com/sivasamyk/logtrail/releases/download/0.1.14/logtrail-5.4.0-0.1.14.zip
